### ISSUE TITLE
feature request: foundry support

### ISSUE THREAD

**Issue by cruzdanilo** [crytic/slither#1007]
![foundry](https://www.paradigm.xyz/static/Foundry_Ink_2-1024x516.jpg)
https://github.com/gakonst/foundry
https://www.paradigm.xyz/2021/12/introducing-the-foundry-ethereum-development-toolbox/

https://github.com/crytic/crytic-compile/issues/230

**Comment by gakonst** [comment]
Vote close https://github.com/gakonst/foundry/issues/705

**Comment by 0xbok** [comment]
Hi, curious if this is planned to implemented any time soon? Would love to add a slither action on our foundry repo https://github.com/ditto-lab/ditto

**Comment by 0xalpharush** [comment]
Support for foundry in crytic-compile is blocked by https://github.com/gakonst/ethers-rs/issues/1028

**Comment by mds1** [comment]
I think this should now be unblocked since https://github.com/gakonst/ethers-rs/issues/1028 and https://github.com/gakonst/ethers-rs/pull/1081 have been merged

**Comment by transmissions11** [comment]
^

**Comment by emilianobonassi** [comment]
+1 waiting for this to complete Rentable foundry migration 💪

**Comment by 0xchaosbi** [comment]
Just used Slither for the first time on our Foundry repo - worked great. Thanks all who worked on this for implementing! 🙌

**Comment by yohanelly95** [comment]
Getting an issue with slither on a foundry project I am working on, attaching the error for reference: 
slither vesion: 0.8.3 

Get this error on github actions as well as locally. 
```
Traceback (most recent call last):
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/opt/slither/lib/python3.9/site-packages/slither/slither.py", line 95, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/opt/slither/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 211, in parse_top_level_from_loaded_json
    contract.set_offset(top_level_data["src"], self._compilation_unit)
  File "/opt/slither/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 124, in set_offset
    self._source_mapping = self._convert_source_mapping(offset, compilation_unit)
  File "/opt/slither/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 101, in _convert_source_mapping
    (lines, starting_column, ending_column) = self._compute_line(
  File "/opt/slither/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 43, in _compute_line
    end_line, ending_column = compilation_unit.core.crytic_compile.get_line_from_offset(
  File "/opt/slither/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 291, in get_line_from_offset
    return lines_delimiters[offset]
KeyError: 566
None
Error in .
Traceback (most recent call last):
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/opt/slither/lib/python3.9/site-packages/slither/slither.py", line 95, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/opt/slither/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 211, in parse_top_level_from_loaded_json
    contract.set_offset(top_level_data["src"], self._compilation_unit)
  File "/opt/slither/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 124, in set_offset
    self._source_mapping = self._convert_source_mapping(offset, compilation_unit)
  File "/opt/slither/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 101, in _convert_source_mapping
    (lines, starting_column, ending_column) = self._compute_line(
  File "/opt/slither/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 43, in _compute_line
    end_line, ending_column = compilation_unit.core.crytic_compile.get_line_from_offset(
  File "/opt/slither/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 291, in get_line_from_offset
    return lines_delimiters[offset]
KeyError: 566

xargs: slither: exited with status 255; aborting

**Comment by gakonst** [comment]
Can you link to your codebase?

**Comment by adarshsrivastava11** [comment]
@yohanelly95 Are you running `slither .` on the root folder?
