### ISSUE TITLE
Incorrect parsing of call when function clashes with globally defined library (`using for *`)

### ISSUE THREAD

**Issue by iouae** [crytic/slither#1008]
Was trying to ` slither . `  an enormous DeFi project and got this `out of range` error.
```
Traceback (most recent call last):
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/slither.py", line 125, in __init__
    parser.analyze_contracts()
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 442, in analyze_contracts
    self._convert_to_slithir()
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 626, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/core/declarations/function.py", line 1708, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/core/cfg/node.py", line 720, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/slithir/convert.py", line 118, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/slithir/convert.py", line 1728, in apply_ir_heuristics
    convert_constant_types(irs)
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/slithir/convert.py", line 1664, in convert_constant_types
    t = types[idx]
IndexError: list index out of range
None
Error in .
Traceback (most recent call last):
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/slither.py", line 125, in __init__
    parser.analyze_contracts()
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 442, in analyze_contracts
    self._convert_to_slithir()
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 626, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/core/declarations/function.py", line 1708, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/core/cfg/node.py", line 720, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/slithir/convert.py", line 118, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/slithir/convert.py", line 1728, in apply_ir_heuristics
    convert_constant_types(irs)
  File "/home/solipsistic/.local/lib/python3.8/site-packages/slither/slithir/convert.py", line 1664, in convert_constant_types
    t = types[idx]
IndexError: list index out of range

```

**Comment by 0xalpharush** [comment]
It'd be helpful if can you link to codebase/ contract on Etherscan with public source code or provide a reproducible example

**Comment by iouae** [comment]
@0xalpharush Sure. [Here it is](https://github.com/fei-protocol/fei-protocol-core).

**Comment by 0xalpharush** [comment]
Solidity expression: `decimals = ERC20(address(poolAssets[i])).decimals()`
IR: `TMP_10704(int128) = LIBRARY_CALL, dest:ExtendedMath, function:decimals, arguments:['TMP_10703']`
It appears that `types` has a length of 0, but `ir.arguments` has a length of 1. I need to look into the issue more before suggesting a fix. 
https://github.com/crytic/slither/blob/168492ad899e074724b97f99cfa4d4f25934a8e5/slither/slithir/convert.py#L1662-L1664

**Comment by 0xalpharush** [comment]
The call to `.decimals` is being converted from a `HighLevelCall` to `LibraryCall` [here](https://github.com/crytic/slither/blob/630a74f96b23a397e5a4ccaaf2e5d0d533309ed2/slither/slithir/convert.py#L510-L524). This may need to be redesigned in the future.

For now, we can probably make the conversion to library calls more strict when `*` is used https://github.com/crytic/slither/blob/630a74f96b23a397e5a4ccaaf2e5d0d533309ed2/slither/slithir/convert.py#L521
