### ISSUE TITLE
unhashable type: 'list'

### ISSUE THREAD

**Issue by AnonFinDev** [crytic/slither#1017]
Trying to use Slither on Ubuntu LTS. The project is using Solidity 0.8.10, Node 14 and Python 3.9. We are facing the following issue:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/slither.py", line 125, in __init__
    parser.analyze_contracts()
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 442, in analyze_contracts
    self._convert_to_slithir()
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 626, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/core/declarations/function.py", line 1708, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/core/cfg/node.py", line 722, in slithir_generation
    self._find_read_write_call()
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/core/cfg/node.py", line 932, in _find_read_write_call
    self._high_level_calls = list(set(self._high_level_calls))
TypeError: unhashable type: 'list'
None
Error in .
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/slither.py", line 125, in __init__
    parser.analyze_contracts()
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 442, in analyze_contracts
    self._convert_to_slithir()
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 626, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/core/declarations/function.py", line 1708, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/core/cfg/node.py", line 722, in slithir_generation
    self._find_read_write_call()
  File "/opt/hostedtoolcache/Python/3.9.9/x64/lib/python3.9/site-packages/slither/core/cfg/node.py", line 932, in _find_read_write_call
    self._high_level_calls = list(set(self._high_level_calls))
TypeError: unhashable type: 'list'
```

**Comment by 0xalpharush** [comment]
Can you share the code to reproduce this bug?

**Comment by eccentricexit** [comment]
I am facing the same issue. Unfortunately I cannot share the codebase at the moment as its private but figured I should mention as well.

**Comment by nodablock** [comment]
Facing the same issue. 

solc version  0.4.19
slither 0.9.1
on mac M1 Monterey
Python 3.8.9

```
./slither ./Contract.sol                                                                                                                                                                                                           

Traceback (most recent call last):
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/__main__.py", line 97, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/__main__.py", line 75, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/slither.py", line 130, in __init__
    parser.analyze_contracts()
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 500, in analyze_contracts
    self._convert_to_slithir()
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 685, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/core/declarations/function.py", line 1705, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/core/cfg/node.py", line 719, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/slithir/convert.py", line 119, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/slithir/convert.py", line 1790, in apply_ir_heuristics
    irs = propagate_type_and_convert_call(irs, node)
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/slithir/convert.py", line 438, in propagate_type_and_convert_call
    new_ins = propagate_types(ins, node)
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/slithir/convert.py", line 529, in propagate_types
    if t in using_for or "*" in using_for:
TypeError: unhashable type: 'list'
Error in ./CityMayor.sol
Traceback (most recent call last):
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/__main__.py", line 97, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/__main__.py", line 75, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/slither.py", line 130, in __init__
    parser.analyze_contracts()
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 500, in analyze_contracts
    self._convert_to_slithir()
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 685, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/core/declarations/function.py", line 1705, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/core/cfg/node.py", line 719, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/slithir/convert.py", line 119, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/slithir/convert.py", line 1790, in apply_ir_heuristics
    irs = propagate_type_and_convert_call(irs, node)
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/slithir/convert.py", line 438, in propagate_type_and_convert_call
    new_ins = propagate_types(ins, node)
  File "/Users/eric/workspace/nodablock.com/env/lib/python3.8/site-packages/slither/slithir/convert.py", line 529, in propagate_types
    if t in using_for or "*" in using_for:
TypeError: unhashable type: 'list'
```

**Comment by 0xalpharush** [comment]
@nodablock  Would you please try 0.9.2 and open a new issue if you're still having this issue? It'd be helpful to include a code sample if possible.
