### ISSUE TITLE
HTTP 403 error

### ISSUE THREAD

**Issue by mrx23dot** [crytic/slither#1027]
running this on 0.8.2
`slither 0xb2f57ff4e1fea6100dc8ac965f08297738825fee `
this address only has byte code.

gives

```
Traceback (most recent call last):
  File "/home/slither/slither/slither/__main__.py", line 741, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/slither/slither/slither/__main__.py", line 73, in process_all
    compilations = compile_all(target, **vars(args))
  File "/root/.local/share/virtualenvs/slither-CAR93vT_/lib/python3.9/site-packages/crytic_compile-0.2.2-py3.9.egg/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/root/.local/share/virtualenvs/slither-CAR93vT_/lib/python3.9/site-packages/crytic_compile-0.2.2-py3.9.egg/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/root/.local/share/virtualenvs/slither-CAR93vT_/lib/python3.9/site-packages/crytic_compile-0.2.2-py3.9.egg/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/root/.local/share/virtualenvs/slither-CAR93vT_/lib/python3.9/site-packages/crytic_compile-0.2.2-py3.9.egg/crytic_compile/platform/etherscan.py", line 275, in compile
    with urllib.request.urlopen(req) as response:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

```

**Comment by mrx23dot** [comment]
Also is it possible to input byte code instead of *.sol source?

**Comment by 0xalpharush** [comment]
Slither requires source code. We will work on improving the error handling in [crytic/crytic-compile ](https://github.com/crytic/crytic-compile).

**Comment by mrx23dot** [comment]
Thank you!
