### ISSUE TITLE
[Bug]: KeyError: 13854

### ISSUE THREAD

**Issue by sradu** [crytic/slither#1066]
### What happened?

Running slither . returns this error:

```
Traceback (most recent call last):
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/slither.py", line 97, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 182, in parse_top_level_from_loaded_json
    contract.set_offset(top_level_data["src"], self._compilation_unit)
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 124, in set_offset
    self._source_mapping = self._convert_source_mapping(offset, compilation_unit)
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 101, in _convert_source_mapping
    (lines, starting_column, ending_column) = self._compute_line(
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 43, in _compute_line
    end_line, ending_column = compilation_unit.core.crytic_compile.get_line_from_offset(
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 291, in get_line_from_offset
    return lines_delimiters[offset]
KeyError: 13854
None
Error in .
Traceback (most recent call last):
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/slither.py", line 97, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 182, in parse_top_level_from_loaded_json
    contract.set_offset(top_level_data["src"], self._compilation_unit)
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 124, in set_offset
    self._source_mapping = self._convert_source_mapping(offset, compilation_unit)
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 101, in _convert_source_mapping
    (lines, starting_column, ending_column) = self._compute_line(
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 43, in _compute_line
    end_line, ending_column = compilation_unit.core.crytic_compile.get_line_from_offset(
  File "/Users/bb/opt/anaconda3/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 291, in get_line_from_offset
    return lines_delimiters[offset]
KeyError: 13854
```

crytic-compile . works great.

### Can you share code with us to reproduce this bug?

Not right now.

### Version

0.8.2

**Comment by elopez** [comment]
Could you please confirm which version of crytic-compile you have installed? You can check it by running `crytic-compile --version`

If it's not the latest (`0.2.2`) can you please upgrade it (`pip3 install --upgrade crytic-compile`) and let us know if that fixes the issue?

**Comment by sradu** [comment]
@elopez, thanks for responding.

It's the latest version
```
❯ crytic-compile --version
0.2.2
```

**Comment by montyly** [comment]
Hi @sradu.

Thank you for reporting this. Can you share the compilation framework that you are using? (truffle/brownie/hardhat, ..)

**Comment by sradu** [comment]
Hi @montyly! Using hardhat!

**Comment by jurgenwerk** [comment]
Getting the same error as @sradu - also with hardhat. `crytic-compile` works fine and it is updated.

**Comment by ggrieco-tob** [comment]
Can you please retry running `hardhat clean` and `rm -Rf crytic-export` before compiling?

**Comment by jurgenwerk** [comment]
@ggrieco-tob thanks, that worked for me!

**Comment by sradu** [comment]
Worked for me as well. Thank you so much!

**Comment by vinceferro** [comment]
I'm having the same issue, none of the steps unfortunately have helped :(

Setup: foundry + hardhat
Compilation: hardhat
Solc: 0.8.13
Slither: 0.8.3
crytic-compile: 0.2.3
