### ISSUE TITLE
[Bug]: OpenZeppelin Math.sol does not exist in imported contracts during crytic-compile

### ISSUE THREAD

**Issue by sjkelleyjr** [crytic/slither#1071]
### What happened?

crytic-compile is not able to resolve the OpenZeppelin Math.sol contract, even though it is able to resolve the SafeMath.sol contract from the same import.  I've also confirmed that the SafeMath.sol contract and Math.sol contract are in the same directory.

### Can you share code with us to reproduce this bug?

run `slither .` in the root of [this repo](https://github.com/fp-crypto/joint-strategy/)

### Version

0.8.2

### Relevant log output

```shell
sakelle@3c06301c27f7 joint-strategy (master) $ slither .
Brownie v1.17.2 - Python development framework for Ethereum

Compiling contracts...
  Solc version: 0.6.12
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
Generating build data...
 - OpenZeppelin/openzeppelin-contracts@3.1.0/Context
 - OpenZeppelin/openzeppelin-contracts@3.1.0/Ownable
 - OpenZeppelin/openzeppelin-contracts@3.1.0/ERC165
 - OpenZeppelin/openzeppelin-contracts@3.1.0/IERC165
 - OpenZeppelin/openzeppelin-contracts@3.1.0/Math
 - OpenZeppelin/openzeppelin-contracts@3.1.0/SafeMath
 - OpenZeppelin/openzeppelin-contracts@3.1.0/ERC20
 - OpenZeppelin/openzeppelin-contracts@3.1.0/IERC20
 - OpenZeppelin/openzeppelin-contracts@3.1.0/SafeERC20
 - OpenZeppelin/openzeppelin-contracts@3.1.0/ERC721
 - OpenZeppelin/openzeppelin-contracts@3.1.0/IERC721
 - OpenZeppelin/openzeppelin-contracts@3.1.0/IERC721Enumerable
 - OpenZeppelin/openzeppelin-contracts@3.1.0/IERC721Metadata
 - OpenZeppelin/openzeppelin-contracts@3.1.0/IERC721Receiver
 - OpenZeppelin/openzeppelin-contracts@3.1.0/Address
 - OpenZeppelin/openzeppelin-contracts@3.1.0/EnumerableMap
 - OpenZeppelin/openzeppelin-contracts@3.1.0/EnumerableSet
 - OpenZeppelin/openzeppelin-contracts@3.1.0/Strings
 - iearn-finance/yearn-vaults@0.4.3/BaseStrategy
 - iearn-finance/yearn-vaults@0.4.3/BaseStrategyInitializable
 - iearn-finance/yearn-vaults@0.4.3/HealthCheck
 - iearn-finance/yearn-vaults@0.4.3/StrategyAPI
 - iearn-finance/yearn-vaults@0.4.3/VaultAPI
 - AggregatorMock
 - HedgilJoint
 - IHedgilPool
 - HegicJoint
 - Joint
 - ProviderStrategy
 - HegicJointAPI
 - IPriceProvider
 - LPHedgingLib
 - JointAPI
 - ProviderStrategy
 - ISushiMasterchef
 - SushiJoint
 - SafeMathUniswap
 - UniswapV2Library
 - IERC20Extended
 - IMasterchef
 - IHegicPool
 - IHegicStaking
 - IPriceCalculator
 - IUniswapV2Factory
 - IUniswapV2Pair
 - IUniswapV2Router01
 - IUniswapV2Router02

Project has been compiled. Build artifacts saved at /Users/sakelle/auditing/joint-strategy/build/contracts

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/opt/homebrew/lib/python3.9/site-packages/slither/slither.py", line 97, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 224, in parse_top_level_from_loaded_json
    get_imported_scope = self.compilation_unit.get_scope(import_directive.filename)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/core/compilation_unit.py", line 231, in get_scope
    filename = self._crytic_compile_compilation_unit.crytic_compile.filename_lookup(
  File "/opt/homebrew/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 199, in filename_lookup
    raise ValueError(
ValueError: /Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/math/Math.sol does not exist in ['/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/token/ERC20/IERC20.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/token/ERC20/IERC20.sol', '/Users/sakelle/auditing/joint-strategy/contracts/libraries/UniswapV2Library.sol', '/Users/sakelle/auditing/joint-strategy/contracts/libraries/UniswapV2Library.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/token/ERC721/IERC721.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/token/ERC721/IERC721.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/token/ERC20/SafeERC20.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/token/ERC20/SafeERC20.sol', '/Users/sakelle/auditing/joint-strategy/contracts/SushiJoint.sol', '/Users/sakelle/auditing/joint-strategy/contracts/SushiJoint.sol', '/Users/sakelle/auditing/joint-strategy/contracts/ProviderStrategy.sol', '/Users/sakelle/auditing/joint-strategy/contracts/ProviderStrategy.sol', '/Users/sakelle/auditing/joint-strategy/contracts/LPHedgingLib.sol', '/Users/sakelle/auditing/joint-strategy/contracts/LPHedgingLib.sol', '/Users/sakelle/auditing/joint-strategy/contracts/AggregatorMock.sol', '/Users/sakelle/auditing/joint-strategy/contracts/AggregatorMock.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/utils/Address.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/utils/Address.sol', '/Users/sakelle/auditing/joint-strategy/contracts/HedgilJoint.sol', '/Users/sakelle/auditing/joint-strategy/contracts/HedgilJoint.sol', '/Users/sakelle/auditing/joint-strategy/contracts/HegicJoint.sol', '/Users/sakelle/auditing/joint-strategy/contracts/HegicJoint.sol', '/Users/sakelle/.brownie/packages/iearn-finance/yearn-vaults@0.4.3/contracts/BaseStrategy.sol', '/Users/sakelle/.brownie/packages/iearn-finance/yearn-vaults@0.4.3/contracts/BaseStrategy.sol', '/Users/sakelle/auditing/joint-strategy/contracts/Joint.sol', '/Users/sakelle/auditing/joint-strategy/contracts/Joint.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/introspection/IERC165.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/introspection/IERC165.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/math/SafeMath.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/math/SafeMath.sol']
None
Error in .
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/opt/homebrew/lib/python3.9/site-packages/slither/slither.py", line 97, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 224, in parse_top_level_from_loaded_json
    get_imported_scope = self.compilation_unit.get_scope(import_directive.filename)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/core/compilation_unit.py", line 231, in get_scope
    filename = self._crytic_compile_compilation_unit.crytic_compile.filename_lookup(
  File "/opt/homebrew/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 199, in filename_lookup
    raise ValueError(
ValueError: /Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/math/Math.sol does not exist in ['/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/token/ERC20/IERC20.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/token/ERC20/IERC20.sol', '/Users/sakelle/auditing/joint-strategy/contracts/libraries/UniswapV2Library.sol', '/Users/sakelle/auditing/joint-strategy/contracts/libraries/UniswapV2Library.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/token/ERC721/IERC721.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/token/ERC721/IERC721.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/token/ERC20/SafeERC20.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/token/ERC20/SafeERC20.sol', '/Users/sakelle/auditing/joint-strategy/contracts/SushiJoint.sol', '/Users/sakelle/auditing/joint-strategy/contracts/SushiJoint.sol', '/Users/sakelle/auditing/joint-strategy/contracts/ProviderStrategy.sol', '/Users/sakelle/auditing/joint-strategy/contracts/ProviderStrategy.sol', '/Users/sakelle/auditing/joint-strategy/contracts/LPHedgingLib.sol', '/Users/sakelle/auditing/joint-strategy/contracts/LPHedgingLib.sol', '/Users/sakelle/auditing/joint-strategy/contracts/AggregatorMock.sol', '/Users/sakelle/auditing/joint-strategy/contracts/AggregatorMock.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/utils/Address.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/utils/Address.sol', '/Users/sakelle/auditing/joint-strategy/contracts/HedgilJoint.sol', '/Users/sakelle/auditing/joint-strategy/contracts/HedgilJoint.sol', '/Users/sakelle/auditing/joint-strategy/contracts/HegicJoint.sol', '/Users/sakelle/auditing/joint-strategy/contracts/HegicJoint.sol', '/Users/sakelle/.brownie/packages/iearn-finance/yearn-vaults@0.4.3/contracts/BaseStrategy.sol', '/Users/sakelle/.brownie/packages/iearn-finance/yearn-vaults@0.4.3/contracts/BaseStrategy.sol', '/Users/sakelle/auditing/joint-strategy/contracts/Joint.sol', '/Users/sakelle/auditing/joint-strategy/contracts/Joint.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/introspection/IERC165.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/introspection/IERC165.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/math/SafeMath.sol', '/Users/sakelle/.brownie/packages/OpenZeppelin/openzeppelin-contracts@3.1.0/contracts/math/SafeMath.sol']
```
```

**Comment by sjkelleyjr** [comment]
looks like it might be related to [this crytic-compile issue](https://github.com/crytic/crytic-compile/issues/241)

**Comment by montyly** [comment]
Hi @sjkelleyjr,

Thank you for reporting this. I suspect it is because of the remapping rules: https://github.com/fp-crypto/joint-strategy/blob/3c12bbff1f3af66599571e9f79d642ce62020d85/brownie-config.yml#L19-L20

We will investigate how to add brownie remapping support

**Comment by 0xalpharush** [comment]
Tracking in crytic-compile
