### ISSUE TITLE
[Bug]:`string.concat` fails `assert isinstance(destination, (Variable, SolidityVariable))` and panics 

### ISSUE THREAD

**Issue by joshieDo** [crytic/slither#1075]
### What happened?

`A bug happened!`

Using `string.concat` seems to trigger an `AssertionError` and panic.

### Can you share code with us to reproduce this bug?
```
pragma solidity 0.8.12;

contract ContractMe  {

    function foo() public pure returns (string memory) {
        return string.concat("bar");
    }

}
```

### Version

0.8.2

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/user/.local/lib/python3.9/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/user/.local/lib/python3.9/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/user/.local/lib/python3.9/site-packages/slither/slither.py", line 125, in __init__
    parser.analyze_contracts()
  File "/home/user/.local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 442, in analyze_contracts
    self._convert_to_slithir()
  File "/home/user/.local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 626, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/home/user/.local/lib/python3.9/site-packages/slither/core/declarations/function.py", line 1708, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/home/user/.local/lib/python3.9/site-packages/slither/core/cfg/node.py", line 720, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/home/user/.local/lib/python3.9/site-packages/slither/slithir/convert.py", line 118, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/home/user/.local/lib/python3.9/site-packages/slither/slithir/convert.py", line 1725, in apply_ir_heuristics
    irs = propagate_type_and_convert_call(irs, node)
  File "/home/user/.local/lib/python3.9/site-packages/slither/slithir/convert.py", line 396, in propagate_type_and_convert_call
    new_ins = extract_tmp_call(ins, contract)
  File "/home/user/.local/lib/python3.9/site-packages/slither/slithir/convert.py", line 947, in extract_tmp_call
    msgcall = HighLevelCall(
  File "/home/user/.local/lib/python3.9/site-packages/slither/slithir/operations/high_level_call.py", line 22, in __init__
    self._check_destination(destination)
  File "/home/user/.local/lib/python3.9/site-packages/slither/slithir/operations/high_level_call.py", line 38, in _check_destination
    assert isinstance(destination, (Variable, SolidityVariable))
AssertionError
None
Error in C.sol
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/user/.local/lib/python3.9/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/user/.local/lib/python3.9/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/user/.local/lib/python3.9/site-packages/slither/slither.py", line 125, in __init__
    parser.analyze_contracts()
  File "/home/user/.local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 442, in analyze_contracts
    self._convert_to_slithir()
  File "/home/user/.local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 626, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/home/user/.local/lib/python3.9/site-packages/slither/core/declarations/function.py", line 1708, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/home/user/.local/lib/python3.9/site-packages/slither/core/cfg/node.py", line 720, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/home/user/.local/lib/python3.9/site-packages/slither/slithir/convert.py", line 118, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/home/user/.local/lib/python3.9/site-packages/slither/slithir/convert.py", line 1725, in apply_ir_heuristics
    irs = propagate_type_and_convert_call(irs, node)
  File "/home/user/.local/lib/python3.9/site-packages/slither/slithir/convert.py", line 396, in propagate_type_and_convert_call
    new_ins = extract_tmp_call(ins, contract)
  File "/home/user/.local/lib/python3.9/site-packages/slither/slithir/convert.py", line 947, in extract_tmp_call
    msgcall = HighLevelCall(
  File "/home/user/.local/lib/python3.9/site-packages/slither/slithir/operations/high_level_call.py", line 22, in __init__
    self._check_destination(destination)
  File "/home/user/.local/lib/python3.9/site-packages/slither/slithir/operations/high_level_call.py", line 38, in _check_destination
    assert isinstance(destination, (Variable, SolidityVariable))
AssertionError
```

**Comment by montyly** [comment]
Hi @joshieDo,

Thank you for reporting this. We will add the support as soon as possible

**Comment by montyly** [comment]
Hi @joshieDo, we added the support with #1086, and it is available in master. It will be included in the next release of Slither
