### ISSUE TITLE
[Bug]: Top level functions cause exception in reentrancy detector 

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/slither#1087]
### What happened?

`AttributeError: 'FunctionTopLevel' object has no attribute 'contract'.` This causes an issue in the reentrancy detector because `can_reenter` uses this info.

Related to https://github.com/crytic/slither/issues/1001

### Can you share code with us to reproduce this bug?

Fei protocol core. To reproduce and bypass https://github.com/crytic/slither/issues/1008, replace `*` with `uint256` [here](https://github.com/fei-protocol/fei-protocol-core/blob/8cba2ae3d3f5bc1cb62860a9f51099bb9c40ecad/contracts/pcv/balancer/BalancerPCVDepositWeightedPool.sol#L17-L19)

### Version

0.8.2

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/alpharush/Desktop/slither/slither/__main__.py", line 741, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/alpharush/Desktop/slither/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Users/alpharush/Desktop/slither/slither/__main__.py", line 69, in process_single
    return _process(slither, detector_classes, printer_classes)
  File "/Users/alpharush/Desktop/slither/slither/__main__.py", line 110, in _process
    detector_results = slither.run_detectors()
  File "/Users/alpharush/Desktop/slither/slither/slither.py", line 203, in run_detectors
    results = [d.detect() for d in self._detectors]
  File "/Users/alpharush/Desktop/slither/slither/slither.py", line 203, in <listcomp>
    results = [d.detect() for d in self._detectors]
  File "/Users/alpharush/Desktop/slither/slither/detectors/abstract_detector.py", line 152, in detect
    for r in [output.data for output in self._detect()]:
  File "/Users/alpharush/Desktop/slither/slither/detectors/reentrancy/reentrancy_eth.py", line 93, in _detect
    super()._detect()
  File "/Users/alpharush/Desktop/slither/slither/detectors/reentrancy/reentrancy.py", line 302, in _detect
    self.detect_reentrancy(c)
  File "/Users/alpharush/Desktop/slither/slither/detectors/reentrancy/reentrancy.py", line 289, in detect_reentrancy
    self._explore(function.entry_point, [])
  File "/Users/alpharush/Desktop/slither/slither/detectors/reentrancy/reentrancy.py", line 282, in _explore
    self._explore(son, visited)
  File "/Users/alpharush/Desktop/slither/slither/detectors/reentrancy/reentrancy.py", line 267, in _explore
    contains_call = fathers_context.analyze_node(node, self)
  File "/Users/alpharush/Desktop/slither/slither/detectors/reentrancy/reentrancy.py", line 159, in analyze_node
    if detector.can_callback(ir):
  File "/Users/alpharush/Desktop/slither/slither/detectors/reentrancy/reentrancy.py", line 228, in can_callback
    return isinstance(ir, Call) and ir.can_reenter()
  File "/Users/alpharush/Desktop/slither/slither/slithir/operations/high_level_call.py", line 109, in can_reenter
    if self.compilation_unit.solc_version and self.compilation_unit.solc_version >= "0.5.0":
  File "/Users/alpharush/Desktop/slither/slither/core/children/child_node.py", line 31, in compilation_unit
    return self.contract.compilation_unit
  File "/Users/alpharush/Desktop/slither/slither/core/children/child_node.py", line 27, in contract
    return self.node.function.contract
AttributeError: 'FunctionTopLevel' object has no attribute 'contract'
```

**Comment by tbrent** [comment]
I was facing this issue on `master` @ commit `81daa56f66488d4ff1961ff4f1033edf15566d36`

I was able to workaround it by doing either of the following:
1. Add all the re-entrancy detectors to the exclude set in my config
2. Switch to commit `697616edae02778cc041366b16ed24f1a214de42`. It may be there are more recent commits that will also do the trick, but this is the one I found.
