### ISSUE TITLE
Slither hangs due to a bug in openzeppelin/upgrades

### ISSUE THREAD

**Issue by FlacoJones** [crytic/slither#1095]
### What happened?

When running slither on [this hardhat repository](https://github.com/openqdev/OpenQ-Contracts), it halted and failed to output anything.

Here is the asciinema of me reproducing the bug.

I'm on MacOS Moneterey

### Can you share code with us to reproduce this bug?

[this hardhat repository](https://github.com/openqdev/OpenQ-Contracts)

The asciinema recording of me reproducing the bug: https://asciinema.org/a/475452

### Version

0.8.2

### Relevant log output

```shell
'npx hardhat compile --force' running
Compiled 41 Solidity files successfully

Solidity 0.8.12 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/reference/solidity-support

[Then nothing, but my processor begins to go wild and laptop heats up...]
```

**Comment by 0xalpharush** [comment]
Can you run `npx hardhat compile && slither . --ignore-compile`? I want to verify that it's not hardhat hanging and see if there's a different error that way.

**Comment by FlacoJones** [comment]
I did so and got the following:

```
(base) AndrewscBookPro:OpenQ-Contracts alo$ npx hardhat compile && slither . --ignore-compile
Solidity 0.8.12 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/reference/solidity-support

Nothing to compile

[and then it hang again and my CPU started to crank up]
```

**Comment by FlacoJones** [comment]
And then to be thorough I deleted artifacts and ran it again, same thing:

```
(base) AndrewscBookPro:OpenQ-Contracts alo$ npx hardhat compile && slither . --ignore-compile
Solidity 0.8.12 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/reference/solidity-support

Compiled 41 Solidity files successfully

[and then it hangs again and my CPU started to crank up]
```

**Comment by FlacoJones** [comment]
It works on other hardhat repositories, but not the one linked.

**Comment by FlacoJones** [comment]
Is there a verbose option I could run to get more info?

**Comment by 0xalpharush** [comment]
I think there's a bug in this function that's causing an infinite loop. 
https://github.com/crytic/slither/blob/e3392dd6942c31f274c60eb04a586df463586d18/slither/solc_parsing/slither_compilation_unit_solc.py#L413

**Comment by FlacoJones** [comment]
Maybe I have a cycle in my dependency graph? So it's circling through a bunch of self-pointing contracts?

But hardhat checks for cyclical deps so likely not

**Comment by 0xalpharush** [comment]
Can you try putting the following in your hardhat config? This worked for me... I think one the dependencies imported in your current config might be causing issues.
```
module.exports = (function () {

	const config = {
		solidity: '0.8.12',
	};

	return config;
})();
```

**Comment by FlacoJones** [comment]
This is resolved in this release: https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fupgrades-core%401.14.1

Thanks @0xalpharush !

**Comment by 0xalpharush** [comment]
If you are affected by this issue, please install the patched version:
```
npm i @openzeppelin/upgrades-core@1.14.1
```

**Comment by eh-93** [comment]
I'm having the same issue with: @openzeppelin/upgrades-core@1.14.1 and hardhat
package.json dependencies:

```
  "dependencies": {
    "@openzeppelin/contracts": "^4.4.2",
    "@openzeppelin/contracts-upgradeable": "^4.5.2",
    "@openzeppelin/upgrades": "^2.8.0",
    "@openzeppelin/upgrades-core": "^1.14.1"
  },
```

```
 npx hardhat compile && slither . --ignore-compile

Nothing to compile
No need to generate any newer typings.
Traceback (most recent call last):
  File "/Users/.pyenv/versions/3.8.7/lib/python3.8/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/.pyenv/versions/3.8.7/lib/python3.8/site-packages/slither/__main__.py", line 73, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Users/.pyenv/versions/3.8.7/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/Users/.pyenv/versions/3.8.7/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/Users/.pyenv/versions/3.8.7/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/Users/.pyenv/versions/3.8.7/lib/python3.8/site-packages/crytic_compile/platform/hardhat.py", line 124, in compile
    contract_filename = convert_filename(
  File "/Users/.pyenv/versions/3.8.7/lib/python3.8/site-packages/crytic_compile/utils/naming.py", line 117, in convert_filename
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: @openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable.sol
None
Error in .
Traceback (most recent call last):
  File "/Users/.pyenv/versions/3.8.7/lib/python3.8/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/.pyenv/versions/3.8.7/lib/python3.8/site-packages/slither/__main__.py", line 73, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Users/.pyenv/versions/3.8.7/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/Users/.pyenv/versions/3.8.7/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/Users/.pyenv/versions/3.8.7/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/Users/.pyenv/versions/3.8.7/lib/python3.8/site-packages/crytic_compile/platform/hardhat.py", line 124, in compile
    contract_filename = convert_filename(
  File "/Users/.pyenv/versions/3.8.7/lib/python3.8/site-packages/crytic_compile/utils/naming.py", line 117, in convert_filename
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: @openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable.sol
```

hardhat version: 2.9.3
solidity compiler: 0.8.9

**Comment by 0xalpharush** [comment]
This looks like a different issue related to naming resolution. Can you try `npx hardhat clean && npx hardhat compile && slither . --ignore-compile`? Make sure that your node modules are in the present working directory. If you run into issues, please open a new issue with additional information about your hardhat config and directory structure.

**Comment by montyly** [comment]
Also can you run `ls node_modules/@openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable.sol` ?
