### ISSUE TITLE
[Bug]: self._underlying_contract_to_parser[father].is_analyzed KeyError: None

### ISSUE THREAD

**Issue by xKamuna** [crytic/slither#1106]
### What happened?

Hi, I'm having an issue running slither (hardhat 2.9.1, solc 0.6.12, slither 0.8.2, crytic-compile 0.2.2, no brownie).  I've tried WSL Ubuntu 20.04.3 LTS and Windows.  This is the error that I get on both (on Windows I have to use the fix-windows-paths branch and --hardhat-ignore-compile, and obviously the paths are different but the error is the same)

### Can you share code with us to reproduce this bug?

Entire private project.  Would share if I could.

### Version

0.8.2

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/summer/.local/lib/python3.8/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/summer/.local/lib/python3.8/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/summer/.local/lib/python3.8/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/summer/.local/lib/python3.8/site-packages/slither/slither.py", line 120, in __init__
    parser.parse_contracts()
  File "/home/summer/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 412, in parse_contracts
    self._analyze_all_enums(contracts_to_be_analyzed)
  File "/home/summer/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 453, in _analyze_all_enums
    all_father_analyzed = all(
  File "/home/summer/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 454, in <genexpr>
    self._underlying_contract_to_parser[father].is_analyzed
KeyError: None
None
Error in .
Traceback (most recent call last):
  File "/home/summer/.local/lib/python3.8/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/summer/.local/lib/python3.8/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/summer/.local/lib/python3.8/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/summer/.local/lib/python3.8/site-packages/slither/slither.py", line 120, in __init__
    parser.parse_contracts()
  File "/home/summer/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 412, in parse_contracts
    self._analyze_all_enums(contracts_to_be_analyzed)
  File "/home/summer/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 453, in _analyze_all_enums
    all_father_analyzed = all(
  File "/home/summer/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 454, in <genexpr>
    self._underlying_contract_to_parser[father].is_analyzed
KeyError: None
```

**Comment by nkuba** [comment]
We experienced the same problem in [our CI](https://github.com/keep-network/tbtc-v2/runs/5568980399?check_suite_focus=true).

**Comment by montyly** [comment]
Hi, thanks @xKamuna and @nkuba for reporting this. I believe we fixed it with #1133 (I tested it on tbtc-v2). The fix will be available in the upcoming release (by the end of the month)

**Comment by nkuba** [comment]
Hey, @montyly we are really looking forward to the fix. When can we expect a new release?

**Comment by montyly** [comment]
Hi @nkuba, we wanted to have it already ready, but we got delayed. We are aiming for early next week
