### ISSUE TITLE
[Bug-Candidate]: Slither complains of "top level `ErrorDefinition`"

### ISSUE THREAD

**Issue by jmcph4** [crytic/slither#1147]
### Describe the issue:

```
$ uname -a
Linux foobar 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
$ python3.7 --version
Python 3.7.3
$ slither --version
0.8.1
```

Slither fails with a somewhat opaque error message on valid (i.e., compiling) Solidity in a Hardhat project.

### Code example to reproduce the issue:

Execute Slither from the root of [tracer-protocol/perpetual-pools-contracts](https://github.com/tracer-protocol/perpetual-pools-contracts).

(See log output).

### Version:

```
$ slither --version
0.8.1
```

### Relevant log output:

```
$ git rev-parse HEAD
b51d30ae3052acb2d1706c0626be8ab8dbacd134
$ slither .
'npx hardhat compile --force' running
Compiling 51 files with 0.8.7
Generating typings for: 51 artifacts in dir: types for target: ethers-v5
Successfully generated 83 typings!
Compilation finished successfully

Solidity 0.8.7 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/reference/solidity-support"

Warning: Function state mutability can be restricted to pure
  --> contracts/implementation/ChainlinkOracleWrapper.sol:33:5:
   |
33 |     function decimals() external view override returns (uint8) {
   |     ^ (Relevant source part starts here and spans across multiple lines).



Traceback (most recent call last):
  File "/home/johndoe/.local/lib/python3.7/site-packages/slither/__main__.py", line 741, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/johndoe/.local/lib/python3.7/site-packages/slither/__main__.py", line 83, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/johndoe/.local/lib/python3.7/site-packages/slither/__main__.py", line 66, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/johndoe/.local/lib/python3.7/site-packages/slither/slither.py", line 81, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/home/johndoe/.local/lib/python3.7/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 221, in parse_top_level_from_loaded_json
    raise SlitherException(f"Top level {top_level_data[self.get_key()]} not supported")
slither.exceptions.SlitherException: Top level ErrorDefinition not supported
Error:
Top level ErrorDefinition not supported
Please report an issue to https://github.com/crytic/slither/issues
```

**Comment by montyly** [comment]
Hi @jmcph4, thank you for reporting this.

We improved the level for top-level objects with [Slither 0.8.3](https://github.com/crytic/slither/releases/tag/0.8.3). Running `pip install --upgrade slither-analyzer` will fix this issue
