### ISSUE TITLE
[Bug-Candidate]: Slither bugging with solc

### ISSUE THREAD

**Issue by Tayarthouail** [crytic/slither#1148]
### Describe the issue:

I followed the instruction to install slither.
=> git clone https://github.com/crytic/slither.git && cd slither
=> python3 setup.py install
=> slither .

it gave me the error bellow
How should I solve that please

### Code example to reproduce the issue:

Traceback (most recent call last):
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 73, in process_all       
    compilations = compile_all(target, **vars(args))
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 658, in compile_all
    compilations.append(CryticCompile(filename, **kwargs))
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\solc.py", line 153, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\solc.py", line 275, in _get_targets_json
    return _run_solc(
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\solc.py", line 463, in _run_solc
    raise InvalidCompilation(
crytic_compile.platform.exceptions.InvalidCompilation: . does not exist (are you in the correct directory?)
None
Error in .
Traceback (most recent call last):
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 743, in main_impl        
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 73, in process_all       
    compilations = compile_all(target, **vars(args))
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 658, in compile_all
    compilations.append(CryticCompile(filename, **kwargs))
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\solc.py", line 153, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\solc.py", line 275, in _get_targets_json
    return _run_solc(
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\solc.py", line 463, in _run_solc
    raise InvalidCompilation(
crytic_compile.platform.exceptions.InvalidCompilation: . does not exist (are you in the correct directory?)

### Version:

0.8.2

**Comment by 0xalpharush** [comment]
You should run slither in the root of your project directory `cd /my/project/path && slither .` Slither supports various Solidity compilation frameworks: truffle, brownie, hardhat, dapptools.

**Comment by Tayarthouail** [comment]
I run slither in the root then I got this error.

Solidity version for this :  pip3 install solc-select (0.2.1)
Smart contract and hardhat config: solidity version 0.8.10
Slither version 0.8.2

It the error have something to do with solc compiler?
Thank you

None
Error in contracts/Multi-sig-Wallet.sol
Traceback (most recent call last):
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 73, in process_all
    compilations = compile_all(target, **vars(args))
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\solc.py", line 153, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\solc.py", line 275, in _get_targets_json
    return _run_solc(
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\solc.py", line 471, in _run_solc
    compiler="solc", version=get_version(solc, env), optimized=is_optimized(solc_arguments)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\solc.py", line 376, in get_version
    raise InvalidCompilation(f"Solidity version not found: {stdout}")
crytic_compile.platform.exceptions.InvalidCompilation: Solidity version not found: No solc version set. Run `solc-select use VERSION` or set SOLC_VERSION environment variable.

**Comment by 0xalpharush** [comment]
In general, you want to have a compilation framework to link dependencies. If `Multi-sig-Wallet.sol` does not have any dependencies, you can run `pip install solc-select`. Then you, can run `solc-select install $VERSION && solc-select use $VERSION` (replace `$VERSION` with whatever is used by `Multi-sig-Wallet.sol` e.g. 0.8.0).

**Comment by Tayarthouail** [comment]
When I run solc-select install 0.8.10 I got this "Unsupported platform". Btw I'm using windows does slither support it.

**Comment by elopez** [comment]
For solc-select on Windows you need to use the beta version: `pip install solc-select==1.0.0b1`

Note that there have been a few issues with Slither on Windows, if you still hit errors after that you can try installing crytic-compile and slither from the following branches: crytic/crytic-compile#248 & crytic/slither#1137

**Comment by Tayarthouail** [comment]
I run the command but I got this error, my smart contract has 0.8.10 version as well as hardhat

Error in contracts/Multi-sig-Wallet.sol
Traceback (most recent call last):
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 73, in process_all
    compilations = compile_all(target, **vars(args))
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\solc.py", line 153, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\solc.py", line 275, in _get_targets_json
    return _run_solc(
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\solc.py", line 471, in _run_solc
    compiler="solc", version=get_version(solc, env), optimized=is_optimized(solc_arguments)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\solc.py", line 376, in get_version
    raise InvalidCompilation(f"Solidity version not found: {stdout}")
crytic_compile.platform.exceptions.InvalidCompilation: Solidity version not found:

**Comment by elopez** [comment]
did you install the required solc version after installing the beta solc-select? (e.g. `solc-select install 0.8.10` and then `solc-select use 0.8.10`) Also, are you in the hardhat project folder when running `slither .`? you should see `hardhat.config.js` if you run `dir`. If you don't, please `cd "C:\Users\21267\yourproject"` before running slither (replace the path with the correct folder for your project)

**Comment by Tayarthouail** [comment]
when run dir I can see hardhat. config.js. I tried to run slither . after running solc-select install 0.8.10 and then solc-select use 0.8.10 and I git this error

> slither .
'npx hardhat compile --force' running
Traceback (most recent call last):
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 73, in process_all
    compilations = compile_all(target, **vars(args))
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\hardhat.py", line 72, in compile
    with subprocess.Popen(
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__       
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
None
Error in .
Traceback (most recent call last):
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 73, in process_all
    compilations = compile_all(target, **vars(args))
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\platform\hardhat.py", line 72, in compile
    with subprocess.Popen(
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__       
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\21267\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

This is my hardhat config :

module.exports = {
  defaultNetwork: "hardhat",

  paths: {
    artifacts: './src/artifacts'
  },

  networks: {

  hardhat: {
    chainId: 1337
  },
  // connect hardhat with infura endpoint
  rinkeby: {
    url: `https://rinkeby.infura.io/v3/${projectId}`,
    accounts:[privateKey]
  },

  mainnet: {
    url: `https://mainnet.infura.io/v3/${projectId}`,
    accounts:[privateKey]
  }
},

  solidity: {
    version : "0.8.4",
    settings: {
      optimizer: {
        enabled: true,
        runs:200
      }
    }
  }
};

**Comment by elopez** [comment]
Those Windows problems are the ones I was referring to, they have been fixed recently in the pull requests I linked earlier. You can install them with the instructions below if you want to try them out. Once the PRs are merged and a new version of crytic-compile and slither is released, it should work better out of the box in Windows.

```sh
pip uninstall crytic-compile
pip uninstall slither-analyzer
pip install -U https://github.com/crytic/crytic-compile/archive/refs/heads/dev-windows-long-paths.zip
pip install -U https://github.com/elopez/slither/archive/refs/heads/windows-ci.zip
```

**Comment by elopez** [comment]
Slither 0.8.3 and crytic-compile 0.2.3 have now been released and should resolve the problem. I'll close this issue, but feel free to create a new one if you still experience problems after upgrading both slither and crytic-compile to the latest releases.
