### ISSUE TITLE
[Bug-Candidate]: Read-only file system: '/interfaces'

### ISSUE THREAD

**Issue by revmischa** [crytic/slither#1154]
### Describe the issue:

```
slither 0xcfc1E0968CA08aEe88CbF664D4A1f8B881d90f37
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.9/site-packages/slither/__main__.py", line 73, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/platform/etherscan.py", line 306, in compile
    filenames, working_dir = _handle_multiple_files(
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/platform/etherscan.py", line 158, in _handle_multiple_files
    os.makedirs(path_filename.parent)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/interfaces'
```

### Code example to reproduce the issue:

slither 0xcfc1E0968CA08aEe88CbF664D4A1f8B881d90f37

### Version:

0.8.2

**Comment by 0xalpharush** [comment]
Your user doesn't have write access to the folder you're in. You can try change permissions using`chmod 755 .`
