### ISSUE TITLE
[Bug-Candidate]: Brownie Config File not detected

### ISSUE THREAD

**Issue by mitche50** [crytic/slither#1158]
### Describe the issue:

A valid configuration titling brownie config file `brownie-config.yml` rather than `brownie-config.yaml` results in not utilizing brownie

### Code example to reproduce the issue:

https://github.com/Badger-Finance/badger-vaults-1.5/runs/5853491558?check_suite_focus=true

### Version:

crytic/slither-action@v0.1.0

### Relevant log output:

 INFO:CryticCompile:'npx hardhat compile --force' running
INFO:CryticCompile:

ERROR:CryticCompile:npm WARN exec The following package was not found and will be installed: hardhat
Error HH12: Trying to use a non-local installation of Hardhat, which is not supported.
Please install Hardhat locally using npm or Yarn, and try again.
For more info go to https://hardhat.org/HH12 or run Hardhat with --show-stack-traces

Traceback (most recent call last):
  File "/opt/slither/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/opt/slither/lib/python3.9/site-packages/crytic_compile/__main__.py", line 192, in main
    compilations = compile_all(**vars(args))
  File "/opt/slither/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/slither/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/slither/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/slither/lib/python3.9/site-packages/crytic_compile/platform/hardhat.py", line 87, in compile
    os.listdir(build_directory), key=lambda x: os.path.getmtime(Path(build_directory, x))
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/build-info'

**Comment by montyly** [comment]
Hi @mitche50.

We improved the brownie support with [Slither 0.8.3](https://github.com/crytic/slither/releases/tag/0.8.3). Running `pip install --upgrade slither-analyzer` will fix this issue
