### ISSUE TITLE
[Bug-Candidate]:  enum inside contract is resulting in "type not found"

### ISSUE THREAD

**Issue by holic** [crytic/slither#1166]
### Describe the issue:

`enum` inside `contract` is resulting in `Error: Type not found enum MyEnum`

### Code example to reproduce the issue:

```solidity
contract BootDisk {
    enum MintPhase {
        OWNER,
        ALPHA,
        BETA,
        PUBLIC
    }
}
```

If I move the `enum` out of `contract`, slither runs fine:

```solidity
enum MintPhase {
    OWNER,
    ALPHA,
    BETA,
    PUBLIC
}
contract BootDisk {
    ...
}
```

### Version:

0.8.2

### Relevant log output:

```
slither src/BootDisk.sol --solc-remaps "@openzeppelin=lib/openzeppelin-contracts erc721a=lib/erc721a"
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/opt/homebrew/lib/python3.9/site-packages/slither/slither.py", line 120, in __init__
    parser.parse_contracts()
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 431, in parse_contracts
    self._analyze_second_part(contracts_to_be_analyzed, libraries)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 514, in _analyze_second_part
    self._analyze_struct_events(contract)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 569, in _analyze_struct_events
    contract.analyze_custom_errors()
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/declarations/contract.py", line 629, in analyze_custom_errors
    custom_error.analyze_params()
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/declarations/custom_error.py", line 57, in analyze_params
    self._parse_params(params)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/declarations/custom_error.py", line 81, in _parse_params
    local_var = self._add_param(param)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/declarations/custom_error.py", line 95, in _add_param
    local_var_parser.analyze(self)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/variables/variable_declaration.py", line 190, in analyze
    self._variable.type = parse_type(self._elem_to_parse, caller_context)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/solidity_types/type_parsing.py", line 318, in parse_type
    return _find_from_type_name(
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/solidity_types/type_parsing.py", line 193, in _find_from_type_name
    raise ParsingError("Type not found " + str(name))
slither.solc_parsing.exceptions.ParsingError: Type not found enum BootDisk.MintPhase
Error:
Type not found enum BootDisk.MintPhase
Please report an issue to https://github.com/crytic/slither/issues
```

**Comment by montyly** [comment]
Hi @holic, thank you for reporting this. I cannot reproduce the bug (tested with 0.8.2 and 0.8.3), can you share the entire codebase where this happen?

**Comment by Mc01** [comment]
Have exactly the same issue with Slither version `0.8.3` and Solidity `0.8.13`

**Comment by stevennevins** [comment]
experiencing the same issue with Slither version 0.8.3 and Solidity 0.8.13

**Comment by 0xdomrom** [comment]
I get a similar issue, for me it relates to the enum being present inside of CustomError (enum not being found)

Feels related to #1173

**Comment by boolafish** [comment]
plus one

**Comment by 0xalpharush** [comment]
If someone can share a failure example related to the enums, that would be appreciated. The custom error issue will be addressed separately.

**Comment by Jeff-CCH** [comment]
Same issue here with an example (solidity 0.8.10 + slither 0.8.3)

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

library Errors {
    error RevertCode(Code errorCode);

    enum Code {
        ERROR_CODE_1 // 0: "Error"
    }
}
```
If I remove the error RevertCode(...), slither works fine. Please have a look. Thanks.
