### ISSUE TITLE
[Bug-Candidate]: Error for father in contract.underlying_contract.inheritance

### ISSUE THREAD

**Issue by frgv** [crytic/slither#1168]
### Describe the issue:

Trying to run slither from a project's root folder (with `slither .` ), I'm greeted with this error. Apparently, the project compiles successfully, but, after showing a few warnings such as:

`@openzeppelin/contracts/access/Ownable.sol:26:5: Warning: Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.
    constructor () internal {
    ^ (Relevant source part starts here and spans across multiple lines).
`

It just crashes with the error message found below.

Any guidance will be more than welcome.

### Code example to reproduce the issue:

Unfortunately, it's a private project. I'd share if I could.

### Version:

Using 0.8.2 from last eth-security-toolbox docker image. Also tried with 0.7.1, same error. 

A colleague tried with a straight linux installation (no docker) and, the same result.

Hardhat is used in the project, but using --hardhat-ignore-compile just returns the same exact error.

### Relevant log output:

ethsec@2034cdd3963e:/tmp/[REDACTED]$ slither . --hardhat-ignore-compile
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 120, in __init__
    parser.parse_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 412, in parse_contracts
    self._analyze_all_enums(contracts_to_be_analyzed)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 455, in _analyze_all_enums
    for father in contract.underlying_contract.inheritance
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 455, in <genexpr>
    for father in contract.underlying_contract.inheritance
KeyError: None
None
Error in .
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 120, in __init__
    parser.parse_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 412, in parse_contracts
    self._analyze_all_enums(contracts_to_be_analyzed)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 455, in _analyze_all_enums
    for father in contract.underlying_contract.inheritance
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 455, in <genexpr>
    for father in contract.underlying_contract.inheritance
KeyError: None

**Comment by montyly** [comment]
Hi @frgv. 
Can you run with `--disallow-partial` and share the output?
