### ISSUE TITLE
[Bug-Candidate]: Slither crashes with `ValueError: XYZ does not exist in dict_keys` when imported contracts use the same name

### ISSUE THREAD

**Issue by duckki** [crytic/slither#1176]
### Describe the issue:

Slither 0.8.2 crashes on multiple contract definitions sharing the same name.
solc/crytic-compile compiles successfully only with a warning of duplicate names. But, Slither 0.8.2 refuses to resolve the contract name to its source file, leading to a crash. Unfortunately, this can break some projects that used to work fine with Slither 0.8.1.

For example, @openzeppelin (I'm using 4.5.0) has paths to import `IERC721Receiver`:
* @openzeppelin/contracts/token/ERC721/IERC721Receiver.sol
* @openzeppelin/contracts/interfaces/IERC721Receiver.sol

Note: "interfaces/IERC721Receiver.sol" file simply imports "../token/ERC721/IERC721Receiver.sol".
Any projects that imports both paths will crash Slither 0.8.2.

### Code example to reproduce the issue:

contracts/test.sol:
```
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/IERC721Receiver.sol";

abstract contract MyTest is IERC721Receiver {
}
```

contracts/test2.sol:
```
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/interfaces/IERC721Receiver.sol";

abstract contract MyTest2 is IERC721Receiver {
}
```

### Version:

Slither 0.8.2
OpenZeppelin 4.5.0

### Relevant log output:

```
% slither .
'npx truffle compile --all' running (use --truffle-version truffle@x.x.x to use specific version)

Compiling your contracts...
===========================
> Compiling ./contracts/test.sol
> Compiling ./contracts/test2.sol
> Compiling @openzeppelin/contracts/interfaces/IERC721Receiver.sol
> Compiling @openzeppelin/contracts/token/ERC721/IERC721Receiver.sol

<snip>

Traceback (most recent call last):
  File "<system>/slither/slither/__main__.py", line 743, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "<system>/slither/slither/__main__.py", line 84, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "<system>/slither/slither/__main__.py", line 67, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "<system>/slither/slither/slither.py", line 97, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "<system>/slither/slither/solc_parsing/slither_compilation_unit_solc.py", line 224, in parse_top_level_from_loaded_json
    get_imported_scope = self.compilation_unit.get_scope(import_directive.filename)
  File "<system>/slither/slither/core/compilation_unit.py", line 236, in get_scope
    filename = self._crytic_compile_compilation_unit.crytic_compile.filename_lookup(
  File "<virtualenv>/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 199, in filename_lookup
    raise ValueError(
ValueError: @openzeppelin/contracts/interfaces/IERC721Receiver.sol does not exist in dict_keys(['<test>/test-duplicate-contracts/contracts/test2.sol', 'contracts/test2.sol', './contracts/test2.sol', '<test>/test-duplicate-contracts/node_modules/@openzeppelin/contracts/token/ERC721/IERC721Receiver.sol', 'node_modules/@openzeppelin/contracts/token/ERC721/IERC721Receiver.sol', '@openzeppelin/contracts/token/ERC721/IERC721Receiver.sol', '<test>/test-duplicate-contracts/contracts/test.sol', 'contracts/test.sol', './contracts/test.sol'])
```

**Comment by montyly** [comment]
Hi @duckki.

Thank you for reporting this. It is due to a bug in truffle (I opened https://github.com/trufflesuite/truffle/issues/5059). Until truffle refactors their compilation artifacts structure, Slither won't be able to analyze such codebase.

I would recommend moving to hardhat in the meantime.

**Comment by montyly** [comment]
@0xmoostorm: the only solution is to switch to another compilation framework. hardhat is probably the simplest one to transit from truffle

**Comment by 0xmoostorm** [comment]
@montyly thank you!
