### ISSUE TITLE
[Bug]: Slither crashes running `slither . --print variable-order` in solmate

### ISSUE THREAD

**Issue by transmissions11** [crytic/slither#1182]
### Describe the issue:

Running `slither . --print variable-order` in Solmate (a foundry project) crashes with an error about "KeyError: 'ERC20.decimals'"

https://github.com/rari-Capital/solmate

### Code example to reproduce the issue:

```
slither . --print variable-order  
```

### Version:

```
λ slither --version
0.8.3
```

### Relevant log output:

```shell
λ slither . --print variable-order
'forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force' running
Compiling 53 files with 0.8.10
Compiler run successful (with warnings)

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 72, in process_single
    return _process(slither, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 119, in _process
    printer_results = slither.run_printers()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/slither.py", line 211, in run_printers
    return [p.output(self._crytic_compile.target).data for p in self._printers]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/slither.py", line 211, in <listcomp>
    return [p.output(self._crytic_compile.target).data for p in self._printers]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/printers/summary/variable_order.py", line 32, in output
    slot, offset = contract.compilation_unit.storage_layout_of(contract, variable)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/core/compilation_unit.py", line 277, in storage_layout_of
    return self._storage_layouts[contract.name][var.canonical_name]
KeyError: 'ERC20.decimals'
None
Error in .
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 72, in process_single
    return _process(slither, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 119, in _process
    printer_results = slither.run_printers()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/slither.py", line 211, in run_printers
    return [p.output(self._crytic_compile.target).data for p in self._printers]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/slither.py", line 211, in <listcomp>
    return [p.output(self._crytic_compile.target).data for p in self._printers]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/printers/summary/variable_order.py", line 32, in output
    slot, offset = contract.compilation_unit.storage_layout_of(contract, variable)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/core/compilation_unit.py", line 277, in storage_layout_of
    return self._storage_layouts[contract.name][var.canonical_name]
KeyError: 'ERC20.decimals'
```

**Comment by brockelmore** [comment]
Doesn't seem to be foundry specific as a `slither . --print variable-order --compile-force-framework dapp` also fails in a same manner
