### ISSUE TITLE
I keep getting "Error: Source file requires different compiler version" for every contract I try to analyze

### ISSUE THREAD

**Issue by DeFiAccount** [crytic/slither#1197]
I'm in a fresh virtual environment so I installed solc doing this:
`sudo add-apt-repository ppa:ethereum/ethereum`
`sudo apt-get update`
`sudo apt-get install solc`

note that this is _not_ the nightly version as described in the Solidity docs [here](https://docs.soliditylang.org/en/latest/installing-solidity.html#linux-packages)

I then installed Slither by doing this:
`git clone https://github.com/crytic/slither.git
cd slither
python3 setup.py install`

Then I cloned Compound's repo by doing this:
`git clone https://github.com/compound-finance/compound-protocol.git`

I `cd` back to the home directory and run:
`slither compound-protocol/contracts/Comptroller.sol`

but I get this:
(I cant seem to get the markdown correct for a code block, my apologies)

`Compilation warnings/errors on compound-protocol/contracts/Comptroller.sol:
Error: Source file requires different compiler version (current compiler is 0.8.13+commit.abaa5c0e.Linux.g++) - note that nightly builds are considered to be strictly less than the released version
 --> compound-protocol/contracts/Comptroller.sol:1:1:
  |
1 | pragma solidity ^0.5.16;
  | ^^^^^^^^^^^^^^^^^^^^^^^^

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/crytic_compile/platform/solc.py", line 544, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.7/dist-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.7/dist-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/crytic_compile/platform/solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/crytic_compile/platform/solc.py", line 284, in _get_targets_json
    force_legacy_json=force_legacy_json,
  File "/usr/local/lib/python3.7/dist-packages/crytic_compile/platform/solc.py", line 548, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Source file requires different compiler version (current compiler is 0.8.13+commit.abaa5c0e.Linux.g++) - note that nightly builds are considered to be strictly less than the released version
 --> compound-protocol/contracts/Comptroller.sol:1:1:
  |
1 | pragma solidity ^0.5.16;
  | ^^^^^^^^^^^^^^^^^^^^^^^^

None
Error in compound-protocol/contracts/Comptroller.sol
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/crytic_compile/platform/solc.py", line 544, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.7/dist-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.7/dist-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/crytic_compile/platform/solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/crytic_compile/platform/solc.py", line 284, in _get_targets_json
    force_legacy_json=force_legacy_json,
  File "/usr/local/lib/python3.7/dist-packages/crytic_compile/platform/solc.py", line 548, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Source file requires different compiler version (current compiler is 0.8.13+commit.abaa5c0e.Linux.g++) - note that nightly builds are considered to be strictly less than the released version
 --> compound-protocol/contracts/Comptroller.sol:1:1:
  |
1 | pragma solidity ^0.5.16;
  | ^^^^^^^^^^^^^^^^^^^^^^^^`

Evidently, something is wrong with my solc version but I'm not sure what to do about it. I have version 0.8.13 and the Slither README.md says "Ability to analyze contracts written with Solidity >= 0.4" under Features. Comptroller.sol uses 0.5.16, which is >= 0.4

As mentioned, I do not have the nightly build of solc

I also launched a new virtual environment and tried to install Slither via pip3 and am arriving at the same issue. Full disclosure: i'm a noob. I apologize if this is a dumb question or if the solution is obvious, i'm just hoping someone can help me out. Thank you

**EDIT:**
i'm a goon. I noticed I should be using  solc-select for older versions. I did this:

`pip3 install solc-select`
`solc-select install 0.5.16`
`solc-select use 0.5.16`

Now it seems to work when I try to analyze the Comptroller. Would someone be kind enough to tell me if I did solc-select correctly or if there is a better way? I imagine I'll need to install solc-select for every version of an old contract I come across. Is this bad practice? Thanks

**Comment by 0xalpharush** [comment]
You can use `solc-select install all` and crytic-compile will attempt to automatically switch for most compilation platforms.

**Comment by TheStarBoys** [comment]
> solc-select

You're right. Same issue I have was resolved.

**Comment by WarrenPanDDDD** [comment]
My project contains solidity files with version 0.5.16 and 0.8.3. If I `solc-select use 0.5.16`or `solc-select use 0.8.3`, it can't compile the other version. What should I do?
