### ISSUE TITLE
[Bug]: User-defined types

### ISSUE THREAD

**Issue by tbrent** [crytic/slither#1211]
### Describe the issue:

I believe some recent work was done on user-defined types but there are at least some cases for which slither still chokes. Example attached.

### Code example to reproduce the issue:

https://github.com/reserve-protocol/slither-custom-types

### Version:

0.8.3

### Relevant log output:

```shell
Traceback (most recent call last):
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/slither.py", line 123, in __init__
    parser.analyze_contracts()
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 496, in analyze_contracts
    self._convert_to_slithir()
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 681, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/core/declarations/function.py", line 1706, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/core/cfg/node.py", line 720, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/slithir/convert.py", line 118, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/slithir/convert.py", line 1744, in apply_ir_heuristics
    convert_constant_types(irs)
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/slithir/convert.py", line 1680, in convert_constant_types
    t = types[idx]
IndexError: list index out of range
None
Error in Fixed.sol
Traceback (most recent call last):
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/slither.py", line 123, in __init__
    parser.analyze_contracts()
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 496, in analyze_contracts
    self._convert_to_slithir()
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 681, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/core/declarations/function.py", line 1706, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/core/cfg/node.py", line 720, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/slithir/convert.py", line 118, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/slithir/convert.py", line 1744, in apply_ir_heuristics
    convert_constant_types(irs)
  File "/Users/fiddle/.asdf/installs/python/3.9.2/lib/python3.9/site-packages/slither/slithir/convert.py", line 1680, in convert_constant_types
    t = types[idx]
IndexError: list index out of range
```

**Comment by fiddlemath** [comment]
For what it's worth, we've heavily minified the code that yields this. It's in the above repo, but the solidity file it's choking on is just:

``` solidity
pragma solidity ^0.8.9;

type Fix is int192;

function div(uint256 numerator, uint256 divisor) pure returns (uint256) {
    return numerator / divisor;
}

contract FixLib {
    function toUint(Fix x) external pure returns (uint256) {
        return div(uint192(Fix.unwrap(x)), 1e18);
    }
}
```

**Comment by 0xalpharush** [comment]
Adding some other edge cases... 
This [example](https://github.com/crytic/slither/commit/793c4c4ee4580f2df91b0a7778691b0b1c192999#diff-6efc18d2ead7a4d45ac6086d339aaf51079760e2239f080ca54c63348fb166d6)
```
Impossible to generate IR for C.slitherConstructorConstantVariables
Contract C
        Function C.slitherConstructorConstantVariables() (*)
                Expression: s = T.wrap(int224(165521356710917456517261742455526507355687727119203895813322792776))
                IRs:
                        TMP_0 = CONVERT 165521356710917456517261742455526507355687727119203895813322792776 to int224
                        TMP_1 = CONVERT TMP_0 to T
                        s(T) := TMP_1(T)
                Expression: t = s
                IRs:
                        t(T) := s(T)
                Expression: u = T.unwrap(t)
                IRs:
```
Here's a branch with test cases to work off: https://github.com/crytic/slither/tree/userDefinedValueType
