### ISSUE TITLE
[Bug-Candidate]: slither cannot handle top-level constants inside Yul blocks

### ISSUE THREAD

**Issue by sseefried** [crytic/slither#1212]
### Describe the issue:

When running `slither` on a simple contract that contains a Yul block with a reference to a top-level constant it complains with the following error:

```
Error: 
unresolved reference to identifier TopLevelConstant
```

### Code example to reproduce the issue:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.13;

uint constant TopLevelConstant = 42;

contract Simple {

    function foo() public pure returns (uint result) {
        assembly {
            result := TopLevelConstant
        }
    }

}
```

### Version:

0.8.3

### Relevant log output:

```shell
$ slither Simple.sol
Traceback (most recent call last):
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/slither.py", line 119, in __init__
    parser.parse_contracts()
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 489, in parse_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 596, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 669, in _analyze_variables_modifiers_functions
    contract.analyze_content_functions()
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/solc_parsing/declarations/contract.py", line 404, in analyze_content_functions
    function_parser.analyze_content()
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/solc_parsing/declarations/function.py", line 308, in analyze_content
    node_parser.analyze_expressions()
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/solc_parsing/yul/parse_yul.py", line 323, in analyze_expressions
    node.analyze_expressions()
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/solc_parsing/yul/parse_yul.py", line 62, in analyze_expressions
    expression = parse_yul(self._scope, self, self._unparsed_expression)
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/solc_parsing/yul/parse_yul.py", line 830, in parse_yul
    op = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/solc_parsing/yul/parse_yul.py", line 685, in parse_yul_assignment
    return _parse_yul_assignment_common(root, node, ast, "variableNames")
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/solc_parsing/yul/parse_yul.py", line 663, in _parse_yul_assignment_common
    rhs = parse_yul(root, node, ast["value"])
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/solc_parsing/yul/parse_yul.py", line 830, in parse_yul
    op = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/Users/sseefried/Library/Python/3.9/lib/python/site-packages/slither/solc_parsing/yul/parse_yul.py", line 801, in parse_yul_identifier
    raise SlitherException(f"unresolved reference to identifier {name}")
slither.exceptions.SlitherException: unresolved reference to identifier TopLevelConstant
Error:
unresolved reference to identifier TopLevelConstant
Please report an issue to https://github.com/crytic/slither/issues
```
```

**Comment by 0xalpharush** [comment]
Try this branch https://github.com/crytic/slither/pull/1188

**Comment by sseefried** [comment]
@0xalpharush Thanks!
