### ISSUE TITLE
[Bug-Candidate]: can't compile to some contract

### ISSUE THREAD

**Issue by shaokun11** [crytic/slither#1220]
### Describe the issue:

Stack too deep, try removing local variables, I hope to custom the solc compile options and will solve this problem

### Code example to reproduce the issue:

[contract soure](https://etherscan.io/address/0x56e59989bcaf633ee60abc4437f82a91a765f4f5#code)

### Version:

0.8.3

### Relevant log output:

```shell
Compilation warnings/errors on contracts/ImpossibleSwapFactory.sol:
Compiler error: Stack too deep, try removing local variables.
   --> contracts/ImpossiblePair.sol:514:68:
    |
514 |                         (_tradeState == TradeState.SELL_TOKEN_1 && amount0Out == 0),
    |                                                                    ^^^^^^^^^^


Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 544, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.6/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 284, in _get_targets_json
    force_legacy_json=force_legacy_json,
  File "/usr/local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 548, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Compiler error: Stack too deep, try removing local variables.
   --> contracts/ImpossiblePair.sol:514:68:
    |
514 |                         (_tradeState == TradeState.SELL_TOKEN_1 && amount0Out == 0),
    |                                                                    ^^^^^^^^^^


None
Error in contracts/ImpossibleSwapFactory.sol
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 544, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.6/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 284, in _get_targets_json
    force_legacy_json=force_legacy_json,
  File "/usr/local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 548, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Compiler error: Stack too deep, try removing local variables.
   --> contracts/ImpossiblePair.sol:514:68:
    |
514 |                         (_tradeState == TradeState.SELL_TOKEN_1 && amount0Out == 0),
    |                                                                    ^^^^^^^^^^
```

**Comment by shaokun11** [comment]
I found this config [https://github.com/crytic/crytic-compile/blob/master/crytic_compile/cryticparser/defaults.py](https://github.com/crytic/crytic-compile/blob/master/crytic_compile/cryticparser/defaults.py),
I flow this create two file , 
one solc.json is 
{
  "settings": {
    "optimizer": {
      "enabled": true,
      "runs": 200
    }
  }
}
one config json is


{
  "solc_standard_json":"config.json"
}

so I execute comander like this  `slither contracts/ImpossibleSwapFactory.sol --config-file config.json` , but still error like above

**Comment by 0xalpharush** [comment]
I don't have any issue running slither on this address. Can you let me know the output of `crytic-compile --version` and `solc --version`?

**Comment by shaokun11** [comment]
[root@iZuf66wtmh7t7fnz9969vkZ home]# crytic-compile --version
0.2.3
[root@iZuf66wtmh7t7fnz9969vkZ home]# solc --version
solc, the solidity compiler commandline interface
Version: 0.7.6+commit.7338295f.Linux.g++


I can't found how to custom config.file, could you give me a link ?

**Comment by 0xalpharush** [comment]
You can run slither directly on the address: `slither 0x56e59989bcaf633ee60abc4437f82a91a765f4f5`. This shouldn't require any configuration. Fwiw, the configuration docs are here https://github.com/crytic/crytic-compile/wiki/Configuration

**Comment by shaokun11** [comment]
> You can run slither directly on the address: `slither 0x56e59989bcaf633ee60abc4437f82a91a765f4f5`. This shouldn't require any configuration. Fwiw, the configuration docs are here https://github.com/crytic/crytic-compile/wiki/Configuration

yes,it success. 

now I download the source code on my computer, I excute cmd like `slither contracts/ImpossibleSwapFactory.sol --solc-standard-json solc.json`, it failed like above info. the error  could be solve by provider a compile config,I did but failed. something I'm wrong? 

this is solc.json


{
  "settings": {
    "optimizer": {
      "enabled": true,
      "runs": 200
    }
  }
}

**Comment by 0xalpharush** [comment]
Try `slither ./contracts/ImpossibleSwapFactory.sol --solc-args "--optimize --optimize-runs 200"` 

Alternatively, you could use some sort of compilation framework like hardhat to produce the AST and configure the compiler settings in the hardhat config.

**Comment by shaokun11** [comment]
> 

Thanks,I'll try. I just have give up this method. thanks a lot of your help again !!!

**Comment by shaokun11** [comment]
> Try `slither ./contracts/ImpossibleSwapFactory.sol --solc-args "--optimize --optimize-runs 200"`
> 
> Alternatively, you could use some sort of compilation framework like hardhat to produce the AST and configure the compiler settings in the hardhat config.

Thanks,I'll try. I just have give up this method. thanks a lot of your help again !!!

**Comment by shaokun11** [comment]
> Try `slither ./contracts/ImpossibleSwapFactory.sol --solc-args "--optimize --optimize-runs 200"`
> 
> Alternatively, you could use some sort of compilation framework like hardhat to produce the AST and configure the compiler settings in the hardhat config.

I did like you said and it work. thanks a lot !!!!
