### ISSUE TITLE
[Bug-Candidate]: Unable to use foundry out of the box with relative imports in lib

### ISSUE THREAD

**Issue by Elyx0** [crytic/slither#1226]
### Describe the issue:

Slither(foundry) chokes on libs/ with relative import inside.
Command: `slither .`

Using:
- forge 0.2.0 (1616380 2022-06-05T00:17:15.301459Z)
- mac os 12.0.1 arm
- slither 0.8.3 (brew+pip)

Example slitherable minimal repo: https://github.com/Elyx0/foundry-slither-oz-choke/blob/main/src/Contract.sol#L6
_See file comments on how to make unslitherable by uncommenting 2 lines of `Contract.sol`_ 

Built with:
```bash
forge init
forge install openzeppelin/openzeppelin-contracts
forge remappings > remappings.txt
``` 

Error log:
```
'forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force' running
Compiling 13 files with 0.8.13
Solc 0.8.13 finished in 1.17s
Compiler run successful (with warnings)
warning[2072]: Warning: Unused local variable.
  --> src/Contract.sol:13:9:
   |
13 |         IERC20 token = IERC20(_token); // Uncomment me as well if you uncomment above
   |         ^^^^^^^^^^^^

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/opt/homebrew/lib/python3.9/site-packages/slither/slither.py", line 95, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 256, in parse_top_level_from_loaded_json
    get_imported_scope = self.compilation_unit.get_scope(import_directive.filename)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/core/compilation_unit.py", line 231, in get_scope
    filename = self._crytic_compile_compilation_unit.crytic_compile.filename_lookup(
  File "/opt/homebrew/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 199, in filename_lookup
    raise ValueError(
ValueError: lib/openzeppelin-contracts/contracts/interfaces/IERC20.sol does not exist in ['/Users/me/slithfoundry/lib/forge-std/src/console2.sol', '/Users/me/slithfoundry/lib/forge-std/src/console2.sol', ...ETC ALL .SOL FILES]
None
Error in .
```

`forge test` passes correctly while in the "unslitherable" state. No issues.

Potentially related: https://github.com/crytic/slither/issues/1214 I grepped the `ast` and they seem to be there.

```
grep -nr "ast" ./out
./out/Vm.sol/Vm.json:61:      "name": "broadcast",
./out/Vm.sol/Vm.json:74:      "name": "broadcast",
./out/Vm.sol/Vm.json:870:      "name": "startBroadcast",
./out/Vm.sol/Vm.json:883:      "name": "startBroadcast",
./out/Vm.sol/Vm.json:921:      "name": "stopBroadcast",
./out/Vm.sol/Vm.json:984:    "broadcast()": "afc98040",
./out/Vm.sol/Vm.json:985:    "broadcast(address)": "e6962cdb",
./out/Vm.sol/Vm.json:1027:    "startBroadcast()": "7fb5297f",
./out/Vm.sol/Vm.json:1028:    "startBroadcast(address)": "7fec2a8d",
./out/Vm.sol/Vm.json:1031:    "stopBroadcast()": "76eadd36",
./out/Vm.sol/Vm.json:1044:  "ast": {
./out/Vm.sol/Vm.json:5344:            "name": "broadcast",
./out/Vm.sol/Vm.json:5371:            "name": "broadcast",
./out/Vm.sol/Vm.json:5427:            "name": "startBroadcast",
./out/Vm.sol/Vm.json:5454:            "name": "startBroadcast",
./out/Vm.sol/Vm.json:5510:            "name": "stopBroadcast",
./out/Ownable.sol/Ownable.json:94:  "ast": {
./out/Address.sol/Address.json:23:  "ast": {
./out/Address.sol/Address.json:1301:              "text": " @dev Same as {xref-Address-functionCall-address-bytes-}[`functionCall`],\n but also transferring `value` wei to `target`.\n Requirements:\n - the calling contract must have an ETH balance of at least `value`.\n - the called Solidity function must be `payable`.\n _Available since v3.1._"
./out/console2.sol/console2.json:22:  "ast": {
./out/test.sol/stdStorage.json:99:  "ast": {
./out/test.sol/stdMath.json:22:  "ast": {
./out/test.sol/Test.json:698:  "ast": {
./out/test.sol/stdError.json:164:  "ast": {
./out/test.sol/DSTest.json:320:  "ast": {
./out/Context.sol/Context.json:23:  "ast": {
./out/Script.sol/Script.json:38:  "ast": {
./out/console.sol/console.json:22:  "ast": {
./out/Contract.sol/Greeter.json:106:  "ast": {
./out/Contract.t.sol/ContractTest.json:714:  "ast": {
```
out/IERC20.sol/IERC20.json only present path is
```json
  {
  "ast": {
    "absolutePath": "lib/openzeppelin-contracts/contracts/token/ERC20/IERC20.sol",
    "id": 20898,
    "exportedSymbols": {
      "IERC20": [
        20897
      ]
    },
    "nodeType": "SourceUnit",
    "src": "106:2661:8",
    "nodes": [] // a lot
}
```

out/Contract.sol/Greeter.json has
```json
      {
        "id": 21219,
        "nodeType": "ImportDirective",
        "src": "185:64:11",
        "absolutePath": "lib/openzeppelin-contracts/contracts/interfaces/IERC20.sol",
        "file": "openzeppelin-contracts/contracts/interfaces/IERC20.sol",
        "nameLocation": "-1:-1:-1",
        "scope": 21247,
        "sourceUnit": 20820,
        "symbolAliases": [],
        "unitAlias": ""
      }    
```
---

#### Additional Notes:

In the **slitherable** state (no IERC20 uncommented):

`slither src/Contract.sol` while trying to target a specific file chokes as well:
```c
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Source "openzeppelin-contracts/contracts/utils/Address.sol" not found: File not found. Searched the following locations: "".
 --> src/Contract.sol:4:1:
  |
4 | import "openzeppelin-contracts/contracts/utils/Address.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: Source "openzeppelin-contracts/contracts/access/Ownable.sol" not found: File not found. Searched the following locations: "".
 --> src/Contract.sol:5:1:
  |
5 | import "openzeppelin-contracts/contracts/access/Ownable.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Likewise for `slither src/Contract.sol --compile-force-framework foundry`
```c
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'src/Contract.sol'
None
Error in src/Contract.sol
```

---
Out of ideas for now. Good luck!

### Code example to reproduce the issue:

https://github.com/Elyx0/foundry-slither-oz-choke/blob/main/src/Contract.sol#L6

### Version:

0.8.3

**Comment by pedrommaiaa** [comment]
Having the same problem with the [Solmate](https://github.com/Rari-Capital/solmate) library.

```
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Source "solmate/utils/FixedPointMathLib.sol" not found: File not found.
 --> src/Contract.sol:5:1:
  |
5 | import {FixedPointMathLib} from "solmate/utils/FixedPointMathLib.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

`forge test` works normally.
