### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by srn87** [crytic/slither#1232]
### Describe the desired feature

i dont know what i m doing wrong i put in terminal slither test\SimpleNft_flat.sol and get: (SimpleNft_flat.sol name of contract)
```
Traceback (most recent call last):
  File "C:\Users\saaja\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 744, 
in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "C:\Users\saaja\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "C:\Users\saaja\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 660, in compile_all
    raise ValueError(f"Unresolved target: {str(target)}")
ValueError: Unresolved target: test\SimpleNftflat.sol
None
Error in test\SimpleNftflat.sol
Traceback (most recent call last):
  File "C:\Users\saaja\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 744, 
in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "C:\Users\saaja\AppData\Local\Programs\Python\Python310\lib\site-packages\slither\__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "C:\Users\saaja\AppData\Local\Programs\Python\Python310\lib\site-packages\crytic_compile\crytic_compile.py", line 660, in compile_all
    raise ValueError(f"Unresolved target: {str(target)}")
ValueError: Unresolved target: test\SimpleNftflat.sol
```

**Comment by elopez** [comment]
Thanks for the report @srn87! Please check that you are using the correct filename and that the file exists; the name on the report (`test\SimpleNft_flat.sol`) does not match the filename on the error message you copied (`test\SimpleNftflat.sol`)
