### ISSUE TITLE
[Bug-Candidate]: Cannot run `slither-flat` in a hardhat project.

### ISSUE THREAD

**Issue by hickscorp** [crytic/slither#1240]
### Describe the issue:

With `pwd` being the hardhat project root (where `hardhat.config.ts` sits), it doesn't seem to be possible to flatten the contracts.
Running `slither-flat --compile-force hardhat . --strategy OneFile` results in:

### Code example to reproduce the issue:

It's difficult to join a code snippet, as the project is quite big.

### Version:

0.8.3

### Relevant log output:

```shell
Traceback (most recent call last):
  File "/home/user/.local/bin/slither-flat", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.9/site-packages/slither/tools/flattening/__main__.py", line 106, in main
    slither = Slither(args.filename, **vars(args))
  File "/home/user/.local/lib/python3.9/site-packages/slither/slither.py", line 95, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/home/user/.local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 211, in parse_top_level_from_loaded_json
    contract.set_offset(top_level_data["src"], self._compilation_unit)
  File "/home/user/.local/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 124, in set_offset
    self._source_mapping = self._convert_source_mapping(offset, compilation_unit)
  File "/home/user/.local/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 101, in _convert_source_mapping
    (lines, starting_column, ending_column) = self._compute_line(
  File "/home/user/.local/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 43, in _compute_line
    end_line, ending_column = compilation_unit.core.crytic_compile.get_line_from_offset(
  File "/home/user/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 291, in get_line_from_offset
    return lines_delimiters[offset]
KeyError: 6870
```

**Comment by hickscorp** [comment]
@0xalpharush I'm not sure whether or not it's a duplicate, I found these two bugs on `slither` and `slither-flat`.

**Comment by 0xalpharush** [comment]
Since the project uses a custom build script, I tried `yarn build && slither . --ignore-compile` and it worked (substitute other slither commands such as slither-flat). 

I labeled it as a duplicate since the error message is identical for both issues and indicates that crytic-compile (a separate package) did not successfully run, meaning slither/ slither-flat was not what failed. Both slither and slither-flat rely on crytic-compile to get the AST/ contract sources, so neither of them will work without crytic-compile running successfully.

**Comment by elopez** [comment]
To add to the above, I cannot reproduce the issue locally either, both slither and slither-flat worked fine with `tableturn/tt-white-contracts` on branch `features/integrates-with-hardhat-deploy` with node v16.15.1, yarn 1.22.19, slither 0.8.3, crytic-compile 0.2.3 with no special steps on my side.

I've seen this problem happen occasionally when old hardhat artifacts remain on the project, can you confirm if this is still an issue after running `hardhat clean` and removing any old files from `crytic-export/`?

**Comment by hickscorp** [comment]
Thanks to you both for taking the time.

@0xalpharush  `yarn build && slither . --ignore-compile` doesn't work for me - same error.
@elopez `rm -rf abi crytic-export artifacts cache deployments typechain && slither .` - same error.
