### ISSUE TITLE
Having issues running yarn slither

### ISSUE THREAD

**Issue by rmajidy** [crytic/slither#1259]
### Describe the issue:

When running yarn slither, after installing all dependencies the following error output occurs.

### Code example to reproduce the issue:

yarn slither

output: 
`yarn run v1.22.19
$ slither ./contracts --solc-remaps '@openzeppelin=node_modules/@openzeppelin @chainlink=node_modules/@chainlink' --exclude naming-convention,external-function,low-level-calls --buidler-ignore-compile
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 658, in compile_all
    compilations.append(CryticCompile(filename, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 276, in _get_targets_json
    return _run_solc(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 474, in _run_solc
    compiler="solc", version=get_version(solc, env), optimized=is_optimized(solc_arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 381, in get_version
    raise InvalidCompilation(f"Solidity version not found: {stdout}")
crytic_compile.platform.exceptions.InvalidCompilation: Solidity version not found: No solc version set. Run `solc-select use VERSION` or set SOLC_VERSION environment variable.

None
Error in ./contracts
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 658, in compile_all
    compilations.append(CryticCompile(filename, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 276, in _get_targets_json
    return _run_solc(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 474, in _run_solc
    compiler="solc", version=get_version(solc, env), optimized=is_optimized(solc_arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/crytic_compile/platform/solc.py", line 381, in get_version
    raise InvalidCompilation(f"Solidity version not found: {stdout}")
crytic_compile.platform.exceptions.InvalidCompilation: Solidity version not found: No solc version set. Run `solc-select use VERSION` or set SOLC_VERSION environment variable.

error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

### Version:

0.8.3

**Comment by 0xalpharush** [comment]
What compilation framework are you using? I suspect if you ran something like `slither .` instead, it may pick up the correct platform instead of looking for standalone `solc`

**Comment by elopez** [comment]
If you want to use the standalone solc integration, you need to install a suitable solc as well. In the error message you pasted, solc-select is saying solc is not available:

```
crytic_compile.platform.exceptions.InvalidCompilation: Solidity version not found: No solc version set. Run solc-select use VERSION or set SOLC_VERSION environment variable.
```

this is solvable by running something like `solc-select install 0.x.y && solc-select use 0.x.y`

**Comment by rmajidy** [comment]
> If you want to use the standalone solc integration, you need to install a suitable solc as well. In the error message you pasted, solc-select is saying solc is not available:
> 
> ```
> crytic_compile.platform.exceptions.InvalidCompilation: Solidity version not found: No solc version set. Run solc-select use VERSION or set SOLC_VERSION environment variable.
> ```
> 
> this is solvable by running something like `solc-select install 0.x.y && solc-select use 0.x.y`

This is the slither script i run, won't the `--solc-remaps` solve this?

`slither ./contracts --solc-remaps '@openzeppelin=node_modules/@openzeppelin @chainlink=node_modules/@chainlink' --exclude naming-convention,external-function,low-level-calls --buidler-ignore-compile`

**Comment by rmajidy** [comment]
sorry I'm new to developing excuse my lack of experience

**Comment by elopez** [comment]
No worries 😄 if you are using the integration with solc itself (like in your example command, providing a folder with arbitrary contract files), you need to have a working solc in your system. `--solc-remaps` just adds the right remaps for the imports in the solidity code, but slither still needs a compiler (solc) it can call to compile your solidity code. Seeing that you already have solc-select installed, it should be a matter of installing and choosing a specific solc version with `solc-select install 0.x.y && solc-select use 0.x.y`

If you are using a compilation framework like @0xalpharush was saying (eg hardhat, buidler) all of this is not needed and you can just run `slither folder/` where `folder/` is the folder path to your project directory (eg. the folder that has the `hardhat.config.ts` or `buidler.config.ts` file). Slither will then take advantage of the compilation framework to do the build, instead of calling solc directly.

**Comment by rmajidy** [comment]
@elopez right in my case i'm using hardhat and the `hardhat.config.js` is in my current working directory that's selected when I run it. so not sure why the compilation framework isn't doing what it's supposed to. I installed all the dev dependencies as well.  

ps. I'm following this tutorial by Patrick Collins
https://www.youtube.com/watch?v=TmZ8gH-toX0

**Comment by 0xalpharush** [comment]
Can you try this patched branch and let me know if you run into issues? https://github.com/PatrickAlphaC/hardhat-security-fcc/pull/3

**Comment by elopez** [comment]
@rmajidy the current working directory may be the project folder, but you are specifying `./contracts` as the target on your slither command, which is not the project directory. Slither looks at the target directory to determine if it should use a compilation framework. In this case, it inspects `./contracts`, and sees no sign of hardhat on there, so it is treating the target like it would do with a folder with standalone solc files.

If you are working from the project directory, you should use `.` as the target (ie `slither . --exclude ...`), and this will make slither use hardhat to build.

@0xalpharush thanks for submitting a fix upstream! 😃
