### ISSUE TITLE
[Bug]: slither 0.8.3 crashing

### ISSUE THREAD

**Issue by thedavidmeister** [crytic/slither#1266]
### Describe the issue:

```
Missing function 'value'
Missing function 'value'
Missing function 'value'
Missing function 'value'
Missing function 'value'
Missing function 'value'
Missing function 'value'
Missing function Variable not found: initializer (context Sale)
Traceback (most recent call last):
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/__main__.py", line 72, in process_single
    return _process(slither, detector_classes, printer_classes)
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/__main__.py", line 113, in _process
    detector_results = slither.run_detectors()
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/slither.py", line 201, in run_detectors
    results = [d.detect() for d in self._detectors]
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/slither.py", line 201, in <listcomp>
    results = [d.detect() for d in self._detectors]
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/abstract_detector.py", line 152, in detect
    for r in [output.data for output in self._detect()]:
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy_eth.py", line 93, in _detect
    super()._detect()
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 303, in _detect
    self.detect_reentrancy(c)
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 290, in detect_reentrancy
    self._explore(function.entry_point, [])
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 282, in _explore
    self._explore(son, visited)
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 282, in _explore
    self._explore(son, visited)
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 282, in _explore
    self._explore(son, visited)
  [Previous line repeated 1 more time]
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 267, in _explore
    contains_call = fathers_context.analyze_node(node, self)
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 159, in analyze_node
    if detector.can_callback(ir):
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line [228](https://github.com/beehive-innovation/rain-protocol/runs/7194366865?check_suite_focus=true#step:4:229), in can_callback
    return isinstance(ir, Call) and ir.can_reenter()
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/slithir/operations/library_call.py", line 27, in can_reenter
    return self.function.can_reenter(callstack)
AttributeError: 'NoneType' object has no attribute 'can_reenter'
None
Error in .
Traceback (most recent call last):
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/__main__.py", line 72, in process_single
    return _process(slither, detector_classes, printer_classes)
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/__main__.py", line 113, in _process
    detector_results = slither.run_detectors()
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/slither.py", line 201, in run_detectors
    results = [d.detect() for d in self._detectors]
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/slither.py", line 201, in <listcomp>
    results = [d.detect() for d in self._detectors]
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/abstract_detector.py", line 152, in detect
    for r in [output.data for output in self._detect()]:
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy_eth.py", line 93, in _detect
    super()._detect()
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 303, in _detect
    self.detect_reentrancy(c)
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 290, in detect_reentrancy
    self._explore(function.entry_point, [])
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 282, in _explore
    self._explore(son, visited)
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 282, in _explore
    self._explore(son, visited)
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 282, in _explore
    self._explore(son, visited)
  [Previous line repeated 1 more time]
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 267, in _explore
    contains_call = fathers_context.analyze_node(node, self)
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 159, in analyze_node
    if detector.can_callback(ir):
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/detectors/reentrancy/reentrancy.py", line 228, in can_callback
    return isinstance(ir, Call) and ir.can_reenter()
  File "/nix/store/dyb0f0f2j23qgy5bdgfhjxfhrwks48as-python3.10-slither-analyzer-0.8.3/lib/python3.10/site-packages/slither/slithir/operations/library_call.py", line 27, in can_reenter
    return self.function.can_reenter(callstack)
AttributeError: 'NoneType' object has no attribute 'can_reenter'
```

Getting this cryptic set of errors when running `slither . --npx-disable --filter-paths="contracts/test" --exclude-dependencies`

Can see this in CI: https://github.com/beehive-innovation/rain-protocol/runs/7194366865?check_suite_focus=true

I tried removing top level constants and enums as I saw this was causing others issues, but it didn't seem to help

### Code example to reproduce the issue:

https://github.com/beehive-innovation/rain-protocol/runs/7194366865?check_suite_focus=true

### Version:

0.8.3

**Comment by 0xalpharush** [comment]
@thedavidmeister Would you mind seeing if this branch fixes the issue you ran into? https://github.com/crytic/slither/pull/1267

**Comment by thedavidmeister** [comment]
@0xalpharush hey sorry, i have no python experience and after getting about 5 cryptic (to me) errors deep in the "virtual env" setup i had to stop

the repository with the errors is public though, you should be able to pull it and run slither on it against develop to see the problem

i removed all custom errors from my solidity code (which i believe is what the linked issue is about) and am still seeing the same errors when i run slither

**Comment by 0xalpharush** [comment]
Thanks for checking. I'm looking into it. As of now, I expect it is in edge case in how slither parses assembly. I'll working on a fix.

**Comment by 0xalpharush** [comment]
The first issue has to do with the declaration of yul variables without assigning them:
```
    function sub(uint256 operand_, uint256 stackTopLocation_)
        internal
        pure
        returns (uint256)
    {
        assembly {
            let location_ := sub(stackTopLocation_, mul(operand_, 0x20))
            let accumulator_ := mload(location_)
            let intermediate_
            for {
                let cursor_ := add(location_, 0x20)
            } lt(cursor_, stackTopLocation_) {
                cursor_ := add(cursor_, 0x20)
            } {
                intermediate_ := sub(accumulator_, mload(cursor_))
                // Adapted from Open Zeppelin safe math.
                if gt(intermediate_, accumulator_) {
                    revert(0, 0)
                }
                accumulator_ := intermediate_
            }
            mstore(location_, accumulator_)
            stackTopLocation_ := add(location_, 0x20)
        }

        return stackTopLocation_;
    }
```
This code does not handle this edge case:
https://github.com/crytic/slither/blob/db703d82f4876e30f1ca10fb78d85b4dd4c31ec1/slither/solc_parsing/yul/parse_yul.py#L669-L680
The second issue regarding the `initializer` modifier should be fixed by https://github.com/crytic/slither/pull/1227

**Comment by thedavidmeister** [comment]
@0xalpharush when do you expect these fixes you are referencing to be available in a release?

**Comment by 0xalpharush** [comment]
I haven't tested it but I think `let intermediate_ := 0x0` may bypass the first error. Not sure about the second issue unfortunately.

**Comment by engn33r** [comment]
I had this same issue with slither 0.8.3, but updating to 0.9.1 fixed the issue. This issue can be closed as far as I can tell.
