### ISSUE TITLE
[Bug-Candidate]: Windows slither on a single file

### ISSUE THREAD

**Issue by PedroReyes** [crytic/slither#1269]
### Describe the issue:

Hello,

💻 System

Windows 10
node v14.18.1
npm 6.14.15
Python 3.10.0

❌Problem
I have installed as follow in the README.md

```
git clone https://github.com/crytic/slither.git && cd slither
python setup.py install
```

When I try to execute the next command `slither contracts/1_Fallback/Fallback.sol ` I get the output I attached.

Could you help me out? 

Best regards,
Pedro Reyes.

### Code example to reproduce the issue:

https://github.com/PedroReyes/ethernaut/commits/master

### Version:

```
$ slither --version
0.8.3
```

### Relevant log output:

```shell
$ slither contracts/1_Fallback/Fallback.sol 
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 370, in get_version
    with subprocess.Popen(
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\slither_analyzer-0.8.3-py3.10.egg\slither\__main__.py", line 755, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "C:\Python310\lib\site-packages\slither_analyzer-0.8.3-py3.10.egg\slither\__main__.py", line 76, in 
process_all
    compilations = compile_all(target, **vars(args))
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 276, in _get_targets_json
    return _run_solc(
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 474, in _run_solc
    compiler="solc", version=get_version(solc, env), optimized=is_optimized(solc_arguments)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 385, in get_version
    raise InvalidCompilation(error)
crytic_compile.platform.exceptions.InvalidCompilation: [WinError 2] El sistema no puede encontrar el archivo especificado
None
Error in contracts/1_Fallback/Fallback.sol
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 370, in get_version
    with subprocess.Popen(
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\slither_analyzer-0.8.3-py3.10.egg\slither\__main__.py", line 755, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "C:\Python310\lib\site-packages\slither_analyzer-0.8.3-py3.10.egg\slither\__main__.py", line 76, in 
process_all
    compilations = compile_all(target, **vars(args))
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 276, in _get_targets_json
    return _run_solc(
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 474, in _run_solc
    compiler="solc", version=get_version(solc, env), optimized=is_optimized(solc_arguments)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 385, in get_version
    raise InvalidCompilation(error)
crytic_compile.platform.exceptions.InvalidCompilation: [WinError 2] El sistema no puede encontrar el archivo especificado
```

**Comment by PedroReyes** [comment]
Hello @elopez ,

Thanks for helping me out. 

I have installed `solc-select`: 

```
$ pip install solc-select==1.0.0b1
Requirement already satisfied: solc-select==1.0.0b1 in c:\python310\lib\site-packages (1.0.0b1)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
```

![image](https://user-images.githubusercontent.com/4096108/177788370-dd4b8128-5263-46c1-bc8b-f854a399e463.png)

However, I obtain the next output error when executing `slither contracts/1_Fallback/Fallback.sol`:

```
$ slither contracts/1_Fallback/Fallback.sol 
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 370, in get_version
    with subprocess.Popen(
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\slither_analyzer-0.8.3-py3.10.egg\slither\__main__.py", line 755, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "C:\Python310\lib\site-packages\slither_analyzer-0.8.3-py3.10.egg\slither\__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 276, in _get_targets_json
    return _run_solc(
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 474, in _run_solc
    compiler="solc", version=get_version(solc, env), optimized=is_optimized(solc_arguments)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 385, in get_version
    raise InvalidCompilation(error)
crytic_compile.platform.exceptions.InvalidCompilation: [WinError 2] El sistema no puede encontrar el archivo especificado
None
Error in contracts/1_Fallback/Fallback.sol
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 370, in get_version
    with subprocess.Popen(
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\slither_analyzer-0.8.3-py3.10.egg\slither\__main__.py", line 755, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "C:\Python310\lib\site-packages\slither_analyzer-0.8.3-py3.10.egg\slither\__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 276, in _get_targets_json
    return _run_solc(
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 474, in _run_solc
    compiler="solc", version=get_version(solc, env), optimized=is_optimized(solc_arguments)
  File "C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg\crytic_compile\platform\solc.py", line 385, in get_version
    raise InvalidCompilation(error)
crytic_compile.platform.exceptions.InvalidCompilation: [WinError 2] El sistema no puede encontrar el archivo especificado
```

After seeing this `C:\Python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg` I installed `cryptic_compile` but it seems the installation was already there according to the next output:

```
$ pip3 install crytic-compile
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
Requirement already satisfied: crytic-compile in c:\python310\lib\site-packages\crytic_compile-0.2.3-py3.10.egg (0.2.3)
Requirement already satisfied: pysha3>=1.0.2 in c:\python310\lib\site-packages\pysha3-1.0.2-py3.10-win-amd64.egg (from crytic-compile) (1.0.2)
```

Unfortunately, the error persist. Maybe I made a mistake in the installation 🤔

Best regards,
Pedro Reyes.

**Comment by PedroReyes** [comment]
Hello @elopez ,

No, it doesn't:

```
$ solc --version
bash: solc: command not found
```

Just for your information:

```
$ solcjs --version
0.8.15+commit.e14f2714.Emscripten.clang
```

Shall I try the installation again from scratch?

Best regards,
Pedro Reyes
