### ISSUE TITLE
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: contracts/hardhat-dependency-compiler/@openzeppelin/contracts/access/AccessControlEnumerable.sol

### ISSUE THREAD

**Issue by TsigelnikovNikita** [crytic/slither#1283]
Hello guys, I'm getting following error when I just try to execute slither tool in my hardhat project:
```
slither .
'npx hardhat compile --force' running
Generating typings for: 14 artifacts in dir: typechain-types for target: ethers-v5
Successfully generated 30 typings!
Compiled 17 Solidity files successfully

Traceback (most recent call last):
  File "/home/nikita/.local/lib/python3.8/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/nikita/.local/lib/python3.8/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/platform/hardhat.py", line 169, in compile
    path = convert_filename(
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/utils/naming.py", line 117, in convert_filename
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: contracts/hardhat-dependency-compiler/@openzeppelin/contracts/access/AccessControlEnumerable.sol
None
Error in .
Traceback (most recent call last):
  File "/home/nikita/.local/lib/python3.8/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/nikita/.local/lib/python3.8/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/platform/hardhat.py", line 169, in compile
    path = convert_filename(
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/utils/naming.py", line 117, in convert_filename
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: contracts/hardhat-dependency-compiler/@openzeppelin/contracts/access/AccessControlEnumerable.sol
```
I've found similar issue here: https://github.com/crytic/slither/issues/852, except that in my case I have "contracts/hardhat-dependency-compiler" prefix in the path.

So why does slither add this prefix to the path?

**Comment by TsigelnikovNikita** [comment]
Also I see that this directory is being created while I run ```hh compile``` or ```slither .```
![image](https://user-images.githubusercontent.com/58594559/178251942-b503d8a8-5c52-4652-943e-836bb3dac34e.png)

**Comment by TsigelnikovNikita** [comment]
Yes. The error also happens with the 0.8.3 slither version. The error is also reproduced in this repo: https://github.com/TsigelnikovNikita/NFTs
```
slither .
'npx hardhat compile --force' running
Generating typings for: 16 artifacts in dir: typechain-types for target: ethers-v5
Successfully generated 52 typings!
Compiled 18 Solidity files successfully

Traceback (most recent call last):
  File "/home/nikita/.local/lib/python3.8/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/nikita/.local/lib/python3.8/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/platform/hardhat.py", line 169, in compile
    path = convert_filename(
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/utils/naming.py", line 117, in convert_filename
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: contracts/hardhat-dependency-compiler/@openzeppelin/contracts/token/ERC721/ERC721.sol
None
Error in .
Traceback (most recent call last):
  File "/home/nikita/.local/lib/python3.8/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/nikita/.local/lib/python3.8/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/platform/hardhat.py", line 169, in compile
    path = convert_filename(
  File "/home/nikita/.local/lib/python3.8/site-packages/crytic_compile/utils/naming.py", line 117, in convert_filename
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: contracts/hardhat-dependency-compiler/@openzeppelin/contracts/token/ERC721/ERC721.sol
```

**Comment by fullkomnun** [comment]
It can be solved by defining 'keep' [flag](https://github.com/ItsNickBarry/hardhat-dependency-compiler#usage) as 'true' for `hardhat-dependency-compiler` plugin in `hardhat.config.ts`:
```typescript
  dependencyCompiler: {
    paths: [
      "hardhat-deploy/solc_0.8/openzeppelin/proxy/transparent/ProxyAdmin.sol",
      "hardhat-deploy/solc_0.8/proxy/OptimizedTransparentUpgradeableProxy.sol",
    ],
    keep: true,
  },
```

You may also want to add 'contracts/hardhat-dependency-compiler' (may vary) to your `.gitignore`

**Comment by TsigelnikovNikita** [comment]
Thanks @fullkomnun it works for me! But anything I think that this is a temp solution, isn't it?

**Comment by 0xalpharush** [comment]
@TsigelnikovNikita In order to analyze the code, the source files of all dependencies must be available. We will document that if `dependencyCompiler` is used, `keep` must be set to `true`.

**Comment by joebb10** [comment]
Hi! I'm getting the same error but that solution didn't work. Any other?

Thanks in advance

**Comment by akugone** [comment]
Hello i tried the solution you provide but i keep get the same error, any update about it ?
<img width="1070" alt="Capture d’écran 2022-12-20 à 16 11 33" src="https://user-images.githubusercontent.com/19951458/208700077-6ba9e75b-14b2-4692-bf49-94483d161936.png">

**Comment by asmitadhungana** [comment]
> contracts/hardhat-dependency-compiler'

Hi, how did you manage to solve this error? 
I'm getting the same error now my imported files.

**Comment by akugone** [comment]
I thinks it was a openzeppelin remap problem , try something like add @openzeppelin/=$(pwd)/node_modules/@openzeppelin/ in your command
