### ISSUE TITLE
Add `--convert-library-to-internal` option to support echidna.

### ISSUE THREAD

**Issue by TheStarBoys** [crytic/slither#1298]
### Describe the desired feature

When using echidna to analyze contract, if the contract contians a library, which has public or external functions, there is an error "unlinked libraries detected in bytecode". Just using "internal" instead of "external" or "public" will work good. If having a program to complete this function is pretty cool. Just like existing "--convert-external" option, we provide "--convert-library-to-internal" option. It's cool, right?

**Comment by 0xKarl98** [comment]
Is this flag being applied to echidna yet ?
i tried to use the same , but without valid output . 
if so , which should i run inside echidna ?

**Comment by asmitadhungana** [comment]
> Is this flag being applied to echidna yet ? i tried to use the same , but without valid output . if so , which should i run inside echidna ?

You can run it while flattening you contract with `slither-flat`.

**Comment by asmitadhungana** [comment]
What are the caveats to running this flag successfully? 
I noticed that I can run it successfully over some external libraries while the same command fails with an `AssetionError` with the following stack-trace for some other external libraries.
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/slither-flat", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/slither/tools/flattening/__main__.py", line 112, in main
    slither = Slither(args.filename, **vars(args))
  File "/opt/homebrew/lib/python3.10/site-packages/slither/slither.py", line 125, in __init__
    parser.parse_contracts()
  File "/opt/homebrew/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 489, in parse_contracts
    self._analyze_second_part(contracts_to_be_analyzed, libraries)
  File "/opt/homebrew/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 557, in _analyze_second_part
    self._analyze_top_level_structures()
  File "/opt/homebrew/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 635, in _analyze_top_level_structures
    struct.analyze()
  File "/opt/homebrew/lib/python3.10/site-packages/slither/solc_parsing/declarations/structure_top_level.py", line 57, in analyze
    elem_parser.analyze(self)
  File "/opt/homebrew/lib/python3.10/site-packages/slither/solc_parsing/variables/variable_declaration.py", line 210, in analyze
    self._variable.type = parse_type(self._elem_to_parse, caller_context)
  File "/opt/homebrew/lib/python3.10/site-packages/slither/solc_parsing/solidity_types/type_parsing.py", line 419, in parse_type
    array_type = parse_type(t["baseType"], next_context)
  File "/opt/homebrew/lib/python3.10/site-packages/slither/solc_parsing/solidity_types/type_parsing.py", line 418, in parse_type
    length = parse_expression(t["length"], caller_context)
  File "/opt/homebrew/lib/python3.10/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 258, in parse_expression
    assert isinstance(caller_context, CallerContextExpression)
    ```
