### ISSUE TITLE
[Bug-Candidate]: Slither suddenly started failing when running

### ISSUE THREAD

**Issue by Bolee95** [crytic/slither#1324]
### Describe the issue:

When trying to run `Slither` it fails without any concrete information but with the trace stack that I couldn't demystify.
Contracts compilation is successful as well as tests running.

### Code example to reproduce the issue:

`slither .`

### Version:

Slither 0.8.3
Hardhat 2.10.1
MacOS 12.5

### Relevant log output:

```shell
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/slither.py", line 95, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 211, in parse_top_level_from_loaded_json
    contract.set_offset(top_level_data["src"], self._compilation_unit)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 124, in set_offset
    self._source_mapping = self._convert_source_mapping(offset, compilation_unit)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 101, in _convert_source_mapping
    (lines, starting_column, ending_column) = self._compute_line(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 43, in _compute_line
    end_line, ending_column = compilation_unit.core.crytic_compile.get_line_from_offset(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 291, in get_line_from_offset
    return lines_delimiters[offset]
KeyError: 511
None
Error in .
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/slither.py", line 95, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 211, in parse_top_level_from_loaded_json
    contract.set_offset(top_level_data["src"], self._compilation_unit)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 124, in set_offset
    self._source_mapping = self._convert_source_mapping(offset, compilation_unit)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 101, in _convert_source_mapping
    (lines, starting_column, ending_column) = self._compute_line(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slither/core/source_mapping/source_mapping.py", line 43, in _compute_line
    end_line, ending_column = compilation_unit.core.crytic_compile.get_line_from_offset(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 291, in get_line_from_offset
    return lines_delimiters[offset]
KeyError: 511
```

**Comment by Bolee95** [comment]
@0xTimepunk Not sure, I still haven't been able to make it work. I would assume these are internal identifiers of errors.

**Comment by 0xalpharush** [comment]
Can you show the output of `crytic-compile .`? Another thing to try is running `npx hardhat clean` and recompiling from scratch.

**Comment by Bolee95** [comment]
Hi @0xalpharush,
I tried it out again with the older codebase, where the issue was first detected, as well as with the new one. I was able to get a proper report, so I wasn't able to replicate this.
I haven't run `npx hardhat clean` before it. 
The only notisable difference between when the issue was appearing and now is that I updated `hardhat` to `2.10.2`, but I'm not sure if that could somehow solve it, as this version of `hardhat` doesn't bring any major changes.
@0xTimepunk How is it on your side?

**Comment by montyly** [comment]
@Bolee95 : it might be because of a cache issue in hardhat - it happens from time to time, where hardhat does not clean properly the compilation artefacts (despite slither providing a flag to do so)

**Comment by gretzke** [comment]
`npx hardhat clean` fixed the issue for me

**Comment by exd0tpy** [comment]
I got same issue on foundry project

I solved with this modification. This fix issue but all of the line number information will 0.

https://github.com/crytic/slither/issues/1313#issuecomment-1237920241
