### ISSUE TITLE
[Bug-Candidate]: Slither errors after install

### ISSUE THREAD

**Issue by Lokizzle** [crytic/slither#1363]
### Describe the issue:

Installed it mulitply times on Ubuntu, everytime the same outcome. 
NO matter if i use docker or not.
I´d really like to use slither. I´d appreciate to get some help. Maybe some of you faced the same problems.

When iḿ hitting this command: `slither .`
This is the output:
Error: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function/error definition.
 --> SmartDeposit.sol:8:1:
  |
8 | <!DOCTYPE html>
  | ^

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 544, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 658, in compile_all
    compilations.append(CryticCompile(filename, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 276, in _get_targets_json
    return _run_solc(
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 548, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function/error definition.
 --> SmartDeposit.sol:8:1:
  |
8 | <!DOCTYPE html>
  | ^

None
Error in .
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 544, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 658, in compile_all
    compilations.append(CryticCompile(filename, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 276, in _get_targets_json
    return _run_solc(
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 548, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Error: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function/error definition.
 --> SmartDeposit.sol:8:1:
  |
8 | <!DOCTYPE html>
  | ^

### Code example to reproduce the issue:

--

### Version:

Version: 0.8.3

**Comment by 0xalpharush** [comment]
This is an error from the solidity compiler, meaning your code doesn't compile: 
```
Invalid solc compilation Error: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function/error definition.
```
Try running `crytic-compile .` or the respective compilation command for your framework e.g. `hardhat build` or `forge build`. Then, address the errors until the code compiles. 

I'd also recommend installing `solc-select` as that using the wrong version of solidity could also be causing the code not to compile. https://github.com/crytic/solc-select

**Comment by Lokizzle** [comment]
Thank you, i just installed solc-slect.
Now this is the output 
test# `crytic-compile .`
INFO:CryticCompile:Compilation warnings/errors on ./SmartDeposit.sol:
Error: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function/error definition.
 --> SmartDeposit.sol:8:1:
  |
8 | <!DOCTYPE html>
  | ^


ERROR:CryticCompile:Invalid solc compilation Error: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function/error definition.
 --> SmartDeposit.sol:8:1:
  |
8 | <!DOCTYPE html>
  | ^

the coder told me to use the newest solc-version on this

**Comment by 0xalpharush** [comment]
Without seeing the code it's hard to say... It looks like there's something unexpected at the beginning of the file that needs to be removed i.e. your code should look like:
```
pragma solidity X.X.XX

contract Test {}
```
but may have something like:
```
DELETE_ME
pragma solidity X.X.XX

contract Test {}
```

**Comment by Lokizzle** [comment]
There wasnt anything like pragma solidy xxx

But just do get slither working now, i downloaded the hex.sol, which is a working code. But i get errors from slither.
This is the output of `crytic-compile hex.sol` 
test2# crytic-compile hex.sol 
INFO:CryticCompile:Compilation warnings/errors on hex.sol:
hex.sol:976:5: Error: Expected ';' but got '}'
    }
    ^

ERROR:CryticCompile:Invalid solc compilation hex.sol:976:5: Error: Expected ';' but got '}'
    }
    ^



and this one is the output from slither, which got the same error:
Compilation warnings/errors on hex.sol:
hex.sol:976:5: Error: Expected ';' but got '}'
    }
    ^

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 544, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 276, in _get_targets_json
    return _run_solc(
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 548, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation hex.sol:976:5: Error: Expected ';' but got '}'
    }
    ^

None
Error in hex.sol
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 544, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 154, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 276, in _get_targets_json
    return _run_solc(
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/solc.py", line 548, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation hex.sol:976:5: Error: Expected ';' but got '}'
    }
    ^

**Comment by Lokizzle** [comment]
[hex.txt](https://github.com/crytic/slither/files/9496894/hex.txt)

I uploaded the code in this txt file.

**Comment by elopez** [comment]
Hi @Lokizzle, it looks like the code you attached does not compile, you will need to fix that first.

```
INFO:CryticCompile:Compilation warnings/errors on hex.sol:
hex.sol:976:5: Error: Expected ';' but got '}'
}
```

```
    /**
     * @dev PUBLIC FACING: External helper for the current day number since launch time
     * @return Current day number (zero-based)
     */
    function currentDay()
        external
        view
        returns (uint256)
    {
        return _currentDay();_dailyDataCount // <- this line contains the compilation error
    }
```

**Comment by Lokizzle** [comment]
Hi there,

we created a new code, which is working fine. compiling was working also without errors.
But Slither makes this output:
# slither pit.sol 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/usr/local/lib/python3.10/dist-packages/slither/slither.py", line 123, in __init__
    parser.analyze_contracts()
  File "/usr/local/lib/python3.10/dist-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 499, in analyze_contracts
    self._compilation_unit.compute_storage_layout()
  File "/usr/local/lib/python3.10/dist-packages/slither/core/compilation_unit.py", line 257, in compute_storage_layout
    size, new_slot = var.type.storage_size
  File "/usr/local/lib/python3.10/dist-packages/slither/core/solidity_types/array_type.py", line 52, in storage_size
    return elem_size * int(self._length_value.value), True
ValueError: invalid literal for int() with base 10: '1e6'
None
Error in pit.sol
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/usr/local/lib/python3.10/dist-packages/slither/slither.py", line 123, in __init__
    parser.analyze_contracts()
  File "/usr/local/lib/python3.10/dist-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 499, in analyze_contracts
    self._compilation_unit.compute_storage_layout()
  File "/usr/local/lib/python3.10/dist-packages/slither/core/compilation_unit.py", line 257, in compute_storage_layout
    size, new_slot = var.type.storage_size
  File "/usr/local/lib/python3.10/dist-packages/slither/core/solidity_types/array_type.py", line 52, in storage_size
    return elem_size * int(self._length_value.value), True
ValueError: invalid literal for int() with base 10: '1e6'

**Comment by elopez** [comment]
Looks like there's an issue when the array sizes are expressed in scientific notation (`1e6`), I've created issue #1376 to track it. In the meantime, if you need a workaround you can replace `1e6` with `1000000` in your arrays and it should let you proceed.

**Comment by Lokizzle** [comment]
@elopez 

Thank you very much. that worked for me.
