### ISSUE TITLE
[Bug]: Slither fails with library events

### ISSUE THREAD

**Issue by yosriady** [crytic/slither#1407]
### Describe the issue:

Slither fails when given a contract which uses a library event. See minimal example below.

### Code example to reproduce the issue:

```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.16;

library Lib {
  event Event();
}

contract Test {
  function foo() external {
    emit Lib.Event(); // This line specifically
  }
}

```

### Version:

0.9.0

### Relevant log output:

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/site-packages/slither/__main__.py", line 97, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/site-packages/slither/__main__.py", line 75, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/usr/local/lib/python3.10/site-packages/slither/slither.py", line 130, in __init__
    parser.analyze_contracts()
  File "/usr/local/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 503, in analyze_contracts
    self._convert_to_slithir()
  File "/usr/local/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 688, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/usr/local/lib/python3.10/site-packages/slither/core/declarations/function.py", line 1705, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/usr/local/lib/python3.10/site-packages/slither/core/cfg/node.py", line 721, in slithir_generation
    self._find_read_write_call()
  File "/usr/local/lib/python3.10/site-packages/slither/core/cfg/node.py", line 919, in _find_read_write_call
    assert isinstance(ir.function, Function)
AssertionError
Error in contracts/Test.sol
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/site-packages/slither/__main__.py", line 97, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/site-packages/slither/__main__.py", line 75, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/usr/local/lib/python3.10/site-packages/slither/slither.py", line 130, in __init__
    parser.analyze_contracts()
  File "/usr/local/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 503, in analyze_contracts
    self._convert_to_slithir()
  File "/usr/local/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 688, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/usr/local/lib/python3.10/site-packages/slither/core/declarations/function.py", line 1705, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/usr/local/lib/python3.10/site-packages/slither/core/cfg/node.py", line 721, in slithir_generation
    self._find_read_write_call()
  File "/usr/local/lib/python3.10/site-packages/slither/core/cfg/node.py", line 919, in _find_read_write_call
    assert isinstance(ir.function, Function)
AssertionError
```

**Comment by altyni86** [comment]
any updates on this? Ran into the same issue...

**Comment by kristovatlas** [comment]
Same.
