### ISSUE TITLE
[Bug-Candidate]: Slither does not parse foundry.toml for "extra_output_files"

### ISSUE THREAD

**Issue by kristovatlas** [crytic/slither#1420]
### Describe the issue:

Specifying the `extra_output_files` config in the `foundry.toml` files causes slither to choke looking for `userdoc`

### Code example to reproduce the issue:

foundry.toml:
```
...snip...
extra_output_files = ["metadata", "abi"]
...snip...
```

### Version:

0.9.0

### Relevant log output:

```shell
% slither .
'forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force' running
Compiling 110 files with 0.8.16
Solc 0.8.16 finished in 7.35s
Compiler run successful (with warnings)
...snip...
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/homebrew/lib/python3.10/site-packages/slither/__main__.py", line 86, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/homebrew/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/homebrew/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 107, in compile
    userdoc = target_loaded.get("userdoc", {})
AttributeError: 'list' object has no attribute 'get'
Error in .
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/homebrew/lib/python3.10/site-packages/slither/__main__.py", line 86, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/homebrew/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/homebrew/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 107, in compile
    userdoc = target_loaded.get("userdoc", {})
AttributeError: 'list' object has no attribute 'get'
```

**Comment by elopez** [comment]
Hi @kristovatlas, thanks for the report! From the stacktrace, it looks like this is a crytic-compile issue, I will transfer it to the corresponding issue tracker.
