### ISSUE TITLE
[Bug-Candidate]: crytic compiler error when running slither on project with hardhat and foundry

### ISSUE THREAD

**Issue by daltyboy11** [crytic/slither#1446]
### Describe the issue:

I have a project that uses both hardhat and foundry and I am trying to run slither with foundry. From the root dir (where hardhat.config.ts and foundry.toml are located) I run this

```
slither . --config-file slither.config.json --compile-force-framework foundry
```

--compile-force-framework is necessary because without it slither defaults to 'npx hardhat compile --force'

And the output is is

```
'forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force' running
Compiling 109 files with 0.6.12
Compiling 13 files with 0.8.4
Compiling 124 files with 0.8.16
Solc 0.8.4 finished in 2.02s
Solc 0.8.16 finished in 6.28s
Solc 0.6.12 finished in 14.37s
Compiler run successful (with warnings)

// LONG LIST OF SOLC COMPILER WARNINGS REMOVED FOR BREVITY

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.0/libexec/lib/python3.10/site-packages/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.0/libexec/lib/python3.10/site-packages/slither/__main__.py", line 86, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 154, in compile
    version, optimized, runs = _get_config_info(self._target)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 239, in _get_config_info
    items_artifact = list(item["artifacts"].values())
AttributeError: 'list' object has no attribute 'values'
Error in .
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.0/libexec/lib/python3.10/site-packages/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.0/libexec/lib/python3.10/site-packages/slither/__main__.py", line 86, in process_all
    compilations = compile_all(target, **vars(args))
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 154, in compile
    version, optimized, runs = _get_config_info(self._target)
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.10/site-packages/crytic_compile/platform/foundry.py", line 239, in _get_config_info
    items_artifact = list(item["artifacts"].values())
AttributeError: 'list' object has no attribute 'values'
```

This looks like an error in the crytic compiler itself.

### Code example to reproduce the issue:

Command to run

```
slither . --config-file slither.config.json --compile-force-framework foundry
```

Slither config is taken from the [foundry docs](https://book.getfoundry.sh/config/static-analyzers#slither)
```
{
  "filter_paths": "lib",
  "solc_remaps": [
    "ds-test/=lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/"
  ]
}
```

foundry.toml
```
[profile.default]
auto_detect_solc = true
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 1
block_timestamp = 1
bytecode_hash = 'ipfs'
cache = true
cache_path = 'foundry-cache'
evm_version = 'london'
extra_output = []
extra_output_files = []
ffi = false
force = false
fuzz_max_global_rejects = 65536
fuzz_max_local_rejects = 1024
fuzz_runs = 256
gas_limit = 9223372036854775807
gas_reports = ['*']
ignored_error_codes = [1878]
initial_balance = '0xffffffffffffffffffffffff'
libraries = []
libs = ["node_modules", "lib"]
memory_limit = 33554432
names = false
no_storage_caching = false
offline = false
optimizer = true
optimizer_runs = 200
out = 'artifacts'
remappings = []
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
sizes = false
sparse_mode = false
src = 'contracts'
test = 'test'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
verbosity = 0
via_ir = false
match_path = "./contracts/test/*.sol"
fs_permissions = [{ access = "read", path = './artifacts' }, { access = "read", path = './contracts/test/fixtures' }]

[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'

[profile.mainnet-forking]
match_path = "./test/forge/mainnet/*.t.sol"
block_number = 15626901
fork_block_number = 15626901
```

### Version:

slither 0.9.0
forge 0.2.0 (cf3a551 2022-11-01T00:15:37.842452Z)

**Comment by 0xalpharush** [comment]
We chatted on Telegram. I believe this is blocked by https://github.com/foundry-rs/foundry/issues/3450

**Comment by 0xalpharush** [comment]
@daltyboy11 Would you see if the latest release solves this issue? Foundry is now prioritized over hardhat so you shouldn't need to override it any longer.
