### ISSUE TITLE
hardhat compilation throwing KeyError 

### ISSUE THREAD

**Issue by Fletch153** [crytic/slither#1464]
### Describe the issue:

Trying to compile my hardhat project and run slither is throwing an error. I've also tried pre-compiling it and using the skip compile option and still no luck. This happens on both on my machine and in the docker eth toolbox container provided by TOB.

### Code example to reproduce the issue:

slither . --hardhat-artifacts-directory ./build/artifacts

### Version:

slither: 0.8.3
crytic-compile: 0.2.3

### Relevant log output:

```shell
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 95, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 211, in parse_top_level_from_loaded_json
    contract.set_offset(top_level_data["src"], self._compilation_unit)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/source_mapping/source_mapping.py", line 124, in set_offset
    self._source_mapping = self._convert_source_mapping(offset, compilation_unit)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/source_mapping/source_mapping.py", line 102, in _convert_source_mapping
    compilation_unit, filename, s, l
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/source_mapping/source_mapping.py", line 44, in _compute_line
    filename, start + length
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 291, in get_line_from_offset
    return lines_delimiters[offset]
KeyError: 15985
None
Error in .
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 87, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 70, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 95, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 211, in parse_top_level_from_loaded_json
    contract.set_offset(top_level_data["src"], self._compilation_unit)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/source_mapping/source_mapping.py", line 124, in set_offset
    self._source_mapping = self._convert_source_mapping(offset, compilation_unit)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/source_mapping/source_mapping.py", line 102, in _convert_source_mapping
    compilation_unit, filename, s, l
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/source_mapping/source_mapping.py", line 44, in _compute_line
    filename, start + length
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 291, in get_line_from_offset
    return lines_delimiters[offset]
KeyError: 15985

```
```

**Comment by elopez** [comment]
Hi @Fletch153, can you confirm if this also happens after running `hardhat clean`?

**Comment by Fletch153** [comment]
@elopez it does, i've tried a fresh install and still no luck

**Comment by elopez** [comment]
Is the project public? If you can share a link to it, it'll help to find the root cause.

**Comment by Fletch153** [comment]
Unfortunately, it's not open source, which makes it tricky. Is there anything I can do or provide?

**Comment by plotchy** [comment]
Likely related to https://github.com/crytic/crytic-compile/issues/285

**Comment by 0xalpharush** [comment]
@Fletch153 Can you install the latest slither and post the output of `slither-doctor .`?

**Comment by 0xalpharush** [comment]
@Fletch153 Please try the latest release and comment any issues you run into
