### ISSUE TITLE
slither-read-storage: add support for `slither.core.solidity_types.array_type.ArrayType`

### ISSUE THREAD

**Issue by backulinivan** [crytic/slither#1615]
### Describe the desired feature

Add support for `ArrayType`. Please see minimal code and relevant log output.

### Version
0.9.1

### Minimal code to reproduce the issue
```solidity
pragma solidity ^0.8.0;

contract TestArrayType {
    struct Checkpoint {
        uint32 _blockNumber;
        uint224 _value;
    }

    struct History {
        Checkpoint[] _checkpoints;
    }

    History private _totalCheckpoints;
}

```

then `slither-read-storage TestArrayType.sol`

### Relevant log output

```
INFO:Slither-read-storage:
Contract 'TestArrayType'
TestArrayType._totalCheckpoints with type TestArrayType.History is located at slot: 0

INFO:Slither-read-storage:
Name: _totalCheckpoints
Type: TestArrayType.History
Slot: 0

INFO:Slither-read-storage:
Contract 'TestArrayType'
TestArrayType._totalCheckpoints with type TestArrayType.History is located at slot: 0

INFO:Slither-read-storage:<class 'slither.core.solidity_types.array_type.ArrayType'> is current not implemented in _find_struct_var_slot
Traceback (most recent call last):
  File "/home/ivan/anaconda3/bin/slither-read-storage", line 8, in <module>
    sys.exit(main())
  File "/home/ivan/anaconda3/lib/python3.9/site-packages/slither/tools/read_storage/__main__.py", line 153, in main
    srs.get_storage_layout()
  File "/home/ivan/anaconda3/lib/python3.9/site-packages/slither/tools/read_storage/read_storage.py", line 117, in get_storage_layout
    tmp[var.name].elems = self._all_struct_slots(var, type_.type, contract)
  File "/home/ivan/anaconda3/lib/python3.9/site-packages/slither/tools/read_storage/read_storage.py", line 550, in _all_struct_slots
    info = self.get_storage_slot(
  File "/home/ivan/anaconda3/lib/python3.9/site-packages/slither/tools/read_storage/read_storage.py", line 183, in get_storage_slot
    info, type_to, slot, size, offset = self._find_struct_var_slot(elems, slot, struct_var)
  File "/home/ivan/anaconda3/lib/python3.9/site-packages/slither/tools/read_storage/read_storage.py", line 312, in _find_struct_var_slot
    return info, type_to, slot_as_bytes, size, offset
UnboundLocalError: local variable 'size' referenced before assignment
```

**Comment by 0xalpharush** [comment]
Was just about to open an issue myself. We also need to support mapping with array values `mapping(x => array[])`
