### ISSUE TITLE
slither fails for specific brownie projects

### ISSUE THREAD

**Issue by UsmannK** [crytic/slither#1616]
I'm think this is actually a bug in brownie, but I'm not sure.

Brownie doesn't output compilation artifacts for some solidity files. For example, a helper file that only has some free functions. When slither is crawling file imports, it looks for the helper file's compilation artifact and then doesn't find it, so it crashes. 

Example repo where slither crashes: https://github.com/UsmannK/slither-brownie-test

Test.sol
```
import { magic_number } from "./Helper.sol";

contract Test {
    function test() public pure returns (uint256) {
        return magic_number();
    }
}
```

Helper.sol
```solidity
function magic_number() pure returns (uint256) {
    return 0xdeadbeef;
}
```

Output

```
$ slither .         
Brownie v1.19.2 - Python development framework for Ethereum

Project has been compiled. Build artifacts saved at /Users/usmannkhan/Development/brownie-test/build/contracts

Traceback (most recent call last):
  File "/Users/usmannkhan/.pyenv/versions/3.10.7/lib/python3.10/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/usmannkhan/.pyenv/versions/3.10.7/lib/python3.10/site-packages/slither/__main__.py", line 98, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Users/usmannkhan/.pyenv/versions/3.10.7/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Users/usmannkhan/.pyenv/versions/3.10.7/lib/python3.10/site-packages/slither/slither.py", line 112, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/Users/usmannkhan/.pyenv/versions/3.10.7/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 281, in parse_top_level_from_loaded_json
    get_imported_scope = self.compilation_unit.get_scope(import_directive.filename)
  File "/Users/usmannkhan/.pyenv/versions/3.10.7/lib/python3.10/site-packages/slither/core/compilation_unit.py", line 243, in get_scope
    filename = self._crytic_compile_compilation_unit.crytic_compile.filename_lookup(
  File "/Users/usmannkhan/.pyenv/versions/3.10.7/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 182, in filename_lookup
    raise ValueError(f"{filename} does not exist")
ValueError: contracts/Helper.sol does not exist
Error in .
Traceback (most recent call last):
  File "/Users/usmannkhan/.pyenv/versions/3.10.7/lib/python3.10/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/usmannkhan/.pyenv/versions/3.10.7/lib/python3.10/site-packages/slither/__main__.py", line 98, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Users/usmannkhan/.pyenv/versions/3.10.7/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Users/usmannkhan/.pyenv/versions/3.10.7/lib/python3.10/site-packages/slither/slither.py", line 112, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/Users/usmannkhan/.pyenv/versions/3.10.7/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 281, in parse_top_level_from_loaded_json
    get_imported_scope = self.compilation_unit.get_scope(import_directive.filename)
  File "/Users/usmannkhan/.pyenv/versions/3.10.7/lib/python3.10/site-packages/slither/core/compilation_unit.py", line 243, in get_scope
    filename = self._crytic_compile_compilation_unit.crytic_compile.filename_lookup(
  File "/Users/usmannkhan/.pyenv/versions/3.10.7/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 182, in filename_lookup
    raise ValueError(f"{filename} does not exist")
ValueError: contracts/Helper.sol does not exist
```

**Comment by UsmannK** [comment]
You can see brownie only makes an artifact for the main file

```bash
$ find build
build
build/contracts
build/contracts/Test.json
build/interfaces
build/deployments
```

Test.json
```json
{
  "abi": [
    {
      "inputs": [],
      "name": "test",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    }
  ],
  "allSourcePaths": {
    "1": "contracts/Test.sol"
  },
  "ast": {
    "absolutePath": "contracts/Test.sol",
    "exportedSymbols": {
      "Test": [
        13
      ],
      "magic_number": [
        22
      ]
    },
    "id": 14,
    "license": "UNLICENSED",
    "nodeType": "SourceUnit",
    "nodes": [
      {
        "id": 1,
        "literals": [
          "solidity",
          "0.8",
          ".14"
        ],
        "nodeType": "PragmaDirective",
        "src": "40:23:1"
      },
      {
        "absolutePath": "contracts/Helper.sol",
        "file": "./Helper.sol",
        "id": 3,
        "nameLocation": "-1:-1:-1",
        "nodeType": "ImportDirective",
        "scope": 14,
        "sourceUnit": 23,
        "src": "65:44:1",
        "symbolAliases": [
          {
            "foreign": {
              "id": 2,
              "name": "magic_number",
              "nodeType": "Identifier",
              "overloadedDeclarations": [],
              "referencedDeclaration": 22,
              "src": "74:12:1",
              "typeDescriptions": {}
            },
            "nameLocation": "-1:-1:-1"
          }
        ],
        "unitAlias": ""
      },
      {
        "abstract": false,
        "baseContracts": [],
        "canonicalName": "Test",
        "contractDependencies": [],
        "contractKind": "contract",
        "fullyImplemented": true,
        "id": 13,
        "linearizedBaseContracts": [
          13
        ],
        "name": "Test",
        "nameLocation": "120:4:1",
        "nodeType": "ContractDefinition",
        "nodes": [
          {
            "body": {
              "id": 11,
              "nodeType": "Block",
              "src": "177:38:1",
              "statements": [
                {
                  "expression": {
                    "arguments": [],
                    "expression": {
                      "argumentTypes": [],
                      "id": 8,
                      "name": "magic_number",
                      "nodeType": "Identifier",
                      "overloadedDeclarations": [],
                      "referencedDeclaration": 22,
                      "src": "194:12:1",
                      "typeDescriptions": {
                        "typeIdentifier": "t_function_internal_pure$__$returns$_t_uint256_$",
                        "typeString": "function () pure returns (uint256)"
                      }
                    },
                    "id": 9,
                    "isConstant": false,
                    "isLValue": false,
                    "isPure": false,
                    "kind": "functionCall",
                    "lValueRequested": false,
                    "names": [],
                    "nodeType": "FunctionCall",
                    "src": "194:14:1",
                    "tryCall": false,
                    "typeDescriptions": {
                      "typeIdentifier": "t_uint256",
                      "typeString": "uint256"
                    }
                  },
                  "functionReturnParameters": 7,
                  "id": 10,
                  "nodeType": "Return",
                  "src": "187:21:1"
                }
              ]
            },
            "functionSelector": "f8a8fd6d",
            "id": 12,
            "implemented": true,
            "kind": "function",
            "modifiers": [],
            "name": "test",
            "nameLocation": "140:4:1",
            "nodeType": "FunctionDefinition",
            "parameters": {
              "id": 4,
              "nodeType": "ParameterList",
              "parameters": [],
              "src": "144:2:1"
            },
            "returnParameters": {
              "id": 7,
              "nodeType": "ParameterList",
              "parameters": [
                {
                  "constant": false,
                  "id": 6,
                  "mutability": "mutable",
                  "name": "",
                  "nameLocation": "-1:-1:-1",
                  "nodeType": "VariableDeclaration",
                  "scope": 12,
                  "src": "168:7:1",
                  "stateVariable": false,
                  "storageLocation": "default",
                  "typeDescriptions": {
                    "typeIdentifier": "t_uint256",
                    "typeString": "uint256"
                  },
                  "typeName": {
                    "id": 5,
                    "name": "uint256",
                    "nodeType": "ElementaryTypeName",
                    "src": "168:7:1",
                    "typeDescriptions": {
                      "typeIdentifier": "t_uint256",
                      "typeString": "uint256"
                    }
                  },
                  "visibility": "internal"
                }
              ],
              "src": "167:9:1"
            },
            "scope": 13,
            "src": "131:84:1",
            "stateMutability": "pure",
            "virtual": false,
            "visibility": "public"
          }
        ],
        "scope": 14,
        "src": "111:106:1",
        "usedErrors": []
      }
    ],
    "src": "40:177:1"
  },
  "bytecode": "6080604052348015600f57600080fd5b50607a80601d6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063f8a8fd6d14602d575b600080fd5b63deadbeef60405190815260200160405180910390f3fea26469706673582212205cb59ffe96a4a1c14ab4cf983cb9c8caf36b770baec45e120b1a58918f262c0f64736f6c634300080e0033",
  "bytecodeSha1": "8f1231338eee127eb0ed53f4f44b323aa22f096a",
  "compiler": {
    "evm_version": "istanbul",
    "optimizer": {
      "enabled": true,
      "runs": 200
    },
    "version": "0.8.14+commit.80d49f37"
  },
  "contractName": "Test",
  "coverageMap": {
    "branches": {
      "1": {}
    },
    "statements": {
      "1": {}
    }
  },
  "dependencies": [],
  "deployedBytecode": "6080604052348015600f57600080fd5b506004361060285760003560e01c8063f8a8fd6d14602d575b600080fd5b63deadbeef60405190815260200160405180910390f3fea26469706673582212205cb59ffe96a4a1c14ab4cf983cb9c8caf36b770baec45e120b1a58918f262c0f64736f6c634300080e0033",
  "deployedSourceMap": "111:106:1:-:0;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;131:84;60:10:0;131:84:1;;160:25:2;;;148:2;133:18;131:84:1;;;;;;",
  "language": "Solidity",
  "natspec": {
    "kind": "dev",
    "methods": {},
    "version": 1
  },
  "offset": [
    111,
    217
  ],
  "opcodes": "PUSH1 0x80 PUSH1 0x40 MSTORE CALLVALUE DUP1 ISZERO PUSH1 0xF JUMPI PUSH1 0x0 DUP1 REVERT JUMPDEST POP PUSH1 0x4 CALLDATASIZE LT PUSH1 0x28 JUMPI PUSH1 0x0 CALLDATALOAD PUSH1 0xE0 SHR DUP1 PUSH4 0xF8A8FD6D EQ PUSH1 0x2D JUMPI JUMPDEST PUSH1 0x0 DUP1 REVERT JUMPDEST PUSH4 0xDEADBEEF PUSH1 0x40 MLOAD SWAP1 DUP2 MSTORE PUSH1 0x20 ADD PUSH1 0x40 MLOAD DUP1 SWAP2 SUB SWAP1 RETURN INVALID LOG2 PUSH5 0x6970667358 0x22 SLT KECCAK256 0x5C 0xB5 SWAP16 INVALID SWAP7 LOG4 LOG1 0xC1 0x4A 0xB4 0xCF SWAP9 EXTCODECOPY 0xB9 0xC8 0xCA RETURN PUSH12 0x770BAEC45E120B1A58918F26 0x2C 0xF PUSH5 0x736F6C6343 STOP ADDMOD 0xE STOP CALLER ",
  "pcMap": {
    "0": {
      "offset": [
        111,
        217
      ],
      "op": "PUSH1",
      "path": "1",
      "value": "0x80"
    },
    "2": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "PUSH1",
      "path": "1",
      "value": "0x40"
    },
    "4": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "MSTORE",
      "path": "1"
    },
    "5": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "CALLVALUE",
      "path": "1"
    },
    "6": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "DUP1",
      "path": "1"
    },
    "7": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "ISZERO",
      "path": "1"
    },
    "8": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "PUSH1",
      "path": "1",
      "value": "0xF"
    },
    "10": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "JUMPI",
      "path": "1"
    },
    "11": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "PUSH1",
      "path": "1",
      "value": "0x0"
    },
    "13": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "DUP1",
      "path": "1"
    },
    "14": {
      "dev": "Cannot send ether to nonpayable function",
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "REVERT",
      "path": "1"
    },
    "15": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "JUMPDEST",
      "path": "1"
    },
    "16": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "POP",
      "path": "1"
    },
    "17": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "PUSH1",
      "path": "1",
      "value": "0x4"
    },
    "19": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "CALLDATASIZE",
      "path": "1"
    },
    "20": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "LT",
      "path": "1"
    },
    "21": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "PUSH1",
      "path": "1",
      "value": "0x28"
    },
    "23": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "JUMPI",
      "path": "1"
    },
    "24": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "PUSH1",
      "path": "1",
      "value": "0x0"
    },
    "26": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "CALLDATALOAD",
      "path": "1"
    },
    "27": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "PUSH1",
      "path": "1",
      "value": "0xE0"
    },
    "29": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "SHR",
      "path": "1"
    },
    "30": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "DUP1",
      "path": "1"
    },
    "31": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "PUSH4",
      "path": "1",
      "value": "0xF8A8FD6D"
    },
    "36": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "EQ",
      "path": "1"
    },
    "37": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "PUSH1",
      "path": "1",
      "value": "0x2D"
    },
    "39": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "JUMPI",
      "path": "1"
    },
    "40": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "JUMPDEST",
      "path": "1"
    },
    "41": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "PUSH1",
      "path": "1",
      "value": "0x0"
    },
    "43": {
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "DUP1",
      "path": "1"
    },
    "44": {
      "first_revert": true,
      "fn": null,
      "offset": [
        111,
        217
      ],
      "op": "REVERT",
      "path": "1"
    },
    "45": {
      "fn": "Test.test",
      "offset": [
        131,
        215
      ],
      "op": "JUMPDEST",
      "path": "1"
    },
    "46": {
      "op": "PUSH4",
      "value": "0xDEADBEEF"
    },
    "51": {
      "fn": "Test.test",
      "offset": [
        131,
        215
      ],
      "op": "PUSH1",
      "path": "1",
      "value": "0x40"
    },
    "53": {
      "fn": "Test.test",
      "offset": [
        131,
        215
      ],
      "op": "MLOAD",
      "path": "1"
    },
    "54": {
      "op": "SWAP1"
    },
    "55": {
      "op": "DUP2"
    },
    "56": {
      "op": "MSTORE"
    },
    "57": {
      "op": "PUSH1",
      "value": "0x20"
    },
    "59": {
      "op": "ADD"
    },
    "60": {
      "fn": "Test.test",
      "offset": [
        131,
        215
      ],
      "op": "PUSH1",
      "path": "1",
      "value": "0x40"
    },
    "62": {
      "fn": "Test.test",
      "offset": [
        131,
        215
      ],
      "op": "MLOAD",
      "path": "1"
    },
    "63": {
      "fn": "Test.test",
      "offset": [
        131,
        215
      ],
      "op": "DUP1",
      "path": "1"
    },
    "64": {
      "fn": "Test.test",
      "offset": [
        131,
        215
      ],
      "op": "SWAP2",
      "path": "1"
    },
    "65": {
      "fn": "Test.test",
      "offset": [
        131,
        215
      ],
      "op": "SUB",
      "path": "1"
    },
    "66": {
      "fn": "Test.test",
      "offset": [
        131,
        215
      ],
      "op": "SWAP1",
      "path": "1"
    },
    "67": {
      "fn": "Test.test",
      "offset": [
        131,
        215
      ],
      "op": "RETURN",
      "path": "1"
    }
  },
  "sha1": "58f5983350b2b6d5afa8d3905780f0e0526e047d",
  "source": "// SPDX-License-Identifier: UNLICENSED\n\npragma solidity 0.8.14;\n\nimport { magic_number } from \"./Helper.sol\";\n\ncontract Test {\n    function test() public pure returns (uint256) {\n        return magic_number();\n    }\n}",
  "sourceMap": "111:106:1:-:0;;;;;;;;;;;;;;;;;;;",
  "sourcePath": "contracts/Test.sol",
  "type": "contract"
}
```

**Comment by UsmannK** [comment]
Brownie does in fact inline the artifact.

**Comment by 0xalpharush** [comment]
This may be related to https://github.com/eth-brownie/brownie/issues/941 Will look into it and if there's not a work around/ fix, we'll update the list of platform limitations https://github.com/crytic/crytic-compile/issues/267

**Comment by qingkaishi** [comment]
The same issue when I use `slither .` to compile [notional-v2](https://github.com/notional-finance/contracts-v2).
