### ISSUE TITLE
Unresolved reference to identifier

### ISSUE THREAD

**Issue by milseg** [crytic/slither#1647]
### Describe the issue:
When trying to run slither against chainlink it has not been able to process the code raising the exception given in the described output log
 
### Code example to reproduce the issue:
Currently chainlink **develop** branch
https://github.com/smartcontractkit/chainlink/tree/47572a63f7253b8a9ef600ec27647b26a23814e4/contracts

1. Clone chainlink
`git clone https://github.com/smartcontractkit/chainlink.git`

2. cd to its contracts folder
`cd chainlink/contracts`

3. remove old chainlink smart contract versions
`rm -r src/v0.4 && rm -r src/v0.5`

4. run slither
`slither . --filter-paths "tests|dev" --compile-force-framework hardhat`

### Version:
0.9.2

### Relevant log output:
 ```Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.9/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/kali/.local/lib/python3.9/site-packages/slither/__main__.py", line 98, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/kali/.local/lib/python3.9/site-packages/slither/__main__.py", line 76, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/kali/.local/lib/python3.9/site-packages/slither/slither.py", line 133, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/home/kali/.local/lib/python3.9/site-packages/slither/slither.py", line 143, in _init_parsing_and_analyses
    raise e
  File "/home/kali/.local/lib/python3.9/site-packages/slither/slither.py", line 139, in _init_parsing_and_analyses
    parser.parse_contracts()
  File "/home/kali/.local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 519, in parse_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "/home/kali/.local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 629, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "/home/kali/.local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 728, in _analyze_variables_modifiers_functions
    contract.analyze_content_functions()
  File "/home/kali/.local/lib/python3.9/site-packages/slither/solc_parsing/declarations/contract.py", line 416, in analyze_content_functions
    function_parser.analyze_content()
  File "/home/kali/.local/lib/python3.9/site-packages/slither/solc_parsing/declarations/function.py", line 312, in analyze_content
    node_parser.analyze_expressions()
  File "/home/kali/.local/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 332, in analyze_expressions
    node.analyze_expressions()
  File "/home/kali/.local/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 65, in analyze_expressions
    expression = parse_yul(self._scope, self, self._unparsed_expression)
  File "/home/kali/.local/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 857, in parse_yul
    op: Expression = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/home/kali/.local/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 702, in parse_yul_function_call
    args = [parse_yul(root, node, arg) for arg in ast["arguments"]]
  File "/home/kali/.local/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 702, in <listcomp>
    args = [parse_yul(root, node, arg) for arg in ast["arguments"]]
  File "/home/kali/.local/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 857, in parse_yul
    op: Expression = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/home/kali/.local/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 819, in parse_yul_identifier
    raise SlitherException(f"unresolved reference to identifier {name}")
slither.exceptions.SlitherException: unresolved reference to identifier GAS_FOR_CALL_EXACT_CHECK
Error:
unresolved reference to identifier GAS_FOR_CALL_EXACT_CHECK
Please report an issue to https://github.com/crytic/slither/issues```

**Comment by smonicas** [comment]
Thanks for the report. This issue is the same as #1610 and should be fixed in the next release.
