### ISSUE TITLE
[Bug-Candidate]:  KeyError: 'name' while using --print call-graph

### ISSUE THREAD

**Issue by thorthedev** [crytic/slither#1675]
### Describe the issue:

When calling --print call-graph the following error is shown:

Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.8/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.8/site-packages/slither/__main__.py", line 98, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.8/site-packages/slither/__main__.py", line 76, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.8/site-packages/slither/slither.py", line 112, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/home/ethsec/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 206, in parse_top_level_from_loaded_json
    if data_loaded[self.get_key()] == "root":
KeyError: 'name'

### Code example to reproduce the issue:

https://arbiscan.io/address/0x330b0AaC13E389313e48f9B70E4d1531C71A5094#readContract

### Version:

0.9.2

### Relevant log output:

```shell
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.8/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.8/site-packages/slither/__main__.py", line 98, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.8/site-packages/slither/__main__.py", line 76, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.8/site-packages/slither/slither.py", line 112, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/home/ethsec/.local/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 206, in parse_top_level_from_loaded_json
    if data_loaded[self.get_key()] == "root":
KeyError: 'name'
```

**Comment by thorthedev** [comment]
Looks like some problem with arbiscan API here.

**Comment by smonicas** [comment]
Yes it's the arbiscan API which has problems. Try https://api.arbiscan.io/api?module=contract&action=getsourcecode&address=0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9 you will see it returns an unknown exception. While for etherscan it works https://api.etherscan.io/api?module=contract&action=getsourcecode&address=0xBB9bc244D798123fDe783fCc1C72d3Bb8C189413

**Comment by 0xalpharush** [comment]
Do we need to do anything for this or it's not something we can fix?

**Comment by smonicas** [comment]
It was due to arbiscan API. We can report an error when the source code is empty instead of crashing but it's already tracked in #1801 so we can close this one.
