### ISSUE TITLE
[Bug-Candidate]: TypeError in solc_parsing/declarations/contract.py, line 775, in _handle_comment

### ISSUE THREAD

**Issue by duckki** [crytic/slither#1677]
### Describe the issue:

Certain comments cause the solc_parsing to crash.
It appears to happen with Solidity 0.6 and 0.5, but not with 0.7 and 0.8.

### Code example to reproduce the issue:

// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.5.0;

/**
 * @dev text
 */
contract Test {
}

### Version:

0.9.2

### Relevant log output:

```shell
% SOLC_VERSION=0.5.17 slither test.sol
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 98, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 76, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/opt/homebrew/lib/python3.9/site-packages/slither/slither.py", line 112, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 222, in parse_top_level_from_loaded_json
    contract_parser = ContractSolc(self, contract, top_level_data)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/declarations/contract.py", line 69, in __init__
    self._handle_comment(self._data)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/declarations/contract.py", line 775, in _handle_comment
    candidates = attributes["documentation"]["text"].replace("\n", ",").split(",")
TypeError: string indices must be integers
```

**Comment by 0xalpharush** [comment]
Closed by https://github.com/crytic/slither/pull/1734
