### ISSUE TITLE
Unresolved reference to identifier _BITMASK_ADDRESS

### ISSUE THREAD

**Issue by floranguyen0** [crytic/slither#1703]
### Describe the issue:

```
'npx hardhat clean' running (wd: /Users/hoanguyen/Documents/Programming/linum/rabble/Rabble_chain)
'npx hardhat clean --global' running (wd: /Users/hoanguyen/Documents/Programming/linum/rabble/Rabble_chain)
'npx hardhat compile --force' running
Compiling 29 files with 0.8.13
Generating typings for: 30 artifacts in dir: typechain-types for target: ethers-v5
Successfully generated 53 typings!
Solidity compilation finished successfully
✅ Generated documentation for 30 contracts

Solidity 0.8.13 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/reference/solidity-support


Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 98, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/slither.py", line 133, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/slither.py", line 143, in _init_parsing_and_analyses
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/slither.py", line 139, in _init_parsing_and_analyses
    parser.parse_contracts()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 519, in parse_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 629, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 728, in _analyze_variables_modifiers_functions
    contract.analyze_content_functions()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/declarations/contract.py", line 416, in analyze_content_functions
    function_parser.analyze_content()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/declarations/function.py", line 312, in analyze_content
    node_parser.analyze_expressions()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/yul/parse_yul.py", line 332, in analyze_expressions
    node.analyze_expressions()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/yul/parse_yul.py", line 65, in analyze_expressions
    expression = parse_yul(self._scope, self, self._unparsed_expression)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/yul/parse_yul.py", line 857, in parse_yul
    op: Expression = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/yul/parse_yul.py", line 698, in parse_yul_assignment
    return _parse_yul_assignment_common(root, node, ast, "variableNames")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/yul/parse_yul.py", line 676, in _parse_yul_assignment_common
    rhs = parse_yul(root, node, ast["value"])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/yul/parse_yul.py", line 857, in parse_yul
    op: Expression = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/yul/parse_yul.py", line 702, in parse_yul_function_call
    args = [parse_yul(root, node, arg) for arg in ast["arguments"]]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/yul/parse_yul.py", line 702, in <listcomp>
    args = [parse_yul(root, node, arg) for arg in ast["arguments"]]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/yul/parse_yul.py", line 857, in parse_yul
    op: Expression = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slither/solc_parsing/yul/parse_yul.py", line 819, in parse_yul_identifier
    raise SlitherException(f"unresolved reference to identifier {name}")
slither.exceptions.SlitherException: unresolved reference to identifier _BITMASK_ADDRESS
Error:
unresolved reference to identifier _BITMASK_ADDRESS
Please report an issue to https://github.com/crytic/slither/issues```

### Code example to reproduce the issue:

Unfortunately I can't share the code as it is in a private repo

### Version:

0.9.2

### Relevant log output:

_No response_

**Comment by floranguyen0** [comment]
Hm I ended up installing slither version 0.9.1 and it's fixed

```
pip3 install slither-analyzer==0.9.1
```
