### ISSUE TITLE
[Bug-Candidate]: Fix etherscan CI test

### ISSUE THREAD

**Issue by bsamuels453** [crytic/slither#1718]
### Describe the issue:

The Etherscan CI test is broken. It uses Rinkeby test net for the second test, but Rinkeby is discontinued.

To repro: `./scripts/ci_test_etherscan.sh`

### Code example to reproduce the issue:

`./scripts/ci_test_etherscan.sh`

### Version:

0.9.2

### Relevant log output:

```shell
urllib.error.HTTPError: HTTP Error 404: Not Found
Error in rinkeby:0xFe05820C5A92D9bc906D4A46F662dbeba794d3b7
Traceback (most recent call last):
  File "/Users/bsamuels/.pyenv/versions/3.8.13/envs/slitherdev/lib/python3.8/site-packages/slither/__main__.py", line 840, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/bsamuels/.pyenv/versions/3.8.13/envs/slitherdev/lib/python3.8/site-packages/slither/__main__.py", line 93, in process_all
    compilations = compile_all(target, **vars(args))
  File "/Users/bsamuels/.pyenv/versions/3.8.13/envs/slitherdev/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/Users/bsamuels/.pyenv/versions/3.8.13/envs/slitherdev/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/Users/bsamuels/.pyenv/versions/3.8.13/envs/slitherdev/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/Users/bsamuels/.pyenv/versions/3.8.13/envs/slitherdev/lib/python3.8/site-packages/crytic_compile/platform/etherscan.py", line 272, in compile
    with urllib.request.urlopen(etherscan_url) as response:
  File "/Users/bsamuels/.pyenv/versions/3.8.13/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/bsamuels/.pyenv/versions/3.8.13/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/bsamuels/.pyenv/versions/3.8.13/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Users/bsamuels/.pyenv/versions/3.8.13/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Users/bsamuels/.pyenv/versions/3.8.13/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/bsamuels/.pyenv/versions/3.8.13/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by montyly** [comment]
Fixed with https://github.com/crytic/slither/pull/1723
