### ISSUE TITLE
[Bug-Candidate]: KeyError in get_line_from_offset

### ISSUE THREAD

**Issue by charlesxsh** [crytic/slither#1721]
### Describe the issue:

When I am trying to print some info by using slither on seadrop, an exception happened.

### Code example to reproduce the issue:

https://github.com/ProjectOpenSea/seadrop

### Version:

0.9.2

### Relevant log output:

```shell
'npx hardhat clean' running (wd: /home/szx5097/code/PrCatch/temp/seadrop)
'npx hardhat clean --global' running (wd: /home/szx5097/code/PrCatch/temp/seadrop)
'npx hardhat compile --force' running
Downloading compiler 0.8.17
Generating typings for: 36 artifacts in dir: typechain-types for target: ethers-v5
Successfully generated 112 typings!
Compiled 37 Solidity files successfully

Solidity 0.8.17 is not fully supported yet. You can still use Hardhat, but some features, like stack traces, might not work correctly.

Learn more at https://hardhat.org/hardhat-runner/docs/reference/solidity-support
Traceback (most recent call last):
  File "../.venv/lib/python3.10/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "../.venv/lib/python3.10/site-packages/slither/__main__.py", line 98, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "../.venv/lib/python3.10/site-packages/slither/__main__.py", line 76, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "../.venv/lib/python3.10/site-packages/slither/slither.py", line 112, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "../.venv/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 225, in parse_top_level_from_loaded_json
    contract.set_offset(top_level_data["src"], self._compilation_unit)
  File "../.venv/lib/python3.10/site-packages/slither/core/source_mapping/source_mapping.py", line 184, in set_offset
    self.source_mapping = _convert_source_mapping(offset, compilation_unit)
  File "../.venv/lib/python3.10/site-packages/slither/core/source_mapping/source_mapping.py", line 150, in _convert_source_mapping
    (lines, starting_column, ending_column) = _compute_line(compilation_unit, filename, s, l)
  File "../.venv/lib/python3.10/site-packages/slither/core/source_mapping/source_mapping.py", line 111, in _compute_line
    end_line, ending_column = compilation_unit.core.crytic_compile.get_line_from_offset(
  File "../.venv/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 272, in get_line_from_offset
    return lines_delimiters[offset]
KeyError: 9522
```
```

**Comment by 0xalpharush** [comment]
What command did you run?

**Comment by charlesxsh** [comment]
> What command did you run?

Just simple slither . --print human-summary
