### ISSUE TITLE
[Bug-Candidate]: Unknown Identifies: __BITMASK_ADDRESS

### ISSUE THREAD

**Issue by rachit2501** [crytic/slither#1729]
### Describe the issue:

running `slither .` on hardhat project breaks after successful compilation.

### Code example to reproduce the issue:

Its a hardhat project

### Version:

`0.9.2`

### Relevant log output:

```shell
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 834, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 98, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/__main__.py", line 76, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/opt/homebrew/lib/python3.9/site-packages/slither/slither.py", line 133, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/opt/homebrew/lib/python3.9/site-packages/slither/slither.py", line 143, in _init_parsing_and_analyses
    raise e
  File "/opt/homebrew/lib/python3.9/site-packages/slither/slither.py", line 139, in _init_parsing_and_analyses
    parser.parse_contracts()
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 519, in parse_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 629, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 728, in _analyze_variables_modifiers_functions
    contract.analyze_content_functions()
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/declarations/contract.py", line 416, in analyze_content_functions
    function_parser.analyze_content()
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/declarations/function.py", line 312, in analyze_content
    node_parser.analyze_expressions()
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 332, in analyze_expressions
    node.analyze_expressions()
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 65, in analyze_expressions
    expression = parse_yul(self._scope, self, self._unparsed_expression)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 857, in parse_yul
    op: Expression = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 698, in parse_yul_assignment
    return _parse_yul_assignment_common(root, node, ast, "variableNames")
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 676, in _parse_yul_assignment_common
    rhs = parse_yul(root, node, ast["value"])
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 857, in parse_yul
    op: Expression = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 702, in parse_yul_function_call
    args = [parse_yul(root, node, arg) for arg in ast["arguments"]]
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 702, in <listcomp>
    args = [parse_yul(root, node, arg) for arg in ast["arguments"]]
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 857, in parse_yul
    op: Expression = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/opt/homebrew/lib/python3.9/site-packages/slither/solc_parsing/yul/parse_yul.py", line 819, in parse_yul_identifier
    raise SlitherException(f"unresolved reference to identifier {name}")
slither.exceptions.SlitherException: unresolved reference to identifier _BITMASK_ADDRESS
Error:
unresolved reference to identifier _BITMASK_ADDRESS
```

**Comment by 0xalpharush** [comment]
Appreciate you taking the time to fill out a bug report! This issue is a duplicate of https://github.com/crytic/slither/issues/1610 so we will track it there. It will be fixed by https://github.com/crytic/slither/pull/1611 in the upcoming release

**Comment by Willyham** [comment]
Hey @0xalpharush, thanks for your work on this. Is there any chance you can cut the 0.9.3 release to fix this, or is there a workaround we can use in the meantime? Thanks
