### ISSUE TITLE
[Bug]: Infinite loop in SlitherCompilationUnitSolc._analyze_all_enums

### ISSUE THREAD

**Issue by romcyncynatus** [crytic/slither#1758]
### Describe the issue:

When analyzing certain contracts, for example, 0x757bc268bd50da88b2d0cf1966652b18e56ca803, an infinite loop in `SlitherCompilationUnitSolc._analyze_all_enums` is encountered. The `contracts_to_be_analyzed` list seems to contain only a single contract that is being added and removed repeatedly.

### Code example to reproduce the issue:

```
# https://etherscan.io/address/0x757bc268bd50da88b2d0cf1966652b18e56ca803
import slither
s = slither.Slither('0x757bc268bd50da88b2d0cf1966652b18e56ca803')
```

### Version:

0.9.2

### Relevant log output:

```shell
>>> import slither
>>> s = slither.Slither('0x757bc268bd50da88b2d0cf1966652b18e56ca803')
WARNING:CryticCompile:Warning: @uniswap/v2-core/contracts/interfaces/IUniswapV2Factory.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.

Warning: contracts/core/work/ContributionBoard.sol:390:5: Warning: Function state mutability can be restricted to view
    function _beforeTokenTransfer(
    ^ (Relevant source part starts here and spans across multiple lines).


^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rom/projects/smart-contracts-similarity/venv/lib/python3.10/site-packages/slither/slither.py", line 133, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/home/rom/projects/smart-contracts-similarity/venv/lib/python3.10/site-packages/slither/slither.py", line 139, in _init_parsing_and_analyses
    parser.parse_contracts()
  File "/home/rom/projects/smart-contracts-similarity/venv/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 496, in parse_contracts
    self._analyze_all_enums(contracts_to_be_analyzed)
  File "/home/rom/projects/smart-contracts-similarity/venv/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 542, in _analyze_all_enums
    for father in contract.underlying_contract.inheritance
  File "/home/rom/projects/smart-contracts-similarity/venv/lib/python3.10/site-packages/slither/solc_parsing/declarations/contract.py", line 92, in underlying_contract
    @property
KeyboardInterrupt
```

**Comment by 0xalpharush** [comment]
```
import {
    ERC20Burnable,
    ERC20 as _ERC20
} from "@openzeppelin/contracts/token/ERC20/ERC20Burnable.sol";

/**
 * @title Commit Token
 * @notice Commit Token is used for redeeming stable coins, buying crypto products
 *      from the village market and mining vision tokens. It is minted by the admin and
 *      given to the contributors. The amount of mintable token is limited to the balance
 *      of redeemable stable coins. Therefore, it's 1:1 pegged to the given stable coin
 *      or expected to have higher value than the redeemable coin values.
 */
contract ERC20 is ERC20Burnable {
```

**Comment by romcyncynatus** [comment]
Thanks for the prompt reply! Any quick way to at least avoid the infinite loop, and have an exception instead?

**Comment by Yhtiyar** [comment]
Facing the same problem when running slither on this repo: https://github.com/xdao-app/xdao-contracts 
There are no redefines of the imports. Could `using X for Y`  be causing the problem?

**Comment by 0xalpharush** [comment]
@Yhtiyar What version of slither are you running?

**Comment by Yhtiyar** [comment]
`0.9.6`
