### ISSUE TITLE
[Bug-Candidate]: slither's solc-json fails even though solc --standard-json compiles

### ISSUE THREAD

**Issue by JamJomJim** [crytic/slither#1940]
### Describe the issue:

I'm trying to use slither to generate security reports for https://www.cookbook.dev. We already have well formed standard solidity JSON available from previous compilations, so this seems like the best option to get slither analysis. 

With the attached JSON I can successfully compile using 
`solc ./contract.json --standard-json`

However when I use slither/crytic-compile, it fails
`slither .\contract.json --compile-force-framework solc-json`

This seems to fail in two places
1) crytic-compile seems to rely on actual files instead of directly using the standard json

```
(venv) PS C:\Users\James Ewens\Work\cookbook-security-scan> slither .\contract.json --compile-force-framework solc-json
Traceback (most recent call last):
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\slither\slither.py", line 103, in __init__
    crytic_compile = CryticCompile(target, **kwargs)
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\crytic_compile\crytic_compile.py", line 131, in __init__
    self._compile(**kwargs)
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\crytic_compile\crytic_compile.py", line 553, in _compile
    self._platform.compile(self, **kwargs)
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\crytic_compile\platform\solc_standard_json.py", line 434, in compile
    parse_standard_json_output(
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\crytic_compile\platform\solc_standard_json.py", line 276, in parse_standard_json_output
    filename = convert_filename(
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\crytic_compile\utils\naming.py", line 149, in convert_filename
    filename = _verify_filename_existence(filename, cwd)
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\crytic_compile\utils\naming.py", line 99, in _verify_filename_existence
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: @openzeppelin\contracts\access\Ownable.sol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\slither\__main__.py", line 824, in main_impl
    ) = process_single(filename, args, detector_classes, printer_classes)
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\slither\__main__.py", line 79, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\slither\slither.py", line 107, in __init__
    raise SlitherError(f"Invalid compilation: \n{str(e)}")
slither.exceptions.SlitherError: Invalid compilation:
Unknown file: @openzeppelin\contracts\access\Ownable.sol
ERROR:root:Error:
ERROR:root:Invalid compilation:
Unknown file: @openzeppelin\contracts\access\Ownable.sol
ERROR:root:Please report an issue to https://github.com/crytic/slither/issues
```

2) I've found that if I recreate the same file structure within the dir, I can get solc-json to work on a certain variety of standard json (flattened contract names). But clearly this is just a workaround on my end, and it fails with the attached JSON. This is the result on the attached JSON even when I've recreated the same file structure within my workspace.
```
(venv) PS C:\Users\James Ewens\Work\cookbook-security-scan> slither .\contract.json --compile-force-framework solc-json
Traceback (most recent call last):
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\slither\__main__.py", line 824, in main_impl
    ) = process_single(filename, args, detector_classes, printer_classes)
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\slither\__main__.py", line 79, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\slither\slither.py", line 114, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\slither\solc_parsing\slither_compilation_unit_solc.py", line 197, in parse_top_level_from_loaded_json
    if "nodeType" in data_loaded:
TypeError: argument of type 'NoneType' is not iterable
ERROR:root:Error in .\contract.json
ERROR:root:Traceback (most recent call last):
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\slither\__main__.py", line 824, in main_impl
    ) = process_single(filename, args, detector_classes, printer_classes)
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\slither\__main__.py", line 79, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\slither\slither.py", line 114, in __init__
    parser.parse_top_level_from_loaded_json(ast, path)
  File "C:\Users\James Ewens\Work\cookbook-security-scan\venv\lib\site-packages\slither\solc_parsing\slither_compilation_unit_solc.py", line 197, in parse_top_level_from_loaded_json
    if "nodeType" in data_loaded:
TypeError: argument of type 'NoneType' is not iterable
```

### Code example to reproduce the issue:

[contract.json.txt](https://github.com/crytic/slither/files/11569896/contract.json.txt)

### Version:

0.9.3

**Comment by 0xalpharush** [comment]
Slither does not support running on the artifact by itself
