### ISSUE TITLE
[Bug-Candidate]:  Unknown file: @openzeppelin/contractsxxx

### ISSUE THREAD

**Issue by INT2ECALL** [crytic/slither#1958]
### Describe the issue:

I got some errors when I try to run slither .

![image](https://github.com/crytic/slither/assets/91420400/f9eb070a-984b-4c7b-beef-c68960c87669)

my command is :
``` slither /immunefi/optimism/OptimismPortal/contracts/L1/OptimismPortal.sol --solc-args "--base-path /immunefi/optimism/OptimismPortal/contracts/ --include-path /immunefi/optimism/OptimismPortal/node_modules/"
```

errors :
```
Compilation warnings/errors on L1/OptimismPortal.sol:
Warning: Contract code size is 30294 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> L1/OptimismPortal.sol:23:1:
   |
23 | contract OptimismPortal is Initializable, ResourceMetering, Semver {
   | ^ (Relevant source part starts here and spans across multiple lines).


Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 165, in compile
    targets_json, skip_filename, compilation_unit, self._target, solc_working_dir
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 323, in solc_handle_contracts
    working_dir=solc_working_dir,
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/utils/naming.py", line 117, in convert_filename
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: @openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol
None
Error in L1/OptimismPortal.sol
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 637, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__
    self._compile(**kwargs)
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 548, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 165, in compile
    targets_json, skip_filename, compilation_unit, self._target, solc_working_dir
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 323, in solc_handle_contracts
    working_dir=solc_working_dir,
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/utils/naming.py", line 117, in convert_filename
    raise InvalidCompilation(f"Unknown file: {filename}")
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: @openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol
```

Is the option "--solc-args" work? It is ok when I use solc to compile the .sol file , but it is not ok for slither.
![image](https://github.com/crytic/slither/assets/91420400/67a8dc33-8ee3-449e-8420-0e4706fdb86d)

### Code example to reproduce the issue:

https://etherscan.io/address/0x28a55488fef40005309e2DA0040DbE9D300a64AB

### Version:

 slither 0.8.3

**Comment by INT2ECALL** [comment]
my command :

```
 slither L1/OptimismPortal.sol --solc-args "--base-path /immunefi/optimism/OptimismPortal/contracts/ --include-path /immunefi/optimism/OptimismPortal/node_modules/"
```

**Comment by 0xalpharush** [comment]
Did you obtain the source from github or etherscan? It worked when I ran the following using 0.9.3 (I got an unrelated bug in 0.8.3 that's presumably been fixed since then):
```
crytic-compile 0x28a55488fef40005309e2DA0040DbE9D300a64AB
cd crytic-export/etherscan-contracts/0x28a55488fef40005309e2DA0040DbE9D300a64AB-OptimismPortal/contracts
slither ./L1/OptimismPortal.sol --solc-args "--base-path /Users/alpharush/crytic-export/etherscan-contracts/0x28a55488fef40005309e2DA0040DbE9D300a64AB-OptimismPortal/contracts/ --include-path /Users/alpharush/crytic-export/etherscan-contracts/0x28a55488fef40005309e2DA0040DbE9D300a64AB-OptimismPortal/node_modules/"
```
