### ISSUE TITLE
[Bug-Candidate]: use default_factory

### ISSUE THREAD

**Issue by mimoo** [crytic/slither#2005]
### Describe the issue:

Getting the following error right after install when I try to use any command of slither:

```
Traceback (most recent call last):
  File "/usr/local/bin/slither", line 5, in <module>
    from slither.__main__ import main
  File "/usr/local/lib/python3.11/site-packages/slither/__main__.py", line 24, in <module>
    from slither.printers import all_printers
  File "/usr/local/lib/python3.11/site-packages/slither/printers/all_printers.py", line 4, in <module>
    from .summary.loc import LocPrinter
  File "/usr/local/lib/python3.11/site-packages/slither/printers/summary/loc.py", line 14, in <module>
    from slither.utils.loc import compute_loc_metrics
  File "/usr/local/lib/python3.11/site-packages/slither/utils/loc.py", line 20, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'slither.utils.loc.LoCInfo'> for field src is not allowed: use default_factory
```

### Code example to reproduce the issue:

```
$ pip3 --version
pip 23.1.2 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)
$ pip3 install slither-analyzer
$ slither --version
```

### Version:

I get the error when I run that

**Comment by 0xalpharush** [comment]
@mimoo We just release 0.9.5 to fix this!

Closed by https://github.com/crytic/slither/pull/2002
