### ISSUE TITLE
[Bug-Candidate]: Assertion failure in SSA generation

### ISSUE THREAD

**Issue by kevinclancy** [crytic/slither#2072]
### Describe the issue:

When I run slither on a small contract involving loops, conditionals, and reverts, an assertion in SSA generation fails.

### Code example to reproduce the issue:
```
contract Test {
    bool z;
    function test() external returns (uint256) {
        if (z) {
            for (;;) {
                revert("");
            }
            revert("");
        }
        revert("");
    }
}
```

### Version:

0.9.6

### Relevant log output:

```shell
ERROR:root:Traceback (most recent call last):
  File "/Users/kevin.clancy/.pyenv/versions/3.9.13/lib/python3.9/site-packages/slither/__main__.py", line 814, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/kevin.clancy/.pyenv/versions/3.9.13/lib/python3.9/site-packages/slither/__main__.py", line 102, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Users/kevin.clancy/.pyenv/versions/3.9.13/lib/python3.9/site-packages/slither/__main__.py", line 80, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Users/kevin.clancy/.pyenv/versions/3.9.13/lib/python3.9/site-packages/slither/slither.py", line 135, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/Users/kevin.clancy/.pyenv/versions/3.9.13/lib/python3.9/site-packages/slither/slither.py", line 155, in _init_parsing_and_analyses
    raise e
  File "/Users/kevin.clancy/.pyenv/versions/3.9.13/lib/python3.9/site-packages/slither/slither.py", line 151, in _init_parsing_and_analyses
    parser.analyze_contracts()
  File "/Users/kevin.clancy/.pyenv/versions/3.9.13/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 541, in analyze_contracts
    self._convert_to_slithir()
  File "/Users/kevin.clancy/.pyenv/versions/3.9.13/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 774, in _convert_to_slithir
    raise e
  File "/Users/kevin.clancy/.pyenv/versions/3.9.13/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 769, in _convert_to_slithir
    contract.convert_expression_to_slithir_ssa()
  File "/Users/kevin.clancy/.pyenv/versions/3.9.13/lib/python3.9/site-packages/slither/core/declarations/contract.py", line 1502, in convert_expression_to_slithir_ssa
    func.generate_slithir_ssa(all_ssa_state_variables_instances)
  File "/Users/kevin.clancy/.pyenv/versions/3.9.13/lib/python3.9/site-packages/slither/core/declarations/function_contract.py", line 134, in generate_slithir_ssa
    compute_dominance_frontier(self.nodes)
  File "/Users/kevin.clancy/.pyenv/versions/3.9.13/lib/python3.9/site-packages/slither/core/dominators/utils.py", line 98, in compute_dominance_frontier
    assert runner.immediate_dominator
AssertionError
```

**Comment by smonicas** [comment]
Probably same as #1973

**Comment by 0xalpharush** [comment]
Closed by https://github.com/crytic/slither/pull/1984
