### ISSUE TITLE
[Bug-Candidate]: running on prb-math repo throws ERROR:SlitherSolcParsing:Impossible to generate IR for top level function

### ISSUE THREAD

**Issue by waynehoover** [crytic/slither#2082]
### Describe the issue:

When running slither on a fresh checkout of the [prb-math repo](https://github.com/PaulRBerg/prb-math/tree/main) I get this error:
```
ERROR:SlitherSolcParsing:
Failed to generate IR for top level function intoUint40. Please open an issue https://github.com/crytic/slither/issues.
intoUint40 (src/ud2x18/Casting.sol#50-56):
 	xUint = UD2x18.unwrap(x)
	xUint > uint64(Common.MAX_UINT40)
	Errors.PRBMath_UD2x18_IntoUint40_Overflow(x)
	result = uint40(xUint)
```

### Code example to reproduce the issue:

❯ git clone git@github.com:PaulRBerg/prb-math.git
❯ cd prb-math
❯ slither .

### Version:

`0.9.6`

### Relevant log output:

```shell
❯ git clone git@github.com:PaulRBerg/prb-math.git
❯ cd prb-math
❯ slither .
'forge clean' running 
'forge build --build-info' running 
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function intoUD2x18 (src/sd1x18/Casting.sol#19-25):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function intoUD60x18 (src/sd1x18/Casting.sol#30-36):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function intoUint256 (src/sd1x18/Casting.sol#41-47):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function intoUint128 (src/sd1x18/Casting.sol#52-58):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function intoUint40 (src/sd1x18/Casting.sol#64-73):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function intoSD1x18 (src/sd59x18/Casting.sol#23-32):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function intoUD2x18 (src/sd59x18/Casting.sol#38-47):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function intoUD60x18 (src/sd59x18/Casting.sol#52-58):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function intoUint256 (src/sd59x18/Casting.sol#63-69):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function intoUint128 (src/sd59x18/Casting.sol#75-84):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function intoUint40 (src/sd59x18/Casting.sol#90-99):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function abs (src/sd59x18/Math.sol#32-38):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function ceil (src/sd59x18/Math.sol#81-100):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function div (src/sd59x18/Math.sol#121-150):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function exp (src/sd59x18/Math.sol#168-181):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function exp2 (src/sd59x18/Math.sol#201-227):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function floor (src/sd59x18/Math.sol#240-259):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function gm (src/sd59x18/Math.sol#283-307):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function log10 (src/sd59x18/Math.sol#363-459):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function log2 (src/sd59x18/Math.sol#484-533):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function mul (src/sd59x18/Math.sol#549-578):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function powu (src/sd59x18/Math.sol#640-671):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function sqrt (src/sd59x18/Math.sol#688-703):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:Impossible to generate IR for top level function intoSD1x18 (src/ud2x18/Casting.sol#15-21):
 'NoneType' object has no attribute 'functions'
ERROR:SlitherSolcParsing:
Failed to generate IR for top level function intoUint40. Please open an issue https://github.com/crytic/slither/issues.
intoUint40 (src/ud2x18/Casting.sol#50-56):
 	xUint = UD2x18.unwrap(x)
	xUint > uint64(Common.MAX_UINT40)
	Errors.PRBMath_UD2x18_IntoUint40_Overflow(x)
	result = uint40(xUint)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/__main__.py", line 814, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/__main__.py", line 102, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/__main__.py", line 80, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/slither.py", line 135, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/slither.py", line 155, in _init_parsing_and_analyses
    raise e
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/slither.py", line 151, in _init_parsing_and_analyses
    parser.analyze_contracts()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 541, in analyze_contracts
    self._convert_to_slithir()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 789, in _convert_to_slithir
    raise e
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 778, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/core/declarations/function.py", line 1760, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/core/cfg/node.py", line 706, in slithir_generation
    self._irs = convert_expression(expression, self)  # type:ignore
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/slithir/convert.py", line 118, in convert_expression
    result = apply_ir_heuristics(result, node)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/slithir/convert.py", line 1918, in apply_ir_heuristics
    find_references_origin(irs)
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/slithir/convert.py", line 1720, in find_references_origin
    ir.lvalue.points_to = ir.variable_left
    ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/slithir/variables/reference.py", line 49, in points_to
    assert is_valid_lvalue(points_to) or isinstance(
AssertionError
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/__main__.py", line 814, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/__main__.py", line 102, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/__main__.py", line 80, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/slither.py", line 135, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/slither.py", line 155, in _init_parsing_and_analyses
    raise e
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/slither.py", line 151, in _init_parsing_and_analyses
    parser.analyze_contracts()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 541, in analyze_contracts
    self._convert_to_slithir()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 789, in _convert_to_slithir
    raise e
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 778, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/core/declarations/function.py", line 1760, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/core/cfg/node.py", line 706, in slithir_generation
    self._irs = convert_expression(expression, self)  # type:ignore
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/slithir/convert.py", line 118, in convert_expression
    result = apply_ir_heuristics(result, node)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/slithir/convert.py", line 1918, in apply_ir_heuristics
    find_references_origin(irs)
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/slithir/convert.py", line 1720, in find_references_origin
    ir.lvalue.points_to = ir.variable_left
    ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.9.6/libexec/lib/python3.11/site-packages/slither/slithir/variables/reference.py", line 49, in points_to
    assert is_valid_lvalue(points_to) or isinstance(
AssertionError
```

**Comment by 0xalpharush** [comment]
Hi thanks for reporting this! We are tracking this issue here https://github.com/crytic/slither/issues/1989

**Comment by faizelmahomed** [comment]
Getting the same issue, any idea how to fix it :/
