### ISSUE TITLE
[Bug-Candidate]: Slither version conflict with rlp/web3.py libs

### ISSUE THREAD

**Issue by caiosabarros** [crytic/slither#2097]
### Describe the issue:

I have downloaded slither with no issues using the `pip3 install slither-analyzer`. But when trying to run it, I get the following error:

```
caiosa@Notebook:~/UDocuments/Github/Work/tester$ slither .
Traceback (most recent call last):
  File "/home/caiosa/.local/bin/slither", line 8, in <module>
    sys.exit(main())
  File "/home/caiosa/.local/lib/python3.8/site-packages/slither/__main__.py", line 708, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/home/caiosa/.local/lib/python3.8/site-packages/slither/__main__.py", line 722, in main_impl
    args = parse_args(all_detector_classes, all_printer_classes)
  File "/home/caiosa/.local/lib/python3.8/site-packages/slither/__main__.py", line 295, in parse_args
    version=require("slither-analyzer")[0].version,
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-utils 2.1.0 (/home/caiosa/.local/lib/python3.8/site-packages), Requirement.parse('eth-utils<2,>=1.0.2'), {'rlp'})
```
So, I run the following commands to install the eth-utils version that satisfies 'rlp':
```
pip3 uninstall eth-utils
pip3 install eth-utils==1.0.2
```
I then try to run slither again:
```
caiosa@Notebook:~/UDocuments/Github/Work/tester$ slither .
Traceback (most recent call last):
  File "/home/caiosa/.local/bin/slither", line 8, in <module>
    sys.exit(main())
  File "/home/caiosa/.local/lib/python3.8/site-packages/slither/__main__.py", line 708, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/home/caiosa/.local/lib/python3.8/site-packages/slither/__main__.py", line 722, in main_impl
    args = parse_args(all_detector_classes, all_printer_classes)
  File "/home/caiosa/.local/lib/python3.8/site-packages/slither/__main__.py", line 295, in parse_args
    version=require("slither-analyzer")[0].version,
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-utils 1.0.2 (/home/caiosa/.local/lib/python3.8/site-packages), Requirement.parse('eth-utils>=2.1.0'), {'slither-analyzer'})
```

Ubuntu version:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

$ pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

$ python3 --version
Python 3.8.10

Idk if it's an issue from my machine, if it's an slither issue or if it's an rlp issue...

Thanks guys!

### Code example to reproduce the issue:

None

### Version:

caiosa@Notebook:~/UDocuments/Github/Work/tester$ slither --version
Traceback (most recent call last):
  File "/home/caiosa/.local/bin/slither", line 8, in <module>
    sys.exit(main())
  File "/home/caiosa/.local/lib/python3.8/site-packages/slither/__main__.py", line 708, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/home/caiosa/.local/lib/python3.8/site-packages/slither/__main__.py", line 722, in main_impl
    args = parse_args(all_detector_classes, all_printer_classes)
  File "/home/caiosa/.local/lib/python3.8/site-packages/slither/__main__.py", line 295, in parse_args
    version=require("slither-analyzer")[0].version,
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-utils 1.0.2 (/home/caiosa/.local/lib/python3.8/site-packages), Requirement.parse('eth-utils>=2.1.0'), {'slither-analyzer'})

### Relevant log output:

```shell
Traceback (most recent call last):
  File "/home/caiosa/.local/bin/slither", line 8, in <module>
    sys.exit(main())
  File "/home/caiosa/.local/lib/python3.8/site-packages/slither/__main__.py", line 708, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/home/caiosa/.local/lib/python3.8/site-packages/slither/__main__.py", line 722, in main_impl
    args = parse_args(all_detector_classes, all_printer_classes)
  File "/home/caiosa/.local/lib/python3.8/site-packages/slither/__main__.py", line 295, in parse_args
    version=require("slither-analyzer")[0].version,
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-utils 1.0.2 (/home/caiosa/.local/lib/python3.8/site-packages), Requirement.parse('eth-utils>=2.1.0'), {'web3', 'slither-analyzer'})
```

**Comment by 0xalpharush** [comment]
It looks like these version requirements may be for an older version of slither so perhaps it would work if you reinstall the latest: `pip uninstall slither-analyzer && pip install slither-analyzer==0.9.6`. If that doesn't work it may be that another package unrelated to slither has conflicting version requirements. In that case, I'd recommend installing slither in a virtual environment (`python -m venv env && source ./env/bin/activate && pip install slither-analyzer==0.9.6`) or using https://pypa.github.io/pipx/
