### ISSUE TITLE
[Bug-Candidate]: crytic_compile.platform.exceptions.InvalidCompilation: Solidity version not found: 

### ISSUE THREAD

**Issue by enderphan94** [crytic/slither#2116]
### Describe the issue:

I tried to run slither on M2 (macos) but it returned an error 

### Code example to reproduce the issue:

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "[@openzeppelin/contracts/token/ERC20/ERC20.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.3/contracts/token/ERC20/ERC20.sol)";

contract MyToken is ERC20 {
    constructor() ERC20("MyToken", "MTK") {}
}

### Version:

0.6.13

### Relevant log output:

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.9/site-packages/slither/__main__.py", line 68, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 1019, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 123, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 930, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/platform/solc.py", line 107, in compile
    compiler="solc", version=get_version(solc), optimized=is_optimized(solc_arguments)
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/platform/solc.py", line 251, in get_version
    raise InvalidCompilation(f"Solidity version not found: {stdout}")
crytic_compile.platform.exceptions.InvalidCompilation: Solidity version not found: 
ERROR:root:None
ERROR:root:Error in AccessController.sol
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.9/site-packages/slither/__main__.py", line 68, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 1019, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 123, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 930, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/platform/solc.py", line 107, in compile
    compiler="solc", version=get_version(solc), optimized=is_optimized(solc_arguments)
  File "/usr/local/lib/python3.9/site-packages/crytic_compile/platform/solc.py", line 251, in get_version
    raise InvalidCompilation(f"Solidity version not found: {stdout}")
crytic_compile.platform.exceptions.InvalidCompilation: Solidity version not found:
```

**Comment by smonicas** [comment]
I'd suggest to use a more recent version of slither. The issue is saying that solc is missing, if you are using `solc-select` you can do `solc-select install 0.8.19 && solc-select use 0.8.19`. If you use a framework like foundry or hardhat you don't have to set the solc version with `slither .` from the root directory.

**Comment by enderphan94** [comment]
> I'd suggest to use a more recent version of slither. The issue is saying that solc is missing, if you are using `solc-select` you can do `solc-select install 0.8.19 && solc-select use 0.8.19`. If you use a framework like foundry or hardhat you don't have to set the solc version with `slither .` from the root directory.

Yes, I do use solc-select and I've installed an appropriate version.

**Comment by smonicas** [comment]
If you do `solc --version` you get solc 0.8.19 as output?

**Comment by enderphan94** [comment]
Got a new error

```
crytic_compile.platform.exceptions.InvalidCompilation: 
Solidity version not found:
STDOUT:

STDERR:
Traceback (most recent call last):
  File "/usr/local/bin/solc", line 8, in <module>
    sys.exit(solc())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/solc_select/__main__.py", line 91, in solc
    halt_old_architecture(path)
  File "/usr/local/lib/python3.11/site-packages/solc_select/solc_select.py", line 30, in halt_old_architecture
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: solc-select is out of date. Please run `solc-select upgrade
```

**Comment by 0xalpharush** [comment]
@0xicingdeath Do you have an idea how to troubleshoot this?

**Comment by 0xicingdeath** [comment]
@enderphan94 Can you share the output of `pip show solc-select`?

**Comment by enderphan94** [comment]
> pip show solc-select

```
Name: solc-select
Version: 0.2.0
Summary: Manage multiple Solidity compiler versions.
Home-page: https://github.com/crytic/solc-select
Author: Trail of Bits
Author-email: 
License: AGPL-3.0
Location: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Requires: 
Required-by: 
```

**Comment by elopez** [comment]
Looking at the error messages, it seems like slither, crytic-compile and solc-select are installed on Homebrew's Python (pip3); but you also have a separate, old solc-select installation on the macOS-bundled Python (pip). Could you try to uninstall the old version (`pip uninstall solc-select`) and give it another go at `solc-select upgrade`?

**Comment by enderphan94** [comment]
Okay, I fixed the issue by removing all old/wrong/alternative versions of the solc, slither, and solc-select (by using which to track its location). Then re-install everything via "pip" instead of "pip3" and it worked.
