### ISSUE TITLE
Error in reentrancy-eth

### ISSUE THREAD

**Issue by mrice32** [crytic/slither#214]
I didn't get a chance to dig into exactly what portion of our Solidity was causing this error, but this error started popping up in our CI without any changes in the Solidity, so I'm thinking this is due to some recent update in slither:

```
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 509, in main_impl
    (results, number_contracts) = process(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 53, in process
    return _process(slither, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 67, in _process
    detector_results = slither.run_detectors()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 153, in run_detectors
    results = [d.detect() for d in self._detectors]
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 153, in <listcomp>
    results = [d.detect() for d in self._detectors]
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/detectors/abstract_detector.py", line 105, in detect
    all_results = self._detect()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/detectors/reentrancy/reentrancy_eth.py", line 79, in _detect
    super()._detect()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/detectors/reentrancy/reentrancy.py", line 202, in _detect
    self.detect_reentrancy(c)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/detectors/reentrancy/reentrancy.py", line 188, in detect_reentrancy
    self._explore(function.entry_point, [])
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/detectors/reentrancy/reentrancy.py", line 179, in _explore
    self._explore(son, visited)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/detectors/reentrancy/reentrancy.py", line 157, in _explore
    if self._can_callback(node.irs + slithir_operations):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/detectors/reentrancy/reentrancy.py", line 64, in _can_callback
    if not ir.function.all_high_level_calls():
AttributeError: 'NoneType' object has no attribute 'all_high_level_calls'

Exited with code 255
```

**Comment by Xenomega** [comment]
Hello @mrice32 . I can look into fixing this for you.

Would you be able to share the version of your codebase which is causing this issue, along with the Solidity version used? I've just tested the latest slither on `master` of https://github.com/UMAprotocol/protocol without encountering this error. I also tested the 0.6.3 release of slither without issue.

**Comment by montyly** [comment]
Hi @mrice32, are you able to reproduce the error? If so, what branch should we try?

**Comment by mrice32** [comment]
Sorry to be slow in getting back. I re-enabled the detector, and the issue seems to have been fixed since we last ran it.
