### ISSUE TITLE
[Bug-Candidate]: Support ternary operator in value initializers

### ISSUE THREAD

**Issue by CodeSandwich** [crytic/slither#2145]
### Describe the issue:

The ternary operator doesn't work when initializing values outside of functions. The example consists of 3 kinds of values being initialized and each of them crashes Slither.

### Code example to reproduce the issue:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

contract Ternary {
    uint256 public constant MAX_C = 2 > 1 ? 2 : 1;
    uint256 public maxS = 2 > 1 ? 2 : 1;
    uint256 public immutable maxI = 2 > 1 ? 2 : 1;
}
```

### Version:

0.9.5

### Relevant log output:

```shell
ERROR:SlitherSolcParsing:
Failed to generate IR for Ternary.slitherConstructorVariables. Please open an issue https://github.com/crytic/slither/issues.
Ternary.slitherConstructorVariables (src/Pass.sol#4-8):
        maxS = if 2 > 1 then 2 else 1
        maxI = if 2 > 1 then 2 else 1
Traceback (most recent call last):
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/__main__.py", line 814, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/__main__.py", line 102, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/__main__.py", line 80, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/slither.py", line 135, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/slither.py", line 155, in _init_parsing_and_analyses
    raise e
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/slither.py", line 151, in _init_parsing_and_analyses
    parser.analyze_contracts()
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 541, in analyze_contracts
    self._convert_to_slithir()
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 767, in _convert_to_slithir
    raise e
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 752, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/core/declarations/function.py", line 1760, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/core/cfg/node.py", line 706, in slithir_generation
    self._irs = convert_expression(expression, self)  # type:ignore
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/slithir/convert.py", line 115, in convert_expression
    visitor = ExpressionToSlithIR(expression, node)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/visitors/slithir/expression_to_slithir.py", line 162, in __init__
    self._visit_expression(self.expression)
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/visitors/expression/expression.py", line 43, in _visit_expression
    self._visit_assignement_operation(expression)
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/visitors/expression/expression.py", line 99, in _visit_assignement_operation
    self._visit_expression(expression.expression_right)
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/visitors/expression/expression.py", line 93, in _visit_expression
    self._post_visit(expression)
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/visitors/expression/expression.py", line 276, in _post_visit
    self._post_conditional_expression(expression)
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/visitors/slithir/expression_to_slithir.py", line 393, in _post_conditional_expression
    raise Exception(f"Ternary operator are not convertible to SlithIR {expression}")
Exception: Ternary operator are not convertible to SlithIR if 2 > 1 then 2 else 1
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/__main__.py", line 814, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/__main__.py", line 102, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/__main__.py", line 80, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/slither.py", line 135, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/slither.py", line 155, in _init_parsing_and_analyses
    raise e
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/slither.py", line 151, in _init_parsing_and_analyses
    parser.analyze_contracts()
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 541, in analyze_contracts
    self._convert_to_slithir()
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 767, in _convert_to_slithir
    raise e
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 752, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/core/declarations/function.py", line 1760, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/core/cfg/node.py", line 706, in slithir_generation
    self._irs = convert_expression(expression, self)  # type:ignore
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/slithir/convert.py", line 115, in convert_expression
    visitor = ExpressionToSlithIR(expression, node)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/visitors/slithir/expression_to_slithir.py", line 162, in __init__
    self._visit_expression(self.expression)
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/visitors/expression/expression.py", line 43, in _visit_expression
    self._visit_assignement_operation(expression)
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/visitors/expression/expression.py", line 99, in _visit_assignement_operation
    self._visit_expression(expression.expression_right)
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/visitors/expression/expression.py", line 93, in _visit_expression
    self._post_visit(expression)
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/visitors/expression/expression.py", line 276, in _post_visit
    self._post_conditional_expression(expression)
  File "/home/zuczek/.local/lib/python3.11/site-packages/slither/visitors/slithir/expression_to_slithir.py", line 393, in _post_conditional_expression
    raise Exception(f"Ternary operator are not convertible to SlithIR {expression}")
Exception: Ternary operator are not convertible to SlithIR if 2 > 1 then 2 else 1
```

**Comment by 0xalpharush** [comment]
This is a duplicate of https://github.com/crytic/slither/issues/634

**Comment by CodeSandwich** [comment]
That's fair, I'll add the note about immutables and constants being affected as much as the storage variables.
