### ISSUE TITLE
[Bug-Candidate]: sh: 1: hardhat: Permission denied

### ISSUE THREAD

**Issue by C0D3O** [crytic/slither#2218]
### Describe the issue:

can't run slither on Ubuntu 22

### Code example to reproduce the issue:

run slither .

### Version:

0.10.0

### Relevant log output:

```shell
slither .
'npx hardhat clean' running (wd: /root/Coding/nextgen)
'npx' returned non-zero exit code 126
sh: 1: hardhat: Permission denied
'npx hardhat clean --global' running (wd: /root/Coding/nextgen)
'npx' returned non-zero exit code 126
sh: 1: hardhat: Permission denied
Problem executing hardhat: sh: 1: hardhat: Permission denied

'npx hardhat compile --force' running (wd: /root/Coding/nextgen)
'npx' returned non-zero exit code 126
sh: 1: hardhat: Permission denied
Traceback (most recent call last):
  File "/usr/local/bin/slither", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 727, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 833, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.10/dist-packages/slither/__main__.py", line 96, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 718, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 207, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/crytic_compile.py", line 629, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/hardhat.py", line 183, in compile
    hardhat_like_parsing(crytic_compile, self._target, build_directory, hardhat_working_dir)
  File "/usr/local/lib/python3.10/dist-packages/crytic_compile/platform/hardhat.py", line 52, in hardhat_like_parsing
    raise InvalidCompilation(txt)
crytic_compile.platform.exceptions.InvalidCompilation: Compilation failed. Can you run build command?
/root/Coding/nextgen/artifacts/build-info is not a directory.
root@moneyDevPC:~/Coding/nextgen#
```

**Comment by C0D3O** [comment]
sudo chown -R $USER /usr/local

And
cd /path/of/project

chmod -R a+x .
