### ISSUE TITLE
[Bug-Candidate]: Slither installed but running through issues

### ISSUE THREAD

**Issue by souilos** [crytic/slither#2271]
### Describe the issue:

I can run `slither .` however I have issues that seems related to python.
I have a mac and have installed python and slither with brew.
`brew install python3` and `brew install slither-analyzer`.

### Code example to reproduce the issue:

while running `slither .`

`
Compiling 16 files with 0.7.6
stdout: Solc 0.7.6 finished in 14.74ms
Error: 
stderr: Compiler run failed:
stderr: Error (2837): Only state variables or file-level variables can have a docstring.
stderr:         uint256 winnerIndex =
stderr:                 ^---------^
Traceback (most recent call last):
  File "/usr/local/bin/slither", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/Cellar/slither-analyzer/0.10.0_1/libexec/lib/python3.12/site-packages/slither/__main__.py", line 727, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/usr/local/Cellar/slither-analyzer/0.10.0_1/libexec/lib/python3.12/site-packages/slither/__main__.py", line 833, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/slither-analyzer/0.10.0_1/libexec/lib/python3.12/site-packages/slither/__main__.py", line 96, in process_all
    compilations = compile_all(target, **vars(args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/opt/crytic-compile/libexec/lib/python3.12/site-packages/crytic_compile/crytic_compile.py", line 718, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/opt/crytic-compile/libexec/lib/python3.12/site-packages/crytic_compile/crytic_compile.py", line 207, in __init__
    self._compile(**kwargs)
  File "/usr/local/opt/crytic-compile/libexec/lib/python3.12/site-packages/crytic_compile/crytic_compile.py", line 629, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/opt/crytic-compile/libexec/lib/python3.12/site-packages/crytic_compile/platform/foundry.py", line 86, in compile
    hardhat_like_parsing(crytic_compile, self._target, build_directory, self._target)
  File "/usr/local/opt/crytic-compile/libexec/lib/python3.12/site-packages/crytic_compile/platform/hardhat.py", line 52, in hardhat_like_parsing
    raise InvalidCompilation(txt)
crytic_compile.platform.exceptions.InvalidCompilation: Compilation failed. Can you run build command?
out/build-info is not a directory.
`

### Version:

0.10.0

**Comment by souilos** [comment]
I have added a bunch of comments aka /// @audit blabla in my code and it was the issue....
