### ISSUE TITLE
[question] module not found error when running

### ISSUE THREAD

**Issue by TheSnakeWitcher** [crytic/slither#2272]
Hi, When I try to run slither even `slither --help` i get the following error

```
Traceback (most recent call last):
  File "/usr/bin/slither", line 33, in <module>
    sys.exit(load_entry_point('slither-analyzer==0.9.6', 'console_scripts', 'slither')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/slither", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/slither/__init__.py", line 4, in <module>
    from .slither import Slither
  File "/usr/lib/python3.11/site-packages/slither/slither.py", line 4, in <module>
    from crytic_compile import CryticCompile, InvalidCompilation
ModuleNotFoundError: No module named 'crytic_compile'
```

I would like to know if these could be that I'm missing something or if it could be a packaging error. I am on archlinux, I already check the packaging and it seems to run the command of the README(clone repo and `python setup.py install` ). Thanks in advanced.

**Comment by elopez** [comment]
Hi! It looks like somehow, crytic-compile did not get installed when you installed Slither. It's odd since it's a direct dependency of Slither. Please try re-installing with `pip install .`

**Comment by TheSnakeWitcher** [comment]
I can't do that because the host packages are managed by the host package manager(pacman) so I can't use pip outside a virtual environment 😢 . I created a package and install separately `crytic-compile`, now the errors is these.

```
Traceback (most recent call last):
  File "/usr/bin/slither", line 33, in <module>
    sys.exit(load_entry_point('slither-analyzer==0.9.6', 'console_scripts', 'slither')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/slither", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/slither/__init__.py", line 4, in <module>
    from .slither import Slither
  File "/usr/lib/python3.11/site-packages/slither/slither.py", line 4, in <module>
    from crytic_compile import CryticCompile, InvalidCompilation
  File "/usr/lib/python3.11/site-packages/crytic_compile/__init__.py", line 4, in <module>
    from .crytic_compile import CryticCompile, compile_all, is_supported
  File "/usr/lib/python3.11/site-packages/crytic_compile/crytic_compile.py", line 17, in <module>
    from solc_select.solc_select import (
ModuleNotFoundError: No module named 'solc_select'
```

Exactly the same error but now the module is `solc_select` which I don't see in the dependencies. I  assume that the error is related to the packaging.
I think that now that at least the `crytic-compile` module is found the cause could be some missing operations. The packaging used in `slither` is equivalent to run the following script in the project dir after a `git clone`.

```sh
python setup.py build -j$(nproc)
python setup.py install --root="${pkgdir}/" --optimize=1 --skip-build
```

Any insigths are welcome and thanks again

**Comment by TheSnakeWitcher** [comment]
Here the list of scripts that i get after install slither, in case that could be helpful
- slither
- slither-check-erc
- slither-check-kspec
- slither-check-upgradeability
- slither-doctor
- slither-documentation
- slither-find-paths
- slither-flat
- slither-format
- slither-interface
- slither-mutate
- slither-prop
- slither-read-storage
- slither-simil

**Comment by elopez** [comment]
Just for reference, `solc-select` is a dependency of `crytic-compile`, so you're still not getting all the dependencies installed 😅 : https://github.com/crytic/crytic-compile/blob/master/setup.py#L17

If you're installing by yourself, you should probably _not_ be using `setup.py install` as root either, if you want to keep the host packages managed solely by your package manager. Besides, I believe the installation of python packages via `setup.py install` is considered deprecated. Consider using a `venv` or `pip install --user .` instead, to install just for your current user. We should probably update our README as well.

Are you by chance trying to install slither with this PKGBUILD from AUR? https://aur.archlinux.org/packages/slither
It seems to be incomplete; it declares almost no dependencies, while [Arch's documentation says you need to](https://wiki.archlinux.org/title/Python_package_guidelines#Installation_methods) add dependencies for each of the package's dependencies. We're not the authors of that PKGBUILD, please reach out to them if that's the case so that they can look into fixing it 👍 

> Note: Dependencies from the package's metadata must be defined in the depends array otherwise they will not be installed.

**Comment by TheSnakeWitcher** [comment]
Yes, I am trying to install slither with that AUR package. That's what I was looking for, to check if the error was something weird with the installation or with the packaging. Thanks again for the feedback 👍🏿
