### ISSUE TITLE
Invalid solc compilation 

### ISSUE THREAD

**Issue by joeldeleep** [crytic/slither#2287]
### Describe the issue:

Running `slither .` on the project folder was successful. However, if I use any of the tools like slither-flat or slither-check-upgradeability against the contract, it produces the evm compilation error.

Command used: `slither-flat src/File.sol`
The contract uses compiler 0.8.13

This is a foundry project and toml file is mentioned below

**foundry.toml**
```toml
[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.13"

remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
```

**EVM compilation error running slither tool**

```
Traceback (most recent call last):
  File "/Users/joeldeleep/Library/Python/3.9/lib/python/site-packages/crytic_compile/platform/solc.py", line 582, in _run_solc
    ret: Dict = json.loads(stdout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joeldeleep/Library/Python/3.9/lib/python/site-packages/slither/slither.py", line 97, in __init__
    crytic_compile = CryticCompile(target, **kwargs)
  File "/Users/joeldeleep/Library/Python/3.9/lib/python/site-packages/crytic_compile/crytic_compile.py", line 207, in __init__
    self._compile(**kwargs)
  File "/Users/joeldeleep/Library/Python/3.9/lib/python/site-packages/crytic_compile/crytic_compile.py", line 629, in _compile
    self._platform.compile(self, **kwargs)
  File "/Users/joeldeleep/Library/Python/3.9/lib/python/site-packages/crytic_compile/platform/solc.py", line 151, in compile
    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)
  File "/Users/joeldeleep/Library/Python/3.9/lib/python/site-packages/crytic_compile/platform/solc.py", line 280, in _get_targets_json
    return _run_solc(
  File "/Users/joeldeleep/Library/Python/3.9/lib/python/site-packages/crytic_compile/platform/solc.py", line 586, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Invalid option for --evm-version: paris


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joeldeleep/Library/Python/3.9/bin//slither-flat", line 8, in <module>
    sys.exit(main())
  File "/Users/joeldeleep/Library/Python/3.9/lib/python/site-packages/slither/tools/flattening/__main__.py", line 112, in main
    slither = Slither(args.filename, **vars(args))
  File "/Users/joeldeleep/Library/Python/3.9/lib/python/site-packages/slither/slither.py", line 101, in __init__
    raise SlitherError(f"Invalid compilation: \n{str(e)}")
slither.exceptions.SlitherError: Invalid compilation:
Invalid solc compilation Invalid option for --evm-version: paris
```

### Code example to reproduce the issue:

{confidential}

### Version:

0.10.0

**Comment by joeldeleep** [comment]
Initially, the toml file was not having Paris, I added it when I saw the same error `Invalid solc compilation Invalid option for --evm-version: paris` without Paris in toml file. 

It is working with evm London, however , If the EVM version is not specified, by default it should use London right ?
