### ISSUE TITLE
[Bug-Candidate]: `KeyError: 7468` after fixing report

### ISSUE THREAD

**Issue by mds1** [crytic/slither#2296]
### Describe the issue:

Slither generated the following finding:
```
DisputeGameFactory.findLatestGames(GameType,uint256,uint256) (src/dispute/DisputeGameFactory.sol#137-185) contains a tautology or contradiction:
        - i >= 0 && i <= _start (src/dispute/DisputeGameFactory.sol#157)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#tautology-or-contradiction
```

Since `i` is a uint256, I removed the `i >= 0` condition. Running slither again then causes it to crash with `KeyError: 7468`

### Code example to reproduce the issue:

To reproduce:
1. Clone `https://github.com/ethereum-optimism/optimism` and checkout the `ci/slither` branch
2. `cd packages/contracts-bedrock` and `forge install`
3. Run `slither .` to get the finding
4. Delete `i >= 0 &&` to get error

### Version:

0.10.0

### Relevant log output:

```shell
$ slither .
'forge clean' running (wd: /Users/mds/Documents/projects/ethereum-optimism/optimism/packages/contracts-bedrock)
'forge build --build-info --skip */test/** */scripts/** --force' running (wd: /Users/mds/Documents/projects/ethereum-optimism/optimism/packages/contracts-bedrock)
Traceback (most recent call last):
  File "/opt/homebrew/bin/slither", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.10.0_1/libexec/lib/python3.12/site-packages/slither/__main__.py", line 727, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/opt/homebrew/Cellar/slither-analyzer/0.10.0_1/libexec/lib/python3.12/site-packages/slither/__main__.py", line 833, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.10.0_1/libexec/lib/python3.12/site-packages/slither/__main__.py", line 107, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.10.0_1/libexec/lib/python3.12/site-packages/slither/__main__.py", line 80, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.10.0_1/libexec/lib/python3.12/site-packages/slither/slither.py", line 118, in __init__
    sol_parser.parse_top_level_items(ast, path)
  File "/opt/homebrew/Cellar/slither-analyzer/0.10.0_1/libexec/lib/python3.12/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 233, in parse_top_level_items
    contract.set_offset(top_level_data["src"], self._compilation_unit)
  File "/opt/homebrew/Cellar/slither-analyzer/0.10.0_1/libexec/lib/python3.12/site-packages/slither/core/source_mapping/source_mapping.py", line 199, in set_offset
    self.source_mapping = _convert_source_mapping(offset, compilation_unit)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.10.0_1/libexec/lib/python3.12/site-packages/slither/core/source_mapping/source_mapping.py", line 171, in _convert_source_mapping
    (lines, starting_column, ending_column) = _compute_line(compilation_unit, filename, s, l)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/slither-analyzer/0.10.0_1/libexec/lib/python3.12/site-packages/slither/core/source_mapping/source_mapping.py", line 132, in _compute_line
    end_line, ending_column = compilation_unit.core.crytic_compile.get_line_from_offset(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/opt/crytic-compile/libexec/lib/python3.12/site-packages/crytic_compile/crytic_compile.py", line 368, in get_line_from_offset
    return lines_delimiters[offset]
           ~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 7468
```

**Comment by 0xalpharush** [comment]
Usually this happens when the file on disk changes but the compiler output is from the old version. We are running `forge clean` and `forge build` with `--force`, but the artifact's `content` for the DisputeGame still seems to contain `i >= 0 &&` after editing the contract and rerunning. Could you confirm by running `find ./artifacts/build-info -name "*.json" -exec grep "i >= 0 &&" {} \;`? I think the detection of which file is dirty and what needs to be updated in `artifacts/build-info` may have a bug in ethers-rs or foundry-compilers. If I run `rm -rf ./artifacts` after editing the contract, I don't get a `KeyError`

**Comment by 0xalpharush** [comment]
I made a PR to fix this, too https://github.com/gakonst/ethers-rs/pull/2730

**Comment by mds1** [comment]
Confirmed that removing the `artifacts` dir resolves the error, thanks! Since these fixes are already being upstreamed to foundry I'll close this now
