### ISSUE TITLE
[Bug-Candidate]: Fail to scan in a project that supports both Hardhat and Foundry

### ISSUE THREAD

**Issue by 0xmichalis** [crytic/slither#2316]
### Describe the issue:

We have a [project](https://github.com/ToucanProtocol/contracts) where we use Hardhat and Foundry in parallel. It seems that when Slither detects a `foundry.toml` file in the project and the Slither config specifies that compilation should be ignored, then if Slither does not find build artifacts produced by Foundry it will fail, although there may be build artifacts by Hardhat. Ideally Slither detects the Hardhat artifacts, or there is a way for us to trigger Slither to look for the Hardhat artifacts.

### Code example to reproduce the issue:

```
git clone https://github.com/ToucanProtocol/contracts
cd contracts
yarn
yarn hardhat compile
slither .
```

### Version:

0.8.3

### Relevant log output:

```shell
$ slither .
--ignore-compile used, if something goes wrong, consider removing the ignore compile flag
Traceback (most recent call last):
  File "/home/michalis/.local/lib/python3.9/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/michalis/.local/lib/python3.9/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 643, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 131, in __init__
    self._compile(**kwargs)
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 553, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/platform/foundry.py", line 90, in compile
    hardhat_like_parsing(crytic_compile, self._target, build_directory, self._target)
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/platform/hardhat.py", line 49, in hardhat_like_parsing
    os.listdir(build_directory), key=lambda x: os.path.getmtime(Path(build_directory, x))
FileNotFoundError: [Errno 2] No such file or directory: 'out/build-info'
None
Error in .
Traceback (most recent call last):
  File "/home/michalis/.local/lib/python3.9/site-packages/slither/__main__.py", line 744, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/michalis/.local/lib/python3.9/site-packages/slither/__main__.py", line 76, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 643, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 131, in __init__
    self._compile(**kwargs)
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 553, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/platform/foundry.py", line 90, in compile
    hardhat_like_parsing(crytic_compile, self._target, build_directory, self._target)
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/platform/hardhat.py", line 49, in hardhat_like_parsing
    os.listdir(build_directory), key=lambda x: os.path.getmtime(Path(build_directory, x))
FileNotFoundError: [Errno 2] No such file or directory: 'out/build-info'
```

**Comment by 0xalpharush** [comment]
Hi please upgrade to the latest slither version 0.10.0 as the foundry compilation is more robust. Let me know if that doesn't fix the issue

**Comment by 0xmichalis** [comment]
@0xalpharush it looks like the issue persists in 0.10.0
```
$ slither .
--ignore-compile used, if something goes wrong, consider removing the ignore compile flag
Traceback (most recent call last):
  File "/home/michalis/.local/bin/slither", line 8, in <module>
    sys.exit(main())
  File "/home/michalis/.local/lib/python3.9/site-packages/slither/__main__.py", line 727, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/home/michalis/.local/lib/python3.9/site-packages/slither/__main__.py", line 833, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/michalis/.local/lib/python3.9/site-packages/slither/__main__.py", line 96, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 718, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 207, in __init__
    self._compile(**kwargs)
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 629, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/platform/foundry.py", line 86, in compile
    hardhat_like_parsing(crytic_compile, self._target, build_directory, self._target)
  File "/home/michalis/.local/lib/python3.9/site-packages/crytic_compile/platform/hardhat.py", line 52, in hardhat_like_parsing
    raise InvalidCompilation(txt)
crytic_compile.platform.exceptions.InvalidCompilation: Compilation failed. Can you run build command?
out/build-info is not a directory.
```

**Comment by elopez** [comment]
@0xmichalis when both Foundry and Hardhat are present, crytic-compile chooses Foundry as it's usually more robust. You can however override this automatic choice and opt to use Hardhat by using `--compile-force-framework hardhat` on the command line or `compile_force_framework` on the config file.

**Comment by 0xalpharush** [comment]
^ Using `ignore_compile` will disable compilation altogether so it should be removed from the config.
https://github.com/ToucanProtocol/contracts/blob/530baaf585b91ba172ce0ea1b94352c60fc7bf85/slither.config.json#L6

**Comment by 0xmichalis** [comment]
We cannot avoid `ignore_compile` because of https://github.com/crytic/slither/issues/2026

**Comment by elopez** [comment]
Both options should work well together, as long as you run the chosen framework before running Slither.

**Comment by 0xalpharush** [comment]
@0xmichalis Your comment references hardhat. I tested with the config removed and slither worked. Is there a reason using foundry for building can not be done instead (as is done by default when both frameworks are detected)?

**Comment by 0xmichalis** [comment]
> @0xmichalis Your comment references hardhat. I tested with the config removed and slither worked. Is there a reason using foundry for building can not be done instead (as is done by default when both frameworks are detected)?

@0xalpharush I guess you are referencing https://github.com/crytic/slither/issues/2026#issuecomment-1952608010 ? We can use `forge` just fine with Slither, it's only Hardhat that does not work.

**Comment by 0xmichalis** [comment]
> Can you explain the issue you're experiencing now that it is building? I can run slither . --compile-force-framework hardhat with the ignore_compile removed in addition to forge working.

Ah sorry about that but the code that requires path filtering is not currently pushed to the repo I have provided in the reproducer for the current issue and this really mixes two different issues, right?

**Comment by 0xalpharush** [comment]
Go ahead and describe the issue with path filtering here, please. To answer your [question](https://github.com/crytic/slither/issues/2026#issuecomment-1952608010), we would need some way to tell hardhat not to compile files yet still successfully resolve dependencies and compile to perform filtering ahead of analysis. 

Fwiw, I realize it may be annoying that we force recompilation, but often times the build framework retain outdated references (a file offset that was invalidated by editing the file).

**Comment by 0xmichalis** [comment]
> @0xmichalis @0xalpharush `slither . --compile-force-framework hardhat --ignore-compile` should also work if you've run `npx hardhat compile` manually, or is that not the case? I'm pretty sure `ignore_compile` only inhibits running `npx hardhat compile`.

Ah, yes, this works fine with `0.10.0`. Pretty sure I had tried with `0.8.3` and it didn't work.

**Comment by 0xmichalis** [comment]
Closing as seems that we just need to upgrade to the latest version :)

Thanks for the prompt responses!
