### ISSUE TITLE
[Bug-Candidate]: ERROR:SlitherSolcParsing

### ISSUE THREAD

**Issue by rayInfinex** [crytic/slither#2456]
### Describe the issue:

ERROR:SlitherSolcParsing:
Failed to generate IR for BaseModule.accountVersion.

### Code example to reproduce the issue:

```
import { ReentrancyGuardUpgradeable } from "@openzeppelin/contracts-upgradeable/utils/ReentrancyGuardUpgradeable.sol";
import { Initializable } from "@openzeppelin/contracts-upgradeable/utils/ReentrancyGuardUpgradeable.sol";

contract BaseModule is ReentrancyGuardUpgradeable {
    function accountVersion() external view returns (uint64) {
        return Initializable._getInitializedVersion();
    }
}
```

### Version:

0.10.0

### Relevant log output:

```shell
ERROR:SlitherSolcParsing:
Failed to generate IR for BaseModule.accountVersion. Please open an issue https://github.com/crytic/slither/issues.
BaseModule.accountVersion (src/accounts/modules/BaseModule.sol#113-115):
        Initializable._getInitializedVersion()
Traceback (most recent call last):
  File "/usr/local/bin/slither", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/slither/__main__.py", line 727, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/usr/local/lib/python3.11/dist-packages/slither/__main__.py", line 833, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/slither/__main__.py", line 107, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/slither/__main__.py", line 80, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/slither/slither.py", line 144, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/usr/local/lib/python3.11/dist-packages/slither/slither.py", line 164, in _init_parsing_and_analyses
    raise e
  File "/usr/local/lib/python3.11/dist-packages/slither/slither.py", line 160, in _init_parsing_and_analyses
    parser.analyze_contracts()
  File "/usr/local/lib/python3.11/dist-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 539, in analyze_contracts
    self._convert_to_slithir()
  File "/usr/local/lib/python3.11/dist-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 765, in _convert_to_slithir
    raise e
  File "/usr/local/lib/python3.11/dist-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 750, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/usr/local/lib/python3.11/dist-packages/slither/core/declarations/function.py", line 1767, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/usr/local/lib/python3.11/dist-packages/slither/core/cfg/node.py", line 718, in slithir_generation
    self._find_read_write_call()
  File "/usr/local/lib/python3.11/dist-packages/slither/core/cfg/node.py", line 926, in _find_read_write_call
    assert isinstance(ir.function, Function)
AssertionError
```

**Comment by 0xalpharush** [comment]
@rayInfinex Would you please use the latest version and let us know if the error persists?

**Comment by rayInfinex** [comment]
@0xalpharush it worked after updating to the latest. thanks
