### ISSUE TITLE
[Bug-Candidate]: ERROR:SlitherSolcParsing:     assert isinstance(right, TupleVariable)  AssertionError

### ISSUE THREAD

**Issue by yashgoel72** [crytic/slither#2489]
### Describe the issue:

ERROR:SlitherSolcParsing:     assert isinstance(right, TupleVariable)  AssertionError

### Code example to reproduce the issue:

```
pragma solidity ^0.4.24;

contract Reentrancy_cross_function {

    // INSECURE
    mapping (address => uint) private userBalances;

    function transfer(address to, uint amount) public{
        if (userBalances[msg.sender] >= amount) {
            userBalances[to] += amount;
            userBalances[msg.sender] -= amount;
        }
    }

    function withdrawBalance() public {
        uint amountToWithdraw = userBalances[msg.sender];
        // <yes> <report> REENTRANCY
        (bool success, ) = msg.sender.call.value(amountToWithdraw)(""); // At this point, the caller's code is executed, and can call transfer()
        require(success);
        userBalances[msg.sender] = 0;
    }
}
```

### Version:

0.10.3

### Relevant log output:

```shell
slither test.sol
'solc --version' running
'solc test.sol --combined-json abi,ast,bin,bin-runtime,srcmap,srcmap-runtime,userdoc,devdoc,hashes,compact-format --allow-paths .,/Users/yashgoel/Desktop' running
Compilation warnings/errors on test.sol:
test.sol:24:9: Warning: Different number of components on the left hand side (2) than on the right hand side (1).
        (bool success, ) = msg.sender.call.value(amountToWithdraw)(""); // At this point, the caller's code is executed, and can call transfer()
        ^------------------------------------------------------------^

ERROR:SlitherSolcParsing:
Failed to generate IR for Reentrancy_cross_function.withdrawBalance. Please open an issue https://github.com/crytic/slither/issues.
Reentrancy_cross_function.withdrawBalance (test.sol#21-27):
        amountToWithdraw = userBalances[msg.sender]
        (success,None) = msg.sender.call.value(amountToWithdraw)()
        require(bool)(success)
        userBalances[msg.sender] = 0
Traceback (most recent call last):
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/env/bin/slither", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/__main__.py", line 782, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/__main__.py", line 888, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/__main__.py", line 113, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/__main__.py", line 80, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/slither.py", line 202, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/slither.py", line 221, in _init_parsing_and_analyses
    raise e
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/slither.py", line 217, in _init_parsing_and_analyses
    parser.analyze_contracts()
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/solc_parsing/slither_compilation_unit_solc.py", line 593, in analyze_contracts
    self._convert_to_slithir()
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/solc_parsing/slither_compilation_unit_solc.py", line 827, in _convert_to_slithir
    raise e
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/solc_parsing/slither_compilation_unit_solc.py", line 812, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/core/declarations/function.py", line 1827, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/core/cfg/node.py", line 717, in slithir_generation
    self._irs = convert_expression(expression, self)  # type:ignore
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/slithir/convert.py", line 115, in convert_expression
    visitor = ExpressionToSlithIR(expression, node)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/visitors/slithir/expression_to_slithir.py", line 174, in __init__
    self._visit_expression(self.expression)
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/visitors/expression/expression.py", line 78, in _visit_expression
    self._post_visit(expression)
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/visitors/expression/expression.py", line 252, in _post_visit
    self._post_assignement_operation(expression)
  File "/Users/yashgoel/Desktop/slitherin-slither/slither/slither/visitors/slithir/expression_to_slithir.py", line 209, in _post_assignement_operation
    assert isinstance(right, TupleVariable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by 0xalpharush** [comment]
The ability to create a tuple despite `.call` only returning a boolean prior to 0.5.0 seems like a quirk in older versions of solidity that isn't worth fixing. https://docs.soliditylang.org/en/v0.5.0/050-breaking-changes.html

For example, this works.
```
pragma solidity ^0.4.24;

contract Reentrancy_cross_function {

    // INSECURE
    mapping (address => uint) private userBalances;

    function transfer(address to, uint amount) public{
        if (userBalances[msg.sender] >= amount) {
            userBalances[to] += amount;
            userBalances[msg.sender] -= amount;
        }
    }

    function withdrawBalance() public {
        uint amountToWithdraw = userBalances[msg.sender];
        // <yes> <report> REENTRANCY
        bool success = msg.sender.call.value(amountToWithdraw)(""); // At this point, the caller's code is executed, and can call transfer()
        require(success);
        userBalances[msg.sender] = 0;
    }
}
```
