### ISSUE TITLE
[Bug-Candidate]: Failed to generate IR for (maybe) this.balance and SafeMath in old Solidity version

### ISSUE THREAD

**Issue by UshioA** [crytic/slither#2608]
### Describe the issue:

I used Slither to analyze Solidity code files, and got an error message which told me to open a issue here.

The file to trigger the error is [42e267c21c222ab5cb97cccaf17a92ef.zip](https://github.com/user-attachments/files/17957130/42e267c21c222ab5cb97cccaf17a92ef.zip) (I use zip because github does not like `.sol` files)

### Code example to reproduce the issue:

Made a repo containing the buggy file and reproduce script:
https://github.com/UshioA/maybe-slither-issue

### Version:

0.10.4

### Relevant log output:

```shell
'solc --version' running
'solc 42e267c21c222ab5cb97cccaf17a92ef.sol --combined-json abi,ast,bin,bin-runtime,srcmap,srcmap-runtime,userdoc,devdoc,hashes,compact-format --allow-paths .,/home/hengdiye/tmp/slithIR_examples/solfuse' running
ERROR:SlitherSolcParsing:
Failed to generate IR for BBDExchange.maxSell. Please open an issue https://github.com/crytic/slither/issues.
BBDExchange.maxSell (42e267c21c222ab5cb97cccaf17a92ef.sol#32-34):
  valueBbd = this.balance.mul(0)
  valueBbd
Traceback (most recent call last):
  File "/home/hengdiye/miniconda3/envs/solfuse/bin/slither", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/__main__.py", line 776, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/__main__.py", line 882, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/__main__.py", line 107, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/__main__.py", line 80, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/slither.py", line 202, in __init__
    self._init_parsing_and_analyses(kwargs.get("skip_analyze", False))
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/slither.py", line 221, in _init_parsing_and_analyses
    raise e
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/slither.py", line 217, in _init_parsing_and_analyses
    parser.analyze_contracts()
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 593, in analyze_contracts
    self._convert_to_slithir()
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 827, in _convert_to_slithir
    raise e
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 812, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/core/declarations/function.py", line 1827, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/core/cfg/node.py", line 717, in slithir_generation
    self._irs = convert_expression(expression, self)  # type:ignore
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/slithir/convert.py", line 118, in convert_expression
    result = apply_ir_heuristics(result, node, is_solidity)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/slithir/convert.py", line 2040, in apply_ir_heuristics
    irs = propagate_type_and_convert_call(irs, node)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/slithir/convert.py", line 529, in propagate_type_and_convert_call
    new_ins = propagate_types(ins, node)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hengdiye/miniconda3/envs/solfuse/lib/python3.11/site-packages/slither/slithir/convert.py", line 630, in propagate_types
    if t in using_for or "*" in using_for:
       ^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
```

**Comment by smonicas** [comment]
Hi thanks for opening the issue. If you explicitly convert this to address like `address(this).balance.mul(0)` you will see that slither works. Since solidity 0.5.0 is not possible to use `this.balance` without explicitly converting it to address so i think we will not try to fix this particular case.

**Comment by UshioA** [comment]
Thank you! I'm dealing with some really old solidity files, so this error occurs sometimes. I will fix my solidity file then.
