### ISSUE TITLE
slither . , command is not working and giving python errors

### ISSUE THREAD

**Issue by abhisharma1357** [crytic/slither#312]
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.4-py3.6.egg/slither/__main__.py", line 585, in main_impl
    (slither_instances, results, number_contracts) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.4-py3.6.egg/slither/__main__.py", line 59, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.6/dist-packages/crytic_compile-0.1.2-py3.6.egg/crytic_compile/crytic_compile.py", line 55, in compile_all
    if os.path.isfile(target) or is_supported(target):
  File "/usr/local/lib/python3.6/dist-packages/crytic_compile-0.1.2-py3.6.egg/crytic_compile/crytic_compile.py", line 28, in is_supported
    return any(f(target) for f in supported) or target.endswith('.zip')
  File "/usr/local/lib/python3.6/dist-packages/crytic_compile-0.1.2-py3.6.egg/crytic_compile/crytic_compile.py", line 28, in <genexpr>
    return any(f(target) for f in supported) or target.endswith('.zip')
  File "/usr/local/lib/python3.6/dist-packages/crytic_compile-0.1.2-py3.6.egg/crytic_compile/platform/standard.py", line 10, in is_standard
    return Path(target).parts[-1].endswith("_export.json")
IndexError: tuple index out of range

**Comment by montyly** [comment]
Hi @abhisharma1357

Thank you for reporting the issue. Can you detail how you installed Slither? Would it be possible to share the codebase you are trying to analyze?

**Comment by montyly** [comment]
As we haven't heard back from the issue, I assume it is fixed.
