### ISSUE TITLE
Suggest to remove build directory after changing repo version and re-running slither-check-upgradeability

### ISSUE THREAD

**Issue by disconnect3d** [crytic/slither#341]
When the `slither-check-upgradeability` is run after `slither` was used previously on a truffle project which was build and whose code has changed (i.e. files removed/added) the tool could suggest to make a clean-rebuild of the project when failing like this:
```
$ slither-check-upgradeability . SomeContractProxy . SomeContract
ERROR:CryticCompile:- Fetching solc version list from solc-bin. Attempt #1

Traceback (most recent call last):
  File "/Users/dc/tob/projects/slither/slither/slither.py", line 59, in __init__
    crytic_compile = CryticCompile(target, **kwargs)
  File "/Users/dc/.virtualenvs/slither/lib/python3.7/site-packages/crytic_compile-0.1.3-py3.7.egg/crytic_compile/crytic_compile.py", line 128, in __init__
  File "/Users/dc/.virtualenvs/slither/lib/python3.7/site-packages/crytic_compile-0.1.3-py3.7.egg/crytic_compile/crytic_compile.py", line 674, in _compile
  File "/Users/dc/.virtualenvs/slither/lib/python3.7/site-packages/crytic_compile-0.1.3-py3.7.egg/crytic_compile/platform/truffle.py", line 95, in compile
  File "/Users/dc/.virtualenvs/slither/lib/python3.7/site-packages/crytic_compile-0.1.3-py3.7.egg/crytic_compile/utils/naming.py", line 68, in convert_filename
crytic_compile.platform.exceptions.InvalidCompilation: Unknown file: /some-path/src/some-path-to-some-solidity-file.sol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dc/.virtualenvs/slither/bin/slither-check-upgradeability", line 11, in <module>
    load_entry_point('slither-analyzer', 'console_scripts', 'slither-check-upgradeability')()
  File "/Users/dc/tob/projects/slither/slither/tools/upgradeability/__main__.py", line 44, in main
    proxy = Slither(proxy_filename, **vars(args))
  File "/Users/dc/tob/projects/slither/slither/slither.py", line 62, in __init__
    raise SlitherError('Invalid compilation: \n'+str(e))
slither.exceptions.SlitherError: Invalid compilation:
Unknown file: /some-path/src/some-path-to-some-solidity-file.sol
```

**Comment by montyly** [comment]
I am not sure to understand the feature here.

`slither-check-upgradeability` does a clean build on every call, this looks more like an issue with the compilation? Can you share an example?
