### ISSUE TITLE
slither crash:  assert isinstance(variable, (Constant,

### ISSUE THREAD

**Issue by miohtama** [crytic/slither#427]
I am trying to run Slither on [this Truffle based open source repo](https://github.com/Dawn-Protocol/dawn-erc20). 

It is a normal Solidity repository. No bells and whistles, besides is its usage of `@import` pattern to get the OpenZepplin base contracts, like:

```
import '@openzeppelin/contracts-ethereum-package/contracts/token/ERC20/ERC20Burnable.sol';
```

Slither crashes in `/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/slithir/utils/ssa.py` with ` assert isinstance(variable, (Constant,`

# Steps to reproduce 

1. Checkout the repo above
2. Then run

```sh
slither .
```

```slither --version
0.6.10
```

Full log:
```
'npx truffle@5.1.17 compile --all' running (use --truffle-version truffle@x.x.x to use specific version)

Compiling your contracts...
===========================
> Compiling ./contracts/DawnTokenImpl.sol
> Compiling ./contracts/DawnTokenProxy.sol
> Compiling ./contracts/Legacy.sol
> Compiling ./contracts/Migrations.sol
> Compiling ./contracts/Recoverable.sol
> Compiling ./contracts/Staking.sol
> Compiling ./contracts/TokenFaucet.sol
> Compiling ./contracts/TokenSwap.sol
> Compiling ./contracts/tests/UpgradedTokenTestImpl.sol
> Compiling @openzeppelin/contracts-ethereum-package/contracts/GSN/Context.sol
> Compiling @openzeppelin/contracts-ethereum-package/contracts/access/Roles.sol
> Compiling @openzeppelin/contracts-ethereum-package/contracts/access/roles/PauserRole.sol
> Compiling @openzeppelin/contracts-ethereum-package/contracts/lifecycle/Pausable.sol
> Compiling @openzeppelin/contracts-ethereum-package/contracts/math/SafeMath.sol
> Compiling @openzeppelin/contracts-ethereum-package/contracts/ownership/Ownable.sol
> Compiling @openzeppelin/contracts-ethereum-package/contracts/token/ERC20/ERC20.sol
> Compiling @openzeppelin/contracts-ethereum-package/contracts/token/ERC20/ERC20Burnable.sol
> Compiling @openzeppelin/contracts-ethereum-package/contracts/token/ERC20/ERC20Pausable.sol
> Compiling @openzeppelin/contracts-ethereum-package/contracts/token/ERC20/IERC20.sol
> Compiling @openzeppelin/upgrades/contracts/Initializable.sol
> Compiling @openzeppelin/upgrades/contracts/upgradeability/AdminUpgradeabilityProxy.sol
> Compiling @openzeppelin/upgrades/contracts/upgradeability/BaseAdminUpgradeabilityProxy.sol
> Compiling @openzeppelin/upgrades/contracts/upgradeability/BaseUpgradeabilityProxy.sol
> Compiling @openzeppelin/upgrades/contracts/upgradeability/Proxy.sol
> Compiling @openzeppelin/upgrades/contracts/upgradeability/UpgradeabilityProxy.sol
> Compiling @openzeppelin/upgrades/contracts/utils/Address.sol
> Artifacts written to /Users/moo/code/dawn-erc20/build/contracts
> Compiled successfully using:
   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang


- Fetching solc version list from solc-bin. Attempt #1

ERROR:ContractSolcParsing:'onlyPauser()'
ERROR:ContractSolcParsing:'constructor()'
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/__main__.py", line 578, in main_impl
    (slither_instances, results_detectors, results_printers, number_contracts) = process_all(filename, args, detector_classes, printer_classes)
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/__main__.py", line 66, in process_all
    (slither, current_results_detectors, current_results_printers, current_analyzed_count) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/__main__.py", line 52, in process_single
    slither = Slither(target,
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/slither.py", line 86, in __init__
    self._analyze_contracts()
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 258, in _analyze_contracts
    self._convert_to_slithir()
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 380, in _convert_to_slithir
    contract.convert_expression_to_slithir()
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/solc_parsing/declarations/contract.py", line 589, in convert_expression_to_slithir
    func.generate_slithir_ssa(all_ssa_state_variables_instances)
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/core/declarations/function.py", line 1386, in generate_slithir_ssa
    add_ssa_ir(self, all_ssa_state_variables_instances)
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/slithir/utils/ssa.py", line 138, in add_ssa_ir
    generate_ssa_irs(function.entry_point,
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/slithir/utils/ssa.py", line 223, in generate_ssa_irs
    generate_ssa_irs(succ,
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/slithir/utils/ssa.py", line 176, in generate_ssa_irs
    new_ir = copy_ir(ir,
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/slithir/utils/ssa.py", line 554, in copy_ir
    new_ir.arguments = get_arguments(ir, *instances)
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/slithir/utils/ssa.py", line 496, in get_arguments
    return _get_traversal(ir.arguments, *instances)
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/slithir/utils/ssa.py", line 491, in _get_traversal
    v = get(v, *instances)
  File "/Users/moo/code/lib-workspace/venv/lib/python3.8/site-packages/slither/slithir/utils/ssa.py", line 470, in get
    assert isinstance(variable, (Constant,
AssertionError```

**Comment by montyly** [comment]
Hi @miohtama thank you for the report.

I cant reproduce the crash, but I think the issue is that the codebase has two contracts with the same name. When I run Slither locally it shows:
```
SafeMath is re-used:
	- @openzeppelin/contracts-ethereum-package/contracts/math/SafeMath.sol#16-156
	- Legacy.sol#13-35
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#name-reused
```

If you rename `SafeMath` in `Legacy.sol`, it should work.

For context, if you have two contracts with the same name, Truffle will generate incorrect compilation artifacts. As a result, Slither cannot analyze correctly the codebase. We allowed Slither to run on such incorrect setting in `0.6.10`, but we are still improving this support (https://github.com/crytic/slither/pull/423)

**Comment by miohtama** [comment]
Hi @montyly - I weeded the codebase for duplicate contracts names.

This, plus I had to clean the `build` folder and Slither was able to run. 

Thank you for a prompt reply! 💯
