### ISSUE TITLE
doesn't support multiple solc versions

### ISSUE THREAD

**Issue by elenadimitrova** [crytic/slither#488]
When compiling different contracts with different solc versions `slither print inheritance` fails for the non-default. Example run for the `contracts/infrastructure/MakerRegistry.sol` contract which is compiled with 0.5.4 via `etherlime built in functionality` while the `solc` version installed locally is `0.6.8`.

```
Galaxy-2:argent-contracts Elena$ slither contracts/infrastructure/MakerRegistry.sol --print inheritance
Compilation warnings/errors on contracts/infrastructure/MakerRegistry.sol:
Warning: This is a pre-release compiler version, please do not use it in production.

Error: Source file requires different compiler version (current compiler is 0.6.7-develop.2020.4.14+commit.accd8d76.Darwin.appleclang - note that nightly builds are considered to be strictly less than the released version
 --> contracts/infrastructure/MakerRegistry.sol:1:1:
  |
1 | pragma solidity ^0.5.4;
  | ^^^^^^^^^^^^^^^^^^^^^^^


ERROR:root:Error in contracts/infrastructure/MakerRegistry.sol
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/crytic_compile/platform/solc.py", line 356, in _run_solc
    ret = json.loads(stdout)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 606, in main_impl
    printer_classes)
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 61, in process_all
    compilations = compile_all(target, **vars(args))
  File "/usr/local/lib/python3.7/site-packages/crytic_compile/crytic_compile.py", line 1013, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/crytic_compile/crytic_compile.py", line 119, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/crytic_compile/crytic_compile.py", line 924, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/crytic_compile/platform/solc.py", line 151, in compile
    working_dir=solc_working_dir,
  File "/usr/local/lib/python3.7/site-packages/crytic_compile/platform/solc.py", line 359, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Warning: This is a pre-release compiler version, please do not use it in production.

Error: Source file requires different compiler version (current compiler is 0.6.7-develop.2020.4.14+commit.accd8d76.Darwin.appleclang - note that nightly builds are considered to be strictly less than the released version
 --> contracts/infrastructure/MakerRegistry.sol:1:1:
  |
1 | pragma solidity ^0.5.4;
  | ^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by montyly** [comment]
Hi @elenadimitrova ,

I would recommend using [`solc-select`](https://github.com/crytic/solc-select) to switch quickly the local solc version:
```
SOLC_VERSION=0.5.4 slither some_file.sol
```

Though in the case of `contracts/infrastructure/MakerRegistry.sol`, I think using directly solc will fail, due to the import:
https://github.com/argentlabs/argent-contracts/blob/3f1bab8dad74f7b49c68a0d6b74e28b9e0db9bf0/contracts/infrastructure/MakerRegistry.sol#L2-L3

A simple solution is to run slither's printers directly on the argent-contracts directory:
```
slither . --print inheritance
```

sidenote: consider using the `--ignore-compile` flag is you are trying the printers, to skip running `etherlime compile` on every Slither run.

**Comment by elenadimitrova** [comment]
Thanks @montyly my mistake for forgetting it supports solc select. Running the inheritance printer on the entire repo gives the following errors 
```
Galaxy-2:argent-contracts Elena$ slither . --print inheritance
Compilation finished successfully
ERROR:ContractSolcParsing:Missing inheritance CompoundManager
ERROR:ContractSolcParsing:Missing inheritance LegacyMakerManager
ERROR:ContractSolcParsing:Missing inheritance SaiTub
ERROR:ContractSolcParsing:Missing inheritance RecoveryManager
ERROR:ContractSolcParsing:Missing inheritance TransferManager
ERROR:ContractSolcParsing:Missing inheritance ApprovedTransfer
ERROR:ContractSolcParsing:Missing inheritance TokenPriceProvider
ERROR:ContractSolcParsing:Missing inheritance DSThing
ERROR:ContractSolcParsing:Missing inheritance TokenExchanger
ERROR:ContractSolcParsing:Missing inheritance GuardianManager
ERROR:ContractSolcParsing:Missing inheritance LegacyTransferManager
ERROR:ContractSolcParsing:Missing inheritance SimpleUpgrader
ERROR:ContractSolcParsing:Missing inheritance TestERC20
ERROR:ContractSolcParsing:Missing inheritance ENSRegistryWithFallback
ERROR:ContractSolcParsing:Missing inheritance LockManager
ERROR:ContractSolcParsing:Missing inheritance SaiVox
ERROR:ContractSolcParsing:Missing inheritance NftTransfer
ERROR:ContractSolcParsing:Missing inheritance BaseTransfer
ERROR:ContractSolcParsing:Missing inheritance DSValue
ERROR:ContractSolcParsing:Missing inheritance LimitManager
ERROR:ContractSolcParsing:Missing params 'onlyOwner()'
ERROR:ContractSolcParsing:Missing params 'constructor()'
ERROR:ContractSolcParsing:Missing params 'auth()'
ERROR:ContractSolcParsing:Missing params 'add(uint256,uint256)'
ERROR:ContractSolcParsing:Missing params 'auth()'
ERROR:ContractSolcParsing:Missing params 'add(uint256,uint256)'
ERROR:ConvertToIR:Function not found fold(bytes32,address,int256)
ERROR:ContractSolcParsing:Impossible to generate IR for Jug.drip
ERROR:ConvertToIR:Function not found suck(address,address,uint256)
ERROR:ContractSolcParsing:Impossible to generate IR for Pot.drip
ERROR:ConvertToIR:Function not found flux(bytes32,address,address,uint256)
ERROR:ContractSolcParsing:Impossible to generate IR for DssCdpManager.flux
ERROR:ConvertToIR:Function not found flux(bytes32,address,address,uint256)
ERROR:ContractSolcParsing:Impossible to generate IR for DssCdpManager.flux
ERROR:ConvertToIR:Function not found fork(bytes32,address,address,int256,int256)
ERROR:ContractSolcParsing:Impossible to generate IR for DssCdpManager.quit
ERROR:ConvertToIR:Function not found fork(bytes32,address,address,int256,int256)
ERROR:ContractSolcParsing:Impossible to generate IR for DssCdpManager.enter
ERROR:ConvertToIR:Function not found fork(bytes32,address,address,int256,int256)
ERROR:ContractSolcParsing:Impossible to generate IR for DssCdpManager.shift
INFO:Printers:Inheritance
```

**Comment by montyly** [comment]
What version of slither are you using (`slither --version`)?

With 0.6.12, on commit `3f1bab8dad74f7b49c68a0d6b74e28b9e0db9bf0`, I have
```
INFO:Printers:Inheritance
Child_Contract -> Immediate_Base_Contracts [Not_Immediate_Base_Contracts]
+ LimitManager
 -> BaseModule
, [Module]

+ NftTransfer
 -> BaseModule, RelayerModule, OnlyOwnerModule
, [Module]

+ ModuleRegistry
 -> Owned

+ ERC20

+ Module

+ GuardianManager
 -> BaseModule, RelayerModule
, [Module]
...
```

**Comment by elenadimitrova** [comment]
Yes on the latest 0.6.12. I get the inheritance print okay but it's prepended with these errors.

**Comment by elenadimitrova** [comment]
I'm closing this as it's not an issue after all. We can carry on the conversation offline.
