### ISSUE TITLE
Cannot flatten uniswap-v2 ("<contracts folder> doesn't exist")

### ISSUE THREAD

**Issue by Pet3ris** [crytic/slither#508]
Hi There,

Having trouble with the following flattening process:

```bash
# Clone Uniswap
echo "uniswap-v2-core" > .gitignore
git clone https://github.com/Uniswap/uniswap-v2-core.git

# Reproduce deps & tests
cd uniswap-v2-core/contracts
npm i
npm i keccakjs --save
npm i web3-provider-engine
npm test

# Run flattening
cd ..
pipenv install -e git+https://github.com/crytic/slither.git@dev#egg=slither-analyzer
pipenv run slither-flat uniswap-v2-core/contracts --strategy OneFile
```

I'm getting the following error:

```
Traceback (most recent call last):
  File "/Users/p/.local/share/virtualenvs/uniswap-v2-oB7e_atR/bin/slither-flat", line 33, in <module>
    sys.exit(load_entry_point('slither-analyzer', 'console_scripts', 'slither-flat')())
  File "/Users/p/.local/share/virtualenvs/uniswap-v2-oB7e_atR/src/slither-analyzer/slither/tools/flattening/__main__.py", line 92, in main
    slither = Slither(args.filename, **vars(args))
  File "/Users/p/.local/share/virtualenvs/uniswap-v2-oB7e_atR/src/slither-analyzer/slither/slither.py", line 64, in __init__
    raise SlitherError('Invalid compilation: \n'+str(e))
slither.exceptions.SlitherError: Invalid compilation: 
uniswap-v2-core/contracts/ does not exist (are you in the correct directory?)
```

Even though the contract folder definitely exists.

Am I doing something wrong perhaps?

**Comment by montyly** [comment]
Hi @Pet3ris ,

- Uniswap uses `waffle`, so slither needs these extra flag: `--waffle-config .waffle.json --compile-force-framework Waffle`
- The target should be the root directory of the project `uniswap-v2-core` and not `uniswap-v2-core/contracts`

This will work:
```
$ git clone https://github.com/Uniswap/uniswap-v2-core.git
$ cd uniswap-v2-core
$ npm install
$ slither-flat . --strategy OneFile --waffle-config .waffle.json --compile-force-framework Waffle
```

There is one issue though, it seems that we are not detecting the correct solc version used with Waffle. The exported file will have `pragma solidity 0.6.9` instead of `pragma solidity 0.5.16`.

We will improve Waffle support

**Comment by Pet3ris** [comment]
Thanks - managed to reproduce this. It didn't work very well from an outside folder btw (even when changing `.` to `uniswap-v2-core` and changing `.waffle.json` to `uniswap-v2-core/.waffle.json` but works perfectly well from inside the repo!

**Comment by montyly** [comment]
Good catch @Pet3ris. We will fix that

Thanks for reporting these issues.

**Comment by dguido** [comment]
Hi @Pet3ris,

This appears to be a user support issue rather than a bug in Slither. The error message indicates you were likely not in the correct directory when running the flattening command, as the error states: "uniswap-v2-core/contracts/ does not exist (are you in the correct directory?)".

The slither-flat tool has undergone significant improvements since 2020, and directory path handling has been enhanced. The specific issue you encountered was related to command execution context.

Closing as this was a usage/configuration issue rather than a bug.
