### ISSUE TITLE
AssertionError when parsing new style of payable function expressions

### ISSUE THREAD

**Issue by Xenomega** [crytic/slither#585]
The following contract causes an assertion error:
```
contract CallPayableFuncExpr {
    function f() public {
        function() external payable func;
        func{gas: 2, value: 3}();
    }
}
```

Output:
```
ERROR:root:Error in .\payable_function_call_expr.sol
ERROR:root:Traceback (most recent call last):
  File "c:\users\x\documents\github\slither\slither\__main__.py", line 610, in main_impl
    (slither_instances, results_detectors, results_printers, number_contracts) = process_all(filename, args,
  File "c:\users\x\documents\github\slither\slither\__main__.py", line 67, in process_all
    (slither, current_results_detectors, current_results_printers, current_analyzed_count) = process_single(
  File "c:\users\x\documents\github\slither\slither\__main__.py", line 53, in process_single
    slither = Slither(target,
  File "c:\users\x\documents\github\slither\slither\slither.py", line 86, in __init__
    self._parser.analyze_contracts()
  File "c:\users\x\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 341, in analyze_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "c:\users\x\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 438, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "c:\users\x\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 478, in _analyze_variables_modifiers_functions
    contract.analyze_content_functions()
  File "c:\users\x\documents\github\slither\slither\solc_parsing\declarations\contract.py", line 356, in analyze_content_functions
    function_parser.analyze_content()
  File "c:\users\x\documents\github\slither\slither\solc_parsing\declarations\function.py", line 300, in analyze_content
    node_parser.analyze_expressions(self)
  File "c:\users\x\documents\github\slither\slither\solc_parsing\cfg\node.py", line 33, in analyze_expressions
    expression = parse_expression(self._unparsed_expression, caller_context)
  File "c:\users\x\documents\github\slither\slither\solc_parsing\expressions\expression_parsing.py", line 465, in parse_expression
    return parse_call(expression, caller_context)
  File "c:\users\x\documents\github\slither\slither\solc_parsing\expressions\expression_parsing.py", line 317, in parse_call
    called = parse_expression(expression["expression"], caller_context)
  File "c:\users\x\documents\github\slither\slither\solc_parsing\expressions\expression_parsing.py", line 470, in parse_expression
    assert isinstance(called, (MemberAccess, NewContract))
AssertionError
```

**Comment by montyly** [comment]
This issue requires actually more work that anticipated.

Solidity supports dynamic external call:

```solidity
contract A{
    function f_a() external{

    }
}

contract B {

    function f(A a) public {
        function() external func = a.f_a;
        func();
    }
}
```

SlithIR does not handle this for now.

**Comment by dguido** [comment]
Hi @Xenomega,

The assertion error when parsing the new style of payable function expressions with gas and value parameters (e.g., `func{gas: 2, value: 3}()`) has been fixed.

This syntax was introduced in Solidity 0.6.x as a replacement for the older `.value()` and `.gas()` member access pattern. The expression parsing system has been updated to properly handle this new syntax, and it no longer causes assertion errors.

Closing as fixed.
