### ISSUE TITLE
AssertionError parsing expression indexing into a constant

### ISSUE THREAD

**Issue by Xenomega** [crytic/slither#588]
Similar to #586 , index expressions also do not handle indexing into a Constant.
```
contract InlineArrayIndex {
    function f() public {
        uint x = [0][0];
    }
}
```

Output:
```
ERROR:root:Error in .\inline_array_index.sol
ERROR:root:Traceback (most recent call last):
  File "c:\users\x\documents\github\slither\slither\__main__.py", line 610, in main_impl
    (slither_instances, results_detectors, results_printers, number_contracts) = process_all(filename, args,
  File "c:\users\x\documents\github\slither\slither\__main__.py", line 67, in process_all
    (slither, current_results_detectors, current_results_printers, current_analyzed_count) = process_single(
  File "c:\users\x\documents\github\slither\slither\__main__.py", line 53, in process_single
    slither = Slither(target,
  File "c:\users\x\documents\github\slither\slither\slither.py", line 86, in __init__
    self._parser.analyze_contracts()
  File "c:\users\x\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 345, in analyze_contracts
    self._convert_to_slithir()
  File "c:\users\x\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 489, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "c:\users\x\documents\github\slither\slither\core\declarations\function.py", line 1652, in generate_slithir_and_analyze
    node.slithir_generation()
  File "c:\users\x\documents\github\slither\slither\core\cfg\node.py", line 702, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "c:\users\x\documents\github\slither\slither\slithir\convert.py", line 64, in convert_expression
    visitor = ExpressionToSlithIR(expression, node)
  File "c:\users\x\documents\github\slither\slither\visitors\slithir\expression_to_slithir.py", line 103, in __init__
    self._visit_expression(self.expression)
  File "c:\users\x\documents\github\slither\slither\visitors\expression\expression.py", line 45, in _visit_expression
    self._visit_assignement_operation(expression)
  File "c:\users\x\documents\github\slither\slither\visitors\expression\expression.py", line 101, in _visit_assignement_operation
    self._visit_expression(expression.expression_right)
  File "c:\users\x\documents\github\slither\slither\visitors\expression\expression.py", line 95, in _visit_expression
    self._post_visit(expression)
  File "c:\users\x\documents\github\slither\slither\visitors\expression\expression.py", line 283, in _post_visit
    self._post_index_access(expression)
  File "c:\users\x\documents\github\slither\slither\visitors\slithir\expression_to_slithir.py", line 306, in _post_index_access
    operation = Index(val, left, right, expression.type)
  File "c:\users\x\documents\github\slither\slither\slithir\operations\index.py", line 13, in __init__
    assert is_valid_lvalue(left_variable) or left_variable == SolidityVariableComposed('msg.data')
AssertionError
```

**Comment by dguido** [comment]
Hi @Xenomega,

The assertion error when parsing expressions that index into inline array literals (e.g., `[0][0]`) has been fixed. 

The expression parser now properly handles indexing operations on constant arrays and inline array literals. The issue was that the Index operation incorrectly required the left operand to be a valid lvalue, which inline array literals are not.

This parsing issue has been resolved in subsequent versions.

Closing as fixed.
