### ISSUE TITLE
AssertionError parsing IR indexing into array of functions

### ISSUE THREAD

**Issue by Xenomega** [crytic/slither#591]
The following contract causes an assertion error:
```
contract ArrayOfFunctionTypes {
    function f() public {
         [this.f, this.f][0];
    }
}
```

Output:
```
ERROR:root:Error in .\type_array.sol
ERROR:root:Traceback (most recent call last):
  File "c:\users\x\documents\github\slither\slither\__main__.py", line 610, in main_impl
    (slither_instances, results_detectors, results_printers, number_contracts) = process_all(filename, args,
  File "c:\users\x\documents\github\slither\slither\__main__.py", line 67, in process_all
    (slither, current_results_detectors, current_results_printers, current_analyzed_count) = process_single(
  File "c:\users\x\documents\github\slither\slither\__main__.py", line 53, in process_single
    slither = Slither(target,
  File "c:\users\x\documents\github\slither\slither\slither.py", line 86, in __init__
    self._parser.analyze_contracts()
  File "c:\users\x\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 345, in analyze_contracts
    self._convert_to_slithir()
  File "c:\users\x\documents\github\slither\slither\solc_parsing\slitherSolc.py", line 489, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "c:\users\x\documents\github\slither\slither\core\declarations\function.py", line 1652, in generate_slithir_and_analyze
    node.slithir_generation()
  File "c:\users\x\documents\github\slither\slither\core\cfg\node.py", line 702, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "c:\users\x\documents\github\slither\slither\slithir\convert.py", line 67, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "c:\users\x\documents\github\slither\slither\slithir\convert.py", line 1321, in apply_ir_heuristics
    irs = propagate_type_and_convert_call(irs, node)
  File "c:\users\x\documents\github\slither\slither\slithir\convert.py", line 309, in propagate_type_and_convert_call
    new_ins = propagate_types(ins, node)
  File "c:\users\x\documents\github\slither\slither\slithir\convert.py", line 476, in propagate_types
    ir.lvalue.set_type(ArrayType(t, length))
  File "c:\users\x\documents\github\slither\slither\core\solidity_types\array_type.py", line 13, in __init__
    assert isinstance(t, Type)
AssertionError
```

**Comment by dguido** [comment]
Hi @Xenomega,

The assertion error when parsing IR indexing into an array of functions (e.g., `[this.f, this.f][0]`) has been fixed.

The type propagation system now properly handles arrays of function types. The issue was in the type inference where function arrays weren't being properly typed, causing an assertion failure when trying to create an ArrayType with a function type element.

This has been resolved through improvements to the type system and IR generation.

Closing as fixed.
