### ISSUE TITLE
Add support for ternary expressions in variable initialization

### ISSUE THREAD

**Issue by samczsun** [crytic/slither#634]
code:
```
contract C {
    uint a = 1 > 0 ? 1 : 0;
}
```

error:
```
Traceback (most recent call last):
  File "/mnt/d/projects/slither/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/mnt/d/projects/slither/slither/__main__.py", line 79, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/mnt/d/projects/slither/slither/__main__.py", line 62, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/mnt/d/projects/slither/slither/slither.py", line 100, in __init__
    self._parser.analyze_contracts()
  File "/mnt/d/projects/slither/slither/solc_parsing/slitherSolc.py", line 353, in analyze_contracts
    self._convert_to_slithir()
  File "/mnt/d/projects/slither/slither/solc_parsing/slitherSolc.py", line 499, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/mnt/d/projects/slither/slither/core/declarations/function.py", line 1661, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/mnt/d/projects/slither/slither/core/cfg/node.py", line 707, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/mnt/d/projects/slither/slither/slithir/convert.py", line 101, in convert_expression
    visitor = ExpressionToSlithIR(expression, node)
  File "/mnt/d/projects/slither/slither/visitors/slithir/expression_to_slithir.py", line 125, in __init__
    self._visit_expression(self.expression)
  File "/mnt/d/projects/slither/slither/visitors/expression/expression.py", line 45, in _visit_expression
    self._visit_assignement_operation(expression)
  File "/mnt/d/projects/slither/slither/visitors/expression/expression.py", line 101, in _visit_assignement_operation
    self._visit_expression(expression.expression_right)
  File "/mnt/d/projects/slither/slither/visitors/expression/expression.py", line 95, in _visit_expression
    self._post_visit(expression)
  File "/mnt/d/projects/slither/slither/visitors/expression/expression.py", line 274, in _post_visit
    self._post_conditional_expression(expression)
  File "/mnt/d/projects/slither/slither/visitors/slithir/expression_to_slithir.py", line 313, in _post_conditional_expression
    raise Exception("Ternary operator are not convertible to SlithIR {}".format(expression))
Exception: Ternary operator are not convertible to SlithIR if 1 > 0 then 1 else 0
```

**Comment by CodeSandwich** [comment]
I can confirm that the issue is still present in 0.9.5. This affects not only the storage variables initialization, but also immutables and constants:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

contract Ternary {
    uint256 public constant MAX_C = 2 > 1 ? 2 : 1;
    uint256 public maxS = 2 > 1 ? 2 : 1;
    uint256 public immutable maxI = 2 > 1 ? 2 : 1;
}
```

**Comment by dguido** [comment]
Hi @samczsun,

The issue with ternary expressions in variable initialization (e.g., `uint a = 1 > 0 ? 1 : 0;`) throwing "not convertible to SlithIR" exceptions has been fixed.

Ternary operators are now properly supported in variable initialization contexts. The SlithIR conversion system has been updated to handle conditional expressions in all contexts where they're valid in Solidity.

Closing as fixed.
