### ISSUE TITLE
Slither fails to run due to Function not found on TMP_309(None) = HIGH_LEVEL_CALL, dest:TMP_308(None), function:toUint112, arguments:[]

### ISSUE THREAD

**Issue by moodysalem** [crytic/slither#667]
Is this an issue with using a single library for multiple types?

Solc 0.6.11

function:toUint112 is a function we have that takes a uint256 and safely converts to a uint112

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/slither/core/cfg/node.py", line 897, in _find_read_write_call
    self._high_level_calls.append((ir.destination.type.type, ir.function))
AttributeError: 'NoneType' object has no attribute 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/slither/__main__.py", line 79, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/slither/__main__.py", line 62, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/slither/slither.py", line 100, in __init__
    self._parser.analyze_contracts()
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 353, in analyze_contracts
    self._convert_to_slithir()
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 499, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/slither/core/declarations/function.py", line 1661, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/slither/core/cfg/node.py", line 709, in slithir_generation
    self._find_read_write_call()
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/slither/core/cfg/node.py", line 900, in _find_read_write_call
    raise SlitherException(
slither.exceptions.SlitherException: Function not found on TMP_309(None) = HIGH_LEVEL_CALL, dest:TMP_308(None), function:toUint112, arguments:[]  . Please try compiling with a recent Solidity version. 'NoneType' object has no attribute 'type'
ERROR:root:Error:
ERROR:root:Function not found on TMP_309(None) = HIGH_LEVEL_CALL, dest:TMP_308(None), function:toUint112, arguments:[]  . Please try compiling with a recent Solidity version. 'NoneType' object has no attribute 'type'
ERROR:root:Please report an issue to https://github.com/crytic/slither/issues
```

**Comment by montyly** [comment]
Hi @moodysalem 

Thank you for reporting this. Would it be possible to share the codebase where this occurs?

**Comment by moodysalem** [comment]
> Would it be possible to share the codebase where this occurs?

Not at the moment, but here are some snippets

`using`

```
contract X {
    using SafeMath for *;
    // ... 
}
```

one call to `toUint112`

```
y = y.addi(z).toUint112();
```

the function definition
```
library SafeMath {
    function toUint112(uint256 y) internal pure returns (uint112 z) {
        require((z = uint112(y)) == y, 'downcast-overflow');
    }
}
```

**Comment by moodysalem** [comment]
Believe this particular error is due to this
https://github.com/crytic/slither/wiki#keyerror-or-nonetype-error

**Comment by 0xalpharush** [comment]
I also ran into this error when using running slither on a contract that uses a casting library.

```
library CastU128I128 {
    /// @dev Safely cast an uint128 to an int128
    function i128(uint128 x) internal pure returns (int128 y) {
        require (x <= uint128(type(int128).max), "Cast overflow");
        y = int128(x);
    }
}
```
Example usage
```
contract Example {
    using CastU128I128 for uint128;
    int128 foo = bar.i128();
}
```

I was able to bypass this by checking that `ir.destination.type is not None` in `core/cfg/node.py`, but I don't imagine this is an acceptable fix. https://github.com/crytic/slither/blob/master/slither/core/cfg/node.py#L902
```
elif ir.destination.type is not None:
    try:
        self._high_level_calls.append((ir.destination.type.type, ir.function))
    except AttributeError as error:
        #  pylint: disable=raise-missing-from
        raise SlitherException(
            f"Function not found on {ir}. Please try compiling with a recent Solidity version. {error}"
        )
```

It was helpful to add `ir.function_name` to the error message for debugging as the temporary name is arbitrary.
```
except AttributeError as error:
    #  pylint: disable=raise-missing-from
    raise SlitherException(
        f"Function not found on {ir.function_name}. Please try compiling with a recent Solidity version. {error}"
    )
```

I'm not sure what would be involved in fixing this, but I will give it a shot if a maintainer could provide insight.
