### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by mrice32** [crytic/slither#670]
We're seeing the following error when running over contracts that compile correctly with solc 0.6.12.

```
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 79, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 62, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 100, in __init__
    self._parser.analyze_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 353, in analyze_contracts
    self._convert_to_slithir()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 499, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/declarations/function.py", line 1661, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/cfg/node.py", line 707, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 104, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 1543, in apply_ir_heuristics
    irs = propagate_type_and_convert_call(irs, node)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 364, in propagate_type_and_convert_call
    new_ins = propagate_types(ins, node)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 683, in propagate_types
    ir.function.return_type = [TypeInformation(ir.arguments[0])]
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/solidity_types/type_information.py", line 16, in __init__
    assert isinstance(c, Contract)
AssertionError
ERROR:root:None
ERROR:root:Error in /home/ethsec/protocol/packages/core
ERROR:root:Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 79, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 62, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 100, in __init__
    self._parser.analyze_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 353, in analyze_contracts
    self._convert_to_slithir()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 499, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/declarations/function.py", line 1661, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/cfg/node.py", line 707, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 104, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 1543, in apply_ir_heuristics
    irs = propagate_type_and_convert_call(irs, node)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 364, in propagate_type_and_convert_call
    new_ins = propagate_types(ins, node)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 683, in propagate_types
    ir.function.return_type = [TypeInformation(ir.arguments[0])]
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/solidity_types/type_information.py", line 16, in __init__
    assert isinstance(c, Contract)
AssertionError
```

Based on the error message I'm thinking it has to do with this line in our code that isn't being correctly parsed:
```
require(a.rawValue <= uint256(type(int256).max), "Unsigned too large");
```

**Comment by ggrieco-tob** [comment]
Which version of slither are you using?

**Comment by mrice32** [comment]
Whichever version Is currently published in the ToB docker image: trailofbits/eth-security-toolbox (the failing run happened earlier today). I can try to dig into the docker image to extract the version, but i figure it's fairly up to date with slither releases.

**Comment by ggrieco-tob** [comment]
I think we had this issue solved in the `master` branch in slither. Can you try reinstalling that version in the docker? (just run `python3 setup.py install --user` after cloning this repository)

**Comment by mrice32** [comment]
I tried cloning the repo and reinstalling slither and I got the same error.

**Comment by montyly** [comment]
Hi @mrice32 .

Thank you for reporting this. I believe that the issue is coming from Slither's lack of support for `type(X).max/min` (https://github.com/crytic/slither/issues/671). We are working on it
