### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by abialy** [crytic/slither#674]
Version 0.6.13

Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 79, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 62, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 100, in __init__
    self._parser.analyze_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 338, in analyze_contracts
    self._analyze_first_part(contracts_to_be_analyzed, libraries)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 395, in _analyze_first_part
    self._parse_struct_var_modifiers_functions(contract)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 461, in _parse_struct_var_modifiers_functions
    contract.parse_state_variables()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/declarations/contract.py", line 303, in parse_state_variables
    var_parser = StateVariableSolc(var, varNotParsed)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/variables/state_variable.py", line 9, in __init__
    super().__init__(variable, variable_data)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/variables/variable_declaration.py", line 65, in __init__
    self._init_from_declaration(variable_data, variable_data["value"])
KeyError: 'value'
ERROR:root:None

**Comment by abialy** [comment]
It happens on more contracts with solidity >7.0.0

ERROR:root:Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 692, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 79, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 62, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 100, in __init__
    self._parser.analyze_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 338, in analyze_contracts
    self._analyze_first_part(contracts_to_be_analyzed, libraries)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 395, in _analyze_first_part
    self._parse_struct_var_modifiers_functions(contract)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 461, in _parse_struct_var_modifiers_functions
    contract.parse_state_variables()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/declarations/contract.py", line 303, in parse_state_variables
    var_parser = StateVariableSolc(var, varNotParsed)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/variables/state_variable.py", line 9, in __init__
    super().__init__(variable, variable_data)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/variables/variable_declaration.py", line 65, in __init__
    self._init_from_declaration(variable_data, variable_data["value"])
KeyError: 'value'


Any idea why?

**Comment by montyly** [comment]
Hi @abialy.

Thank you for reporting this. It might have been already fixed by https://github.com/crytic/slither/pull/642, which is present in slither@master, and will be present in the next release.

**Comment by abialy** [comment]
Yes, I did install master branch and it works fine. Thank you. When do you plan to release it?

**Comment by montyly** [comment]
Hopefully next week. I opened an issue to track the release progress: https://github.com/crytic/slither/issues/676

**Comment by abialy** [comment]
Thank you. Keep up the good work.
