### ISSUE TITLE
Slither Check ERC20 Erro

### ISSUE THREAD

**Issue by naszam** [crytic/slither#710]
Hi, 

I'm trying to run:

`slither-check-erc Uni.sol Uni`

and I get:

```
Traceback (most recent call last):
  File "/home/sencha/.local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 367, in _run_solc
    ret = json.loads(stdout)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sencha/.local/lib/python3.6/site-packages/slither/slither.py", line 75, in __init__
    crytic_compile = CryticCompile(target, **kwargs)
  File "/home/sencha/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 124, in __init__
    self._compile(**kwargs)
  File "/home/sencha/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 931, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/sencha/.local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 156, in compile
    force_legacy_json=force_legacy_json,
  File "/home/sencha/.local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 371, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Uni.sol:17:31: Error: Expected primary expression.
    uint public totalSupply = 1_000_000_000e18; // 1 billion Uni
                              ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sencha/.local/bin/slither-check-erc", line 11, in <module>
    sys.exit(main())
  File "/home/sencha/.local/lib/python3.6/site-packages/slither/tools/erc_conformance/__main__.py", line 75, in main
    slither = Slither(args.project, **vars(args))
  File "/home/sencha/.local/lib/python3.6/site-packages/slither/slither.py", line 79, in __init__
    raise SlitherError(f"Invalid compilation: \n{str(e)}")
slither.exceptions.SlitherError: Invalid compilation: 
Invalid solc compilation Uni.sol:17:31: Error: Expected primary expression.
    uint public totalSupply = 1_000_000_000e18; // 1 billion Uni
```

If I remove the `_` and try again I get:
```
Traceback (most recent call last):
  File "/home/sencha/.local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 367, in _run_solc
    ret = json.loads(stdout)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sencha/.local/lib/python3.6/site-packages/slither/slither.py", line 75, in __init__
    crytic_compile = CryticCompile(target, **kwargs)
  File "/home/sencha/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 124, in __init__
    self._compile(**kwargs)
  File "/home/sencha/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 931, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/sencha/.local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 156, in compile
    force_legacy_json=force_legacy_json,
  File "/home/sencha/.local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 371, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation Uni.sol:85:16: Error: Expected identifier, got 'LParen'
    constructor(address account, address minter_, uint mintingAllowedAfter_) public {
               ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sencha/.local/bin/slither-check-erc", line 11, in <module>
    sys.exit(main())
  File "/home/sencha/.local/lib/python3.6/site-packages/slither/tools/erc_conformance/__main__.py", line 75, in main
    slither = Slither(args.project, **vars(args))
  File "/home/sencha/.local/lib/python3.6/site-packages/slither/slither.py", line 79, in __init__
    raise SlitherError(f"Invalid compilation: \n{str(e)}")
slither.exceptions.SlitherError: Invalid compilation: 
Invalid solc compilation Uni.sol:85:16: Error: Expected identifier, got 'LParen'
    constructor(address account, address minter_, uint mintingAllowedAfter_) public {
```

Source Code: [Uni](https://github.com/Uniswap/governance/blob/master/contracts/Uni.sol)
Slither: v0.6.14
Slither installed vial: `pip install slither-analyzer`
Also tried installing via:
`git clone https://github.com/crytic/slither.git && cd slither`
`sudo python3 setup.py install`
pip: v9.0.1
OS: Ubuntu 18.04.5 LTS

**Comment by mayanksatnalika** [comment]
Hey were you able to resolve this? Im facing the same issue.

**Comment by naszam** [comment]
Hi @mayanksatnalika,

Make sure you set the right solc version via `solc-select` that you can install via pip:
`$ pip3 install solc-select`
Then install and select the solc version to use:
`$ solc-select install <solc version> (e.g 0.6.12)
`$ solc-select use <solc version> (e.g. 0.6.12)
Then run:
`$ slither-check-erc20 <contract path> <contract name>`

It should work

**Comment by mayanksatnalika** [comment]
thanks a lot, will give this a try.

**Comment by dguido** [comment]
This appears to be a user configuration issue rather than a bug in Slither. The error message indicates that the Solidity compiler (solc) wasn't accessible in the user's PATH:

```
'solc' is not recognized as an internal or external command
```

The issue was resolved by the user installing solc through npm. This is a standard setup requirement for Slither, not a bug in the tool itself. The documentation already covers compiler installation requirements.

Closing as this was a local environment setup issue that was resolved.
