### ISSUE TITLE
AttributeError: module '_sha3' has no attribute 'sha3' when running with Python 3.9 on macOS BigSur

### ISSUE THREAD

**Issue by banescusebi** [crytic/slither#783]
Not sure if anyone else encountered this issue, but after installing slither 0.7.0 via pip I get the following error when trying to run slither on the current directory in a Hardhat project:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/__main__.py", line 712, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/__main__.py", line 82, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/__main__.py", line 67, in process_single
    return _process(slither, detector_classes, printer_classes)
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/__main__.py", line 108, in _process
    detector_results = slither.run_detectors()
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/slither.py", line 183, in run_detectors
    results = [d.detect() for d in self._detectors]
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/slither.py", line 183, in <listcomp>
    results = [d.detect() for d in self._detectors]
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/detectors/abstract_detector.py", line 138, in detect
    all_results = self._detect()
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/detectors/attributes/incorrect_solc.py", line 140, in _detect
    json = self.generate_result(info)
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/detectors/abstract_detector.py", line 221, in generate_result
    output = Output(
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/utils/output.py", line 239, in __init__
    self._data["id"] = hashlib.sha3_256(id_txt.encode("utf-8")).hexdigest()
  File "/usr/local/lib/python3.9/site-packages/sha3/__init__.py", line 97, in sha3_256
    return SHA3256(s)
  File "/usr/local/lib/python3.9/site-packages/sha3/__init__.py", line 30, in __init__
    self._s = _sha3.sha3()
AttributeError: module '_sha3' has no attribute 'sha3'
ERROR:root:None
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/__main__.py", line 712, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/__main__.py", line 82, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/__main__.py", line 67, in process_single
    return _process(slither, detector_classes, printer_classes)
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/__main__.py", line 108, in _process
    detector_results = slither.run_detectors()
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/slither.py", line 183, in run_detectors
    results = [d.detect() for d in self._detectors]
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/slither.py", line 183, in <listcomp>
    results = [d.detect() for d in self._detectors]
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/detectors/abstract_detector.py", line 138, in detect
    all_results = self._detect()
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/detectors/attributes/incorrect_solc.py", line 140, in _detect
    json = self.generate_result(info)
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/detectors/abstract_detector.py", line 221, in generate_result
    output = Output(
  File "/usr/local/lib/python3.9/site-packages/slither_analyzer-0.7.0-py3.9.egg/slither/utils/output.py", line 239, in __init__
    self._data["id"] = hashlib.sha3_256(id_txt.encode("utf-8")).hexdigest()
  File "/usr/local/lib/python3.9/site-packages/sha3/__init__.py", line 97, in sha3_256
    return SHA3256(s)
  File "/usr/local/lib/python3.9/site-packages/sha3/__init__.py", line 30, in __init__
    self._s = _sha3.sha3()
AttributeError: module '_sha3' has no attribute 'sha3'
```

Any hints?

**Comment by montyly** [comment]
Hi @banescusebi, 

Thank you for reporting this. I never saw this issue, it looks like a dependency issue with `pysha3`. 

Can you run:
```bash
$ pip show pysha3
```

**Comment by banescusebi** [comment]
Sure @montyly here's the output:

**Comment by montyly** [comment]
Thanks, this is the expected output.

It might be possible that you have both `sha3` and `pysha3` installed, which can cause an issue.


Can you run this:
```bash
$ pip3 show sha3
```

If you have both installed, you need to remove one (they are going to create conflicts in other packages). 

One way to deal with this, is to use [virtualenv](https://virtualenvwrapper.readthedocs.io/en/latest/):
```bash
pip3 install virtualenvwrapper
source /usr/local/bin/virtualenvwrapper.sh # the location might be different according your system
mkvirtualenv --python=`which python3` slither
pip3 install slither-analyzer
```

Then you can switch to the slither virtualenv from the terminal with : `workon slither`.

**Comment by banescusebi** [comment]
Thank you @montyly that worked for me!
