### ISSUE TITLE
Error when running on solc 0.8.0

### ISSUE THREAD

**Issue by dylankilkenny** [crytic/slither#808]
```
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 712, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 71, in process_all
    compilations = compile_all(target, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 1076, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 137, in __init__
    self._compile(**kwargs)
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/crytic_compile.py", line 987, in _compile
    self._platform.compile(self, **kwargs)
  File "/home/ethsec/.local/lib/python3.6/site-packages/crytic_compile/platform/solc.py", line 180, in compile
    crytic_compile.abis[contract_name] = json.loads(info["abi"])
  File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'list'
ERROR:root:None
ERROR:root:Error in flat.sol
ERROR:root:Traceback (most recent call last):
```

**Comment by montyly** [comment]
Hi @dylankilkenny .

Thank you for reporting this. Can you share the codebase where this happens? I believe we fixed this issue with https://github.com/crytic/crytic-compile/pull/147, and the fix will be available in the next release

**Comment by dylankilkenny** [comment]
The contract is a basic enough extension of [openzepplins erc1155 v4 contract](https://us02web.zoom.us/j/84535678711?pwd=TnM4bkFNNysrYm1EMHc1QVZSb0hLZz09), flattened down to one file to use with slither. Is there an estimate for the next release date?

**Comment by montyly** [comment]
We were aiming for the beginning of the month, but we had some delays. The release should be out soon. 

You can watch the progress here: https://github.com/crytic/slither/issues/789

**Comment by yuetloo** [comment]
Hi, I'm getting the following error that solc-0.8.0 is not recommended for deployment.  Any estimate when solc-0.8.0+ will be supported?  I'm using pip3 install to install slither, slither version is 0.8.1, running on ubuntu.

```
Pragma version0.8.0 (contracts/src/registry/Registry.sol#5) necessitates a version too recent to be trusted. Consider deploying with 0.6.12/0.7.6
17
Pragma version0.8.0 (contracts/tests/RegistryEchidnaTest.sol#5) necessitates a version too recent to be trusted. Consider deploying with 0.6.12/0.7.6
18
solc-0.8.0 is not recommended for deployment
19
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity
20
. analyzed (2 contracts with 75 detectors), 3 result(s) found
```

**Comment by yuetloo** [comment]
It works when I use solc-0.7.6.
