### ISSUE TITLE
ERROR on orfano contract

### ISSUE THREAD

**Issue by matbrgz** [crytic/slither#840]
```
$ slither --version
0.7.1

$ solc --version
solc, the solidity compiler commandline interface
Version: 0.8.4+commit.c7e474f2.Linux.g++

$ python --version
Python 3.8.5
```

```
$ slither orfano.sol 
Traceback (most recent call last):
  File "/home/gates/.local/lib/python3.8/site-packages/slither/__main__.py", line 721, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/gates/.local/lib/python3.8/site-packages/slither/__main__.py", line 82, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/gates/.local/lib/python3.8/site-packages/slither/__main__.py", line 65, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/gates/.local/lib/python3.8/site-packages/slither/slither.py", line 102, in __init__
    self._parser.parse_contracts()
  File "/home/gates/.local/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 380, in parse_contracts
    self._analyze_second_part(contracts_to_be_analyzed, libraries)
  File "/home/gates/.local/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 463, in _analyze_second_part
    self._analyze_struct_events(contract)
  File "/home/gates/.local/lib/python3.8/site-packages/slither/solc_parsing/slitherSolc.py", line 516, in _analyze_struct_events
    contract.analyze_using_for()
  File "/home/gates/.local/lib/python3.8/site-packages/slither/solc_parsing/declarations/contract.py", line 531, in analyze_using_for
    lib_name = parse_type(using_for["libraryName"], self)
  File "/home/gates/.local/lib/python3.8/site-packages/slither/solc_parsing/solidity_types/type_parsing.py", line 357, in parse_type
    raise ParsingError("Type name not found " + str(t))
slither.solc_parsing.exceptions.ParsingError: Type name not found {'id': 1503, 'name': 'SafeMath', 'nodeType': 'IdentifierPath', 'referencedDeclaration': 387, 'src': '28295:8:0'}
ERROR:root:Error:
ERROR:root:Type name not found {'id': 1503, 'name': 'SafeMath', 'nodeType': 'IdentifierPath', 'referencedDeclaration': 387, 'src': '28295:8:0'}
ERROR:root:Please report an issue to https://github.com/crytic/slither/issues
```

**Comment by montyly** [comment]
Hi @matbrgz.

Thank you for your report. We fixed this issue (I believe with https://github.com/crytic/slither/pull/817). I tested this contract with our `dev` branch, and it works. Our upcoming release (https://github.com/crytic/slither/issues/829), next week, will include the fix.
