### ISSUE TITLE
ERROR:root:Type name not found

### ISSUE THREAD

**Issue by Joelpo** [crytic/slither#866]
Hi, 

I am using the docker image coming from crytic/eth-security-toolbox which is also used in our CI environnement. 

slither --version
0.7.1

solc --version
Version: 0.8.3+commit.8d00100c.Linux.g++

`Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 721, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 82, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 65, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 102, in __init__
    self._parser.parse_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 380, in parse_contracts
    self._analyze_second_part(contracts_to_be_analyzed, libraries)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 463, in _analyze_second_part
    self._analyze_struct_events(contract)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 516, in _analyze_struct_events
    contract.analyze_using_for()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/declarations/contract.py", line 531, in analyze_using_for
    lib_name = parse_type(using_for["libraryName"], self)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/solidity_types/type_parsing.py", line 357, in parse_type
    raise ParsingError("Type name not found " + str(t))
slither.solc_parsing.exceptions.ParsingError: Type name not found {'id': 2679, 'name': 'Address', 'nodeType': 'IdentifierPath', 'referencedDeclaration': 3193, 'src': '608:7:19'}
ERROR:root:Error:
ERROR:root:Type name not found {'id': 2679, 'name': 'Address', 'nodeType': 'IdentifierPath', 'referencedDeclaration': 3193, 'src': '608:7:19'}
ERROR:root:Please report an issue to https://github.com/crytic/slither/issues`

Our code is on v0.8.5 of solidity. Any hints on solving this? Also, is there any way of installing the latest versions of slither and solc on the docker image?

**Comment by sledge-dev** [comment]
https://github.com/crytic/slither/issues/807

**Comment by Joelpo** [comment]
I'm closing this issue since this is solved on new version of slither 0.8. 

Note : I'd be nice to have a docker container ready to go with the latests versions.
