### ISSUE TITLE
slither.core.solidity_types.elementary_type.NonElementaryType

### ISSUE THREAD

**Issue by ziedsaidd** [crytic/slither#872]
I have encountered this error while compiling a BSC smart contract with the right solc version. Any ideas? 

Compilation warnings/errors on newcontract080.sol:
Warning: Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
  --> newcontract080.sol:90:1:
   |
90 | contract GNBU is Ownable, Pausable {
   | ^ (Relevant source part starts here and spans across multiple lines).

Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 721, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 82, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 65, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 106, in __init__
    self._parser.analyze_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 391, in analyze_contracts
    self._convert_to_slithir()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 568, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/declarations/function.py", line 1664, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/cfg/node.py", line 709, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 108, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 1559, in apply_ir_heuristics
    irs = propagate_type_and_convert_call(irs, node)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 368, in propagate_type_and_convert_call
    new_ins = propagate_types(ins, node)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 605, in propagate_types
    t = ir.variable_left.type
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/declarations/solidity_variables.py", line 114, in type
    return ElementaryType(SOLIDITY_VARIABLES[self.name])
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/solidity_types/elementary_type.py", line 146, in __init__
    raise NonElementaryType
slither.core.solidity_types.elementary_type.NonElementaryType
ERROR:root:None
ERROR:root:Error in newcontract080.sol
ERROR:root:Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 721, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 82, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 65, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 106, in __init__
    self._parser.analyze_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 391, in analyze_contracts
    self._convert_to_slithir()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 568, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/declarations/function.py", line 1664, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/cfg/node.py", line 709, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 108, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 1559, in apply_ir_heuristics
    irs = propagate_type_and_convert_call(irs, node)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 368, in propagate_type_and_convert_call
    new_ins = propagate_types(ins, node)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slithir/convert.py", line 605, in propagate_types
    t = ir.variable_left.type
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/declarations/solidity_variables.py", line 114, in type
    return ElementaryType(SOLIDITY_VARIABLES[self.name])
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/core/solidity_types/elementary_type.py", line 146, in __init__
    raise NonElementaryType
slither.core.solidity_types.elementary_type.NonElementaryType

**Comment by montyly** [comment]
Hi @ziedsaidd,

Can you share the address of the contract where this happen?

**Comment by ziedsaidd** [comment]
Hi @montyly 
here is the address 0x091fba22fc1fa78c50dee12364efd5e47803321b
here is the code link:
https://testnet.bscscan.com/address/0x091fba22fc1fa78c50dee12364efd5e47803321b#code

**Comment by 0xalpharush** [comment]
This works on the latest release of slither: `0.8.2`
` slither testnet.bsc:0x091fba22fc1fa78c50dee12364efd5e47803321b`
