### ISSUE TITLE
Parsing exception

### ISSUE THREAD

**Issue by bingen** [crytic/slither#882]
Trying to run Slither on [Frax staking contract](https://github.com/FraxFinance/frax-solidity/blob/master/src/hardhat/contracts/Staking/CommunalFarm.sol), I get this error:
```
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 721, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 82, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 65, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 102, in __init__
    self._parser.parse_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 380, in parse_contracts
    self._analyze_second_part(contracts_to_be_analyzed, libraries)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 463, in _analyze_second_part
    self._analyze_struct_events(contract)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 516, in _analyze_struct_events
    contract.analyze_using_for()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/declarations/contract.py", line 531, in analyze_using_for
    lib_name = parse_type(using_for["libraryName"], self)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/solidity_types/type_parsing.py", line 357, in parse_type
    raise ParsingError("Type name not found " + str(t))
slither.solc_parsing.exceptions.ParsingError: Type name not found {'id': 2792, 'name': 'SafeMath', 'nodeType': 'IdentifierPath', 'referencedDeclaration': 3327, 'src': '633:8:3'}
ERROR:root:Error:
ERROR:root:Type name not found {'id': 2792, 'name': 'SafeMath', 'nodeType': 'IdentifierPath', 'referencedDeclaration': 3327, 'src': '633:8:3'}
ERROR:root:Please report an issue to https://github.com/crytic/slither/issues
```

I’m using `eth-security-toolbox` docker image (just pulled, id `2ad73f16de91`) with:

```
docker run -it -v ~/workspace/FraxFinance/frax-solidity:/share trailofbits/eth-security-toolbox
solc-select 0.8.3 # 0.8.4 is not available
cd /share/src/hardhat/
slither contracts/Staking/CommunalFarm.sol
```

**Comment by DavidIsa** [comment]
I'm facing the same issue.

It is happening after adding this line

```
using SafeMath for uint256;
```

This is the contract code

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import './SafeMath.sol';

contract SimpleStorage {
    using SafeMath for uint256;
    uint8 storedData = 5;

    function get() public view returns (uint8) {
        return storedData;
    }
}
```

and this is the output

```
ethsec@16b256917ed6:/share$ slither SimpleStorage.sol 
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 721, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 82, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 65, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 102, in __init__
    self._parser.parse_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 380, in parse_contracts
    self._analyze_second_part(contracts_to_be_analyzed, libraries)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 463, in _analyze_second_part
    self._analyze_struct_events(contract)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 516, in _analyze_struct_events
    contract.analyze_using_for()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/declarations/contract.py", line 531, in analyze_using_for
    lib_name = parse_type(using_for["libraryName"], self)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/solidity_types/type_parsing.py", line 357, in parse_type
    raise ParsingError("Type name not found " + str(t))
slither.solc_parsing.exceptions.ParsingError: Type name not found {'id': 3, 'name': 'SafeMath', 'nodeType': 'IdentifierPath', 'referencedDeclaration': 329, 'src': '118:8:1'}
ERROR:root:Error:
ERROR:root:Type name not found {'id': 3, 'name': 'SafeMath', 'nodeType': 'IdentifierPath', 'referencedDeclaration': 329, 'src': '118:8:1'}
ERROR:root:Please report an issue to https://github.com/crytic/slither/issues
```

**Comment by morrigan** [comment]
Same thing here with Docker but all good when installing through Pip so maybe Docker is not at the latest version?

**Comment by KNeowise** [comment]
I've got the same problem with Docker too, so I ran `pip3 install slither-analyzer` inside the container to upgrade to 0.8.0. It works fine.

**Comment by montyly** [comment]
Hi, we are currently having troubles with our automated build of eth-security-toolbox (https://github.com/crytic/eth-security-toolbox/issues/20). As a result the docker uses currently tools that are outdated.

I recommend using a locally installed version of slither until we fix eth-security-toolbox
