### ISSUE TITLE
Support for free functions

### ISSUE THREAD

**Issue by axic** [crytic/slither#911]
It seems that slither does not fully support free functions which were introduced in 0.7.1. I'm using `slither-analyzer 0.8.0` which was installed via pip3.

A simple example is inspired by balancer, where I came across this issue (`_require` from [BalancerErrors.sol](https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/solidity-utils/contracts/helpers/BalancerErrors.sol) is used by most of the contracts).

File `helper.sol`:
```
function _require(bool condition, uint256 errorCode) pure {
    if (!condition) revert();
}
```

File `test.sol`:
```
import "./helpers.sol";

contract C {
  function f() external {
    _require(msg.sender != address(0), 42);
  }
}
```

The above results in the following trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slither/__main__.py", line 723, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.9/site-packages/slither/__main__.py", line 82, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.9/site-packages/slither/__main__.py", line 65, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/usr/local/lib/python3.9/site-packages/slither/slither.py", line 102, in __init__
    parser.parse_contracts()
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 384, in parse_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 490, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 557, in _analyze_variables_modifiers_functions
    self._analyze_content_top_level_function()
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 542, in _analyze_content_top_level_function
    func_parser.analyze_content()
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/declarations/function.py", line 316, in analyze_content
    node_parser.analyze_expressions(self)
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/cfg/node.py", line 33, in analyze_expressions
    expression = parse_expression(self._unparsed_expression, caller_context)
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 639, in parse_expression
    return parse_call(expression, caller_context)
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 488, in parse_call
    called = parse_expression(expression["expression"], caller_context)
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 802, in parse_expression
    var = find_variable(value, caller_context, referenced_declaration)
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 336, in find_variable
    assert isinstance(underlying_func, FunctionContract)
AssertionError
ERROR:root:None
ERROR:root:Error in .
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slither/__main__.py", line 723, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.9/site-packages/slither/__main__.py", line 82, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/usr/local/lib/python3.9/site-packages/slither/__main__.py", line 65, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/usr/local/lib/python3.9/site-packages/slither/slither.py", line 102, in __init__
    parser.parse_contracts()
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 384, in parse_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 490, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 557, in _analyze_variables_modifiers_functions
    self._analyze_content_top_level_function()
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 542, in _analyze_content_top_level_function
    func_parser.analyze_content()
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/declarations/function.py", line 316, in analyze_content
    node_parser.analyze_expressions(self)
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/cfg/node.py", line 33, in analyze_expressions
    expression = parse_expression(self._unparsed_expression, caller_context)
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 639, in parse_expression
    return parse_call(expression, caller_context)
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 488, in parse_call
    called = parse_expression(expression["expression"], caller_context)
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 802, in parse_expression
    var = find_variable(value, caller_context, referenced_declaration)
  File "/usr/local/lib/python3.9/site-packages/slither/solc_parsing/expressions/expression_parsing.py", line 336, in find_variable
    assert isinstance(underlying_func, FunctionContract)
AssertionError
```

The referred `isinstance` has a comment that the variable should be part of a contract or a function.

**Comment by montyly** [comment]
Hi @axic,

Thanks for reporting this. Indeed it seems that we don't support lookup within a top-level / free functions (ex: here slither can't do the lookup on `revert()` here)

We will add the support, and improve the tests coverage for the top level functions

**Comment by axic** [comment]
@montyly do you have any ETA for this?

**Comment by montyly** [comment]
Not a precise one, but we will work on this in September

**Comment by axic** [comment]
@montyly is this supported by #945 now?

**Comment by montyly** [comment]
Hi @axic. Similar to the other issues, I merged the fix in master, it will be available in the next release

**Comment by axic** [comment]
Thanks!
