### ISSUE TITLE
Cannot Parse OpenZeppelin ERC-1155 Implementation

### ISSUE THREAD

**Issue by Thomas-Sciaroni** [crytic/slither#913]
When running slither against https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/ERC1155.sol one receives this error:

```
slither contracts/ExternalContracts/ERC1155.sol
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 721, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 82, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 65, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 102, in __init__
    self._parser.parse_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 380, in parse_contracts
    self._analyze_second_part(contracts_to_be_analyzed, libraries)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 463, in _analyze_second_part
    self._analyze_struct_events(contract)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slitherSolc.py", line 516, in _analyze_struct_events
    contract.analyze_using_for()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/declarations/contract.py", line 531, in analyze_using_for
    lib_name = parse_type(using_for["libraryName"], self)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/solidity_types/type_parsing.py", line 357, in parse_type
    raise ParsingError("Type name not found " + str(t))
slither.solc_parsing.exceptions.ParsingError: Type name not found {'id': 17, 'name': 'Address', 'nodeType': 'IdentifierPath', 'referencedDeclaration': 1376, 'src': '518:7:2'}
ERROR:root:Error:
ERROR:root:Type name not found {'id': 17, 'name': 'Address', 'nodeType': 'IdentifierPath', 'referencedDeclaration': 1376, 'src': '518:7:2'}
ERROR:root:Please report an issue to https://github.com/crytic/slither/issues
```

The contract parses correctly if you remove [this declaration](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/b174f067df18e3214f290c62d50f6721e87c05cf/contracts/token/ERC1155/ERC1155.sol#L20) and change these two function calls: [1](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/b174f067df18e3214f290c62d50f6721e87c05cf/contracts/token/ERC1155/ERC1155.sol#L409) [2](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/b174f067df18e3214f290c62d50f6721e87c05cf/contracts/token/ERC1155/ERC1155.sol#L430)

**Comment by montyly** [comment]
Hi @Thomas-Sciaroni ,

Thank you for reporting this.

Did you make any changes to ERC1155? What version of Slither are you using? (`slither --version`)

When I run `slither contracts/token/ERC1155/ERC1155.sol`, with Slither 0.8.0, on the latest ERC1155 version (commit `b174f067df18e3214f290c62d50f6721e87c05cf`), I do not have this issue

**Comment by Thomas-Sciaroni** [comment]
Hello @montyly !

I did not modify the ERC1155 contract at all.

This error is on slither 0.7.1, which is the version included in the trailofbits/eth-security-toolbox docker image.

Seems this issue is more with the prebuilt docker image than Slither itself so I'll close this issue.
