### ISSUE TITLE
Dockerizing latest for Apple M1 Silicon

### ISSUE THREAD

**Issue by daithi-coombes** [crytic/slither#937]
I think the `Dockerfile` needs looking at, hasn't been updated since 2 Sep 2020. I'm working on an Apple Silicon M1 chip (arm64) and hitting issues.

Here's what I've done and why
  1. upgraded base ubuntu to xenial (no maifest for arm64 with bionic)
  2. install pip3 in `Dockerfile` to install `crytic-compile` and `prettytable` (`RUN ... setup.py...` step couldn't find them)
  3. now builds but with error:

```
% docker run --rm daithi/slither:local slither --help
Traceback (most recent call last):
  File "/home/slither/.local/bin/slither", line 9, in <module>
    load_entry_point('slither-analyzer==0.8.1', 'console_scripts', 'slither')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/slither/.local/lib/python3.5/site-packages/slither_analyzer-0.8.1-py3.5.egg/slither/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/home/slither/.local/lib/python3.5/site-packages/slither_analyzer-0.8.1-py3.5.egg/slither/slither.py", line 61
    self._disallow_partial: bool = kwargs.get("disallow_partial", False)
                          ^
SyntaxError: invalid syntax
```

OS:
```
Darwin 20.5.0 Darwin Kernel Version 20.5.0 RELEASE_ARM64_T8101 arm64
```

Docker:
```
Client:
 Version:           20.10.7
 API version:       1.41
 OS/Arch:           darwin/arm64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  Git commit:       b0f5bc3
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.6
  ```

**Comment by daithi-coombes** [comment]
^ python version should be '>=3.6', above is running on 3.5

**Comment by daithi-coombes** [comment]
also if anyone needs it, I've pushed an image with the latest version that works on Apple Silicon M1 arm64 chipsets here:
https://hub.docker.com/repository/docker/daithi/slither

**Comment by dguido** [comment]
Thanks so much! We'll look at getting this integrated.
