### ISSUE TITLE
unresolved reference to identifier

### ISSUE THREAD

**Issue by z3roTo0ne** [crytic/slither#957]
code:
```
function ecdsaRecover(bytes32 message, bytes calldata encodedSignature)
        internal
        pure
        returns (address signer)
    {
        require(
            encodedSignature.length == ECDSA_SIGNATURE_LENGTH,
            "GPv2: malformed ecdsa signature"
        );

        bytes32 r;
        bytes32 s;
        uint8 v;

        // NOTE: Use assembly to efficiently decode signature data.
        // solhint-disable-next-line no-inline-assembly
        assembly {
            // r = uint256(encodedSignature[0:32])
            r := calldataload(encodedSignature.offset)
            // s = uint256(encodedSignature[32:64])
            s := calldataload(add(encodedSignature.offset, 32))
            // v = uint8(encodedSignature[64])
            v := shr(248, calldataload(add(encodedSignature.offset, 64)))
        }

        signer = ecrecover(message, v, r, s);
        require(signer != address(0), "GPv2: invalid ecdsa signature");
    }
```

Got this error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/__main__.py", line 741, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/__main__.py", line 83, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/__main__.py", line 66, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/slither.py", line 102, in __init__
    parser.parse_contracts()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 386, in parse_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 492, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 558, in _analyze_variables_modifiers_functions
    contract.analyze_content_functions()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/declarations/contract.py", line 354, in analyze_content_functions
    function_parser.analyze_content()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/declarations/function.py", line 319, in analyze_content
    node_parser.analyze_expressions()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/yul/parse_yul.py", line 319, in analyze_expressions
    node.analyze_expressions()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/yul/parse_yul.py", line 59, in analyze_expressions
    expression = parse_yul(self._scope, self, self._unparsed_expression)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/yul/parse_yul.py", line 781, in parse_yul
    op = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/yul/parse_yul.py", line 669, in parse_yul_assignment
    return _parse_yul_assignment_common(root, node, ast, "variableNames")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/yul/parse_yul.py", line 647, in _parse_yul_assignment_common
    rhs = parse_yul(root, node, ast["value"])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/yul/parse_yul.py", line 781, in parse_yul
    op = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/yul/parse_yul.py", line 673, in parse_yul_function_call
    args = [parse_yul(root, node, arg) for arg in ast["arguments"]]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/yul/parse_yul.py", line 673, in <listcomp>
    args = [parse_yul(root, node, arg) for arg in ast["arguments"]]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/yul/parse_yul.py", line 781, in parse_yul
    op = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/slither/solc_parsing/yul/parse_yul.py", line 752, in parse_yul_identifier
    raise SlitherException(f"unresolved reference to identifier {name}")
slither.exceptions.SlitherException: unresolved reference to identifier encodedSignature.offset
```

**Comment by chichke** [comment]
.offset Doesn't work with slither :/

**Comment by chichke** [comment]
https://github.com/crytic/slither/pull/1057

**Comment by 0xalpharush** [comment]
Fixed by https://github.com/crytic/slither/pull/1057
