### ISSUE TITLE
'NoneType' object has no attribute 'compilation_unit'

### ISSUE THREAD

**Issue by onigirisan** [crytic/slither#989]
Hi，What is this problem and how should I solve it?

$ slither .
'npx hardhat compile --force' running
Compiling 44 files with 0.8.4
Compilation finished successfully

Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 741, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 83, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 66, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 102, in __init__
    parser.parse_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 386, in parse_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 492, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 559, in _analyze_variables_modifiers_functions
    self._analyze_content_top_level_function()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 544, in _analyze_content_top_level_function
    func_parser.analyze_content()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/declarations/function.py", line 319, in analyze_content
    node_parser.analyze_expressions()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 319, in analyze_expressions
    node.analyze_expressions()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 59, in analyze_expressions
    expression = parse_yul(self._scope, self, self._unparsed_expression)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 781, in parse_yul
    op = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 669, in parse_yul_assignment
    return _parse_yul_assignment_common(root, node, ast, "variableNames")
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 646, in _parse_yul_assignment_common
    lhs = [parse_yul(root, node, arg) for arg in ast[key]]
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 646, in <listcomp>
    lhs = [parse_yul(root, node, arg) for arg in ast[key]]
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 783, in parse_yul
    op.set_offset(ast["src"], root.compilation_unit)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 140, in compilation_unit
    return self._contract.compilation_unit
AttributeError: 'NoneType' object has no attribute 'compilation_unit'
None
Error in .
Traceback (most recent call last):
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 741, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 83, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/__main__.py", line 66, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/slither.py", line 102, in __init__
    parser.parse_contracts()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 386, in parse_contracts
    self._analyze_third_part(contracts_to_be_analyzed, libraries)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 492, in _analyze_third_part
    self._analyze_variables_modifiers_functions(contract)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 559, in _analyze_variables_modifiers_functions
    self._analyze_content_top_level_function()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 544, in _analyze_content_top_level_function
    func_parser.analyze_content()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/declarations/function.py", line 319, in analyze_content
    node_parser.analyze_expressions()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 319, in analyze_expressions
    node.analyze_expressions()
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 59, in analyze_expressions
    expression = parse_yul(self._scope, self, self._unparsed_expression)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 781, in parse_yul
    op = parsers.get(ast["nodeType"], parse_yul_unsupported)(root, node, ast)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 669, in parse_yul_assignment
    return _parse_yul_assignment_common(root, node, ast, "variableNames")
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 646, in _parse_yul_assignment_common
    lhs = [parse_yul(root, node, arg) for arg in ast[key]]
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 646, in <listcomp>
    lhs = [parse_yul(root, node, arg) for arg in ast[key]]
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 783, in parse_yul
    op.set_offset(ast["src"], root.compilation_unit)
  File "/home/ethsec/.local/lib/python3.6/site-packages/slither/solc_parsing/yul/parse_yul.py", line 140, in compilation_unit
    return self._contract.compilation_unit
AttributeError: 'NoneType' object has no attribute 'compilation_unit'

**Comment by montyly** [comment]
Hi @onigirisan ,

Thank you for reporting this. Can you share the codebase where this happens? 

We might already have fixed it with https://github.com/crytic/slither/pull/987, which will be available in the upcoming release (https://github.com/crytic/slither/issues/979)
